### ISSUE TITLE
listCatalogItems request rate

### ISSUE THREAD

**Issue by limenote135** [amzn/selling-partner-api-docs#101]
I often use GetMatchingProductForId with EAN code. This API has 20 requests quota and can be requested18000 per hour. However, listCatalogItems is limited only 1 request per second, so I can get only 3600 items per hour.

Is it possible to increase this limit? Should I create a support case?

**Comment by vikingcodes** [comment]
@limenote135 On GetMatchingProductForId  MWS support maximum 20 Requests. Maximum 18000 requests per hour.

I think you should use listCatalogItems of SPAPI to get matching Products.

As per SPAPI document

https://github.com/amzn/selling-partner-api-docs/blob/main/references/catalog-items-api/catalogItemsV0.md#listcatalogitems

listCatalogItems  API showing 1 request per second.

Have you tried multiple ASINs? Try 5 at least.

**Comment by limenote135** [comment]
@vikingcodes Oh, sorry, it's not getCatalogItem but listCatalogItems.

Is listCatalogItems possible to submit multiple EAN in single request?

**Comment by vikingcodes** [comment]
@limenote135 Not sure, I never tried. But you can. And let me know result.

**Comment by ericblade** [comment]
1 req per second *does* seem a bit on the light side for this.

**Comment by callumb123** [comment]
Bumping this up as even though the docs say the restore rate is 1 per second this only works for about 10-15 seconds and then it starts saying the limit has been exceeded despite sending at the same rate. Hopefully someone can take a look at this soon.

**Comment by ericblade** [comment]
When I say it's a "bit" on the light side, i mean, that if listCatalogItems is this API's version of GetMatchingProductForId, then it is woefully lacking. I could see it being limited that much for search requests, but for identifier requests, i could easily see people needing a lot more than 1 per second.

**Comment by graedwin** [comment]
Hi @limenote135, We will need to work with you via a support case to resolve this issue. Please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation.

**Comment by limenote135** [comment]
Hi @graedwin , I have already opened a support case (2142415203) and got some responses (probably from @ShivikaK ), but I don't get an answer about this issue yet.

**Comment by ulandj** [comment]
Hi @graedwin , @ShivikaK ,
We can retrieve 5 products' details passing SellerSKU params in a single request using `GetMatchingProductForId` method of the MWS API. But in the `ListCatalogItems` of SP API we can get only one product's details using SellerSKU which means we will have to do 4 extra requests.
Do you know if there are any ways to fetch details of multiple products in a single request? Or is there a plan to improve `ListCatalogItems` endpoint of SP API so that we could request 5 or more products' details passing SellerSKU parameter with multiple SKUs? i.e. to do the same as `GetMatchingProductForId` of the MWS API ?
Thanks
