### ISSUE TITLE
GET_FLAT_FILE_GEO_OPPORTUNITIES: Request for report type 23900 is not allowed at this time

### ISSUE THREAD

**Issue by moltar** [amzn/selling-partner-api-docs#1021]
Requesting report:

```json
{
    "marketplaceIds": ["ATVPDKIKX0DER"],
    "reportType": "GET_FLAT_FILE_GEO_OPPORTUNITIES",
    "dataStartTime": "2021-07-11",
    "dataEndTime": "2021-07-11"
}
```

Get:

```json
{
    "errors": [
        {
            "code": "InvalidInput",
            "message": "Request for report type 23900 is not allowed at this time",
            "details": ""
        }
    ]
}
```

Any ideas?

**Comment by ShivikaK** [comment]
Hello @moltar 

Thank you for raising this issue.

We are currently investigating the error you receiving and will provide an update accordingly.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by ShivikaK** [comment]
Hello @moltar 

This Report Type is no longer active which is why you are getting an error on requesting it. 

The documentation will be updated to remove this inactive report type as well.

Please let me know if you have any further concerns/questions regarding this.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by moltar** [comment]
How do reports get deactivated? Is there an announcement or something? I haven't seen any communications or warnings in regards to this report going out of availability.

**Comment by tspicer** [comment]
@ShivikaK as @moltar suggests, this begs a larger question on the status and viability of all other reports going forward. If a report is deprecated, we do not seem to have a way to care for this. If there is no schedule published for report deprecation, then at least the error response should indicate this is no longer a viable report. The current error implies the issue is transitory, not permanent removal.

**Comment by moltar** [comment]
> then at least the error response should indicate this is no longer a viable report.

Would a perfect use case for that `detail` key on the error object.

**Comment by ShivikaK** [comment]
Hello everyone,

Thank you for your valued feedback. 

I will be working with the engineering team regarding this and also investigate if the error messaging can be improved to convey deprecation of a report type.

Thanks,
Shivika Khare
Selling Partner API Developer Support
