### ISSUE TITLE
The security token included in the request is invalid.

### ISSUE THREAD

**Issue by dingzheyan** [amzn/selling-partner-api-docs#108]
why？when i get this url https://sellingpartnerapi-eu.amazon.com/orders/v0/orders?OrderStatuses=Unshipped&version=beta
it is return The security token included in the request is invalid.

**Comment by roger-sanchez117** [comment]
Are you sure that the security token corresponds to the AccessKey and SecretKey that you are using to sign the request?

**Comment by dingzheyan** [comment]
i don't know what  security token,i had x-amz-access-token from https://api.amazon.co.uk/auth/o2/token, and add to header,
this x-amz-access-token use  AccessKey and SecretKey is same to sign .

**Comment by roger-sanchez117** [comment]
Your problem lies in access and authentication. Apparently if you followed the application registration guide and used the role's ARN to register your application you must include a security token that you can get from the assumeRole operation (https://sts.amazonaws.com/?Action=AssumeRole).

Personally this did not work for me and I re-registered my application but with the ARN of the IAM user.

**Comment by dingzheyan** [comment]
i had get  SessionToken from  https://sts.amazonaws.com/?Action=AssumeRole, and add it to header ： X-Amz-Security-Token
，but it  still return The security token included in the request is invalid.

**Comment by rogersv** [comment]
Did you also use the Id and secret from the assume role response? You need to use those parameters instead of the users Id and secret.
