### ISSUE TITLE
[BUG] Sandbox URL doesn't work

### ISSUE THREAD

**Issue by MayuBen1027** [amzn/selling-partner-api-docs#1128]
Whenever I call the sandbox I get the following error: 

{
    "errors": [
        {
            "message": "We encountered an internal error. Please try again.",
            "code": "InternalFailure"
        }
    ]
}

If I take the exact same call and do it to production. it works.

Any ideas what I am doing wrong?

**Comment by ShivikaK** [comment]
Hello @MayuBen1027 

Thank you for raising this issue.

The SP API sandbox works like many mocking frameworks; it uses pattern matching to return a specified response when the specified parameters are present. 

A developer receives a response defined in the x-amazon-spds-sandbox-behaviors object when they send a request that matches the specified parameters.

If the request sent to the sandbox endpoint does not match the parameter values in the x-amazon-spds-sandbox-behaviors object, you will receive a "500 Internal Server Error" in the response. You must send the request with the exact values specified in the model.

Please provide us with request details for the sandbox request to verify if the 500 error is due to missing required parameters from the sandbox object of that API.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by MayuBen1027** [comment]
This is the URL I am using: https://sandbox.sellingpartnerapi-na.amazon.com/vendor/directFulfillment/shipping/v1/shippingLabels

And here is the body: 
{ "shippingLabelRequests" : [ { "purchaseOrderNumber" : "123456789", "sellingParty" : { "partyId" : "123456", "address" : { "name" : "Test", "addressLine1" : "Test", "addressLine2" : "Test", "addressLine3" : "Test", "city" : "Test", "county" : "Test", "district" : "Test", "stateOrRegion" : "Test", "postalCode" : "Test", "countryCode" : "Test", "phone" : "Test" } }, "shipFromParty" : { "partyId" : "123456", "address" : { "name" : "Test", "addressLine1" : "Test", "addressLine2" : "Test", "addressLine3" : "Test", "city" : "Test", "county" : "Test", "district" : "Test", "stateOrRegion" : "Test", "postalCode" : "Test", "countryCode" : "Test", "phone" : "Test" } } } ] }

**Comment by Emizy** [comment]
Sandbox returning 403 AccessDenied Exception.

Any help on this?

**Comment by coder771** [comment]
@MayuBen1027 were you able to solve this?
