### ISSUE TITLE
Missing TaxRegistrationDetails in ordersAPI

### ISSUE THREAD

**Issue by fernlop** [amzn/selling-partner-api-docs#115]
I'm not receiving the tax Information like i was used to with the MWS API. 
It looked like this:

`<TaxRegistrationDetails>
     <member>
        <taxRegistrationId>**********</taxRegistrationId>
        <taxRegistrationAuthority>
            <country>DE</country>
        </taxRegistrationAuthority>
        <taxRegistrationType>VAT</taxRegistrationType>
    </member>
</TaxRegistrationDetails>`

I have the permissions to view this information, so this shouldn't be the problem. I don't see anything about this in the documentation too.

**Comment by shubham-verma-1** [comment]
@fernlop Were you able to resolve this issue? We are also unable to find those details and wanted to check the format how this node is coming in SP API response.

**Comment by fernlop** [comment]
@shubham-verma-1 
No and the support is not able to give us an answer for this. My case is open since May 13th.
On September 1st they told me the case was forwarded to the engineering team.

**Comment by kevinvenclovas** [comment]
Same issue TaxRegistrationDetails on the new SP API does not existing.

Someone fixed this issue and get the tax infomations?

**Comment by rugved1991** [comment]
Hi @fernlop,

You should be able to pull the TaxRegistration information for an order using getOrders operation. You would be able to get [BuyerTaxInformation](https://developer-docs.amazon.com/sp-api/docs/orders-api-v0-reference#buyertaxinformation) in the getOrders response. 
This field is available only in TR marketplace. Can you provide more information on why you need this information in a different marketplace? 

Best,
Rugved
Solutions Architect, SP API

**Comment by kevinvenclovas** [comment]
@rugved1991 
Hi thank you for joining our discussion.

My companie need the BuyerTaxInformation to write invoices for business customers. We cannot write correct and tax free invoices witout the taxnumber.

So that is really nesesary for us.

Currently we get the information with the old mws api but we need this also in the new sp api. We cannot migrate our application to the new api without this informations. 

Thats a realy big problem for our tax office when we write tax free invoices without tax number!

Thank you!

**Comment by Rajesh-ExertisGO** [comment]
@rugved1991 

We are facing the same issue with SP API.

For business customers we will have to capture the VAT number to generate the invoices correctly and we dont see that coming on the orders API.

Thank you.

**Comment by hildickethan-S73** [comment]
@rugved1991 

Are there any plans for this being rolled out to other marketplaces?

We are also facing the issue with SP.

We sync all our orders and invoice them manually, in order to create the invoices correctly, we need the VAT number for the buyer in the case of it being a business.

In MWS this comes when available through `TaxRegistrationDetails`, but in SP it's as you say, only available to TR marketplace. I haven't been able to find any reasoning for this restriction and why it is no longer available for the rest.

A work-around I have seen in other issues is getting the information from an Orders report, but this extra step of requesting, waiting for processing and adjusting contacts with it takes a lot more time and requests to the server to do, making it fix contacts every x minutes with a report instead of on sync.

I believe the most appropriate way of doing it is making it restricted data like the Buyer Info or Shipping Address

Thank you

**Comment by lw-andrewsmith** [comment]
+1
Since we've migrated our clients to SP-API as requested before the 30th July cutoff date. We now have client complaints about the fact the buyers VAT ID is no longer returned in the order data to generate invoices for business orders and as such we're no longer generating accurate invoices for Vat Invoice Document Upload in EU marketplaces.

**Comment by clement-hollander** [comment]
@rugved1991 any update on this bug ? thanks

**Comment by clement-hollander** [comment]
@rugved1991 can we have an update ? thanks

**Comment by greenhof** [comment]
> Hi,
> 
> Thanks for sharing your concerns regarding this issue. We are working with the internal teams to fix this issue. I will provide an update when the fix is available publicly.
> 
> Best, Rugved Solutions Architect, SP API

any updates on this?

**Comment by chrisskhoury** [comment]
Hello @greenhof,

You can rely on the GET_FLAT_FILE_ORDER_REPORT_DATA_INVOICING report to return the missing Buyer Tax Information.
It can include data on Amazon Business orders, but the Seller has to enable these columns on ColumnPicker page in Seller Central.

It can be seen that for these fields(buyer-tax-registration-id, buyer-tax-registration-country, and buyer-tax-registration-type), they are controlled by the merchant's preference: isBuyerTaxIdentifierEnabledInOrderReports (SC)
 
To do so, go to the page [Add or remove order report columns 18](https://sellercentral-europe.amazon.com/order-reports-and-feeds/column-picker), enable Buyer tax identifiers and Buyer company name, and save your changes.


You can also rely on the SC_VAT_TAX_REPORT but this is available only for sellers that are enrolled in VCS.

Best,
Chris
Solutions Architect, SP API

**Comment by clement-hollander** [comment]
@chrisskhoury this is not a solution for us, we would need to merge Orders API with Report API to get full data for an order ? Why can't we have this information in Orders API ?
