### ISSUE TITLE
Report been Cancled

### ISSUE THREAD

**Issue by Feng-Xg** [amzn/selling-partner-api-docs#1262]
Some report status is **Cancled** ,What the reason?

**Comment by gaurav-webs** [comment]
@Feng-Xg 

if you have reviewed the [Report API documentation](https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reports_2021-06-30.md#processingstatuses) then you can find this



Value | Description
----- | -----------
CANCELLED | The report was cancelled. There are two ways a report can be cancelled: an explicit cancellation request before the report starts processing, or an automatic cancellation if there is no data to return.
DONE | The report has completed processing.
FATAL | The report was aborted due to a fatal error.
IN_PROGRESS | The report is being processed.
IN_QUEUE | The report has not yet started processing. It may be waiting for another IN_PROGRESS report.
