### ISSUE TITLE
PII Access Request

### ISSUE THREAD

**Issue by hkncnr07** [amzn/selling-partner-api-docs#1331]
Hi,
I've been trying for a very long time to approve access to PII data.
Although I submitted the requested data several times, my applications were not accepted.
I have sent the requested information again. Could you please review and approve my application with the 8658933181 case number?
This is very urgent for our software team and business process.
Thanks

**Comment by misterakko** [comment]
Shall we found a club?
I've been waiting for more than one year. We open a case, we explain painfully everything we're doing to protect the PII data (encryption at rest, role separation, logs, the whole shebang), it gets dismissed in a couple of months with no explanation. It seems impossibile to talk with a human being.
From where I'm sitting, it looks like Amazon gave PII permission to almost everybody who asked years ago. If you were accepted, you keep seeing PIIs. If you didn't at the time, no chance to find someone to listen to your case. Or, well, I don't know, maybe if you are at IBM or some other huge company you get flagged.
I'm very frustrated because fro 2015 to 2018 we rented our libraries to customers and all of them get PIIs today. In 2019 we changed business model and tried using MPW, then SP-API, as it's meant to be used (the seller authorises you to make requests in their name). But the very same code is not authorised my Amazon to get PIIs.

**Comment by jchavest13** [comment]
Hi evryone,

@hkncnr07 - Please accept our apologies for the delay getting back to you on your case. We thank you for your patience while we work to address your case as soon as possible.
Please  ensure you monitor your Seller Central account for any pending case  updates where your response may be needed to fully meet the requirements  of our Data Protection and Acceptable Use policies.

@misterakko - Can you please provide your most recent Developer Registration case ID, so I can further review it?

Regards,
Julian
Developer Registration Specialist, SP-API

**Comment by misterakko** [comment]
Hi @jchavest13. First, thank you sincerely for your kind offer, very much appreciated. The most recent developer case id was #6570842602
But I noticed that this summer you added more questions, and it's probably better if I rewrite our answers in English rather than the original Italian  (I very much fear automatic translations, as it's very easy to loose nuances). I can open a new case or send directly my answers to you, if it helps.
Also, I beg your pardon if I sounded harsh; much of my frustration derives from the lack of interaction. If we were told "you are lacking in this, this and this" I can kick myself, try to do better and/or throw in the towel. But since we are only asking to get the shipping addresses to which the seller must send the parcels and only want to keep those addresses for the shortest amount of time (just until the customer can't ask for a refund), well,  when we're answered with just a "no" it's ulcers time...

**Comment by gopackagingproducts** [comment]
Hi @jchavest13

SP-API Developer Profile Created
Case ID: 7077840972 
Thank you for completing your Amazon Selling Partner API (SP-API) Developer Profile.
Your request for access to SP-API has been APPROVED

My organisation participates in Amazon Services Europe, and I want to integrate to manage my own business only.

We created api and status is Draft.  

We would like to enerate shipping labels and send Amazon orders directly to customers. For this we need buyer name and complete delivery address. But buyer name and address line 1.

Please advise.

Many thanks

**Comment by hkncnr07** [comment]
> Hi evryone,
> 
> @hkncnr07 - Please accept our apologies for the delay getting back to you on your case. We thank you for your patience while we work to address your case as soon as possible.
> Please ensure you monitor your Seller Central account for any pending case updates where your response may be needed to fully meet the requirements of our Data Protection and Acceptable Use policies.
> 
> @misterakko - Can you please provide your most recent Developer Registration case ID, so I can further review it?
> 
> Regards,
> Julian
> Developer Registration Specialist, SP-API

**Comment by hkncnr07** [comment]
Hi @jchavest13 ,

Thanks for your answer.
We have completed requested information but then we never get reply from Amazon.
Our case is still in Pending Amazon Action status.

Can you please contact related team and help us?

Case Id: 8658933181

Thanks

**Comment by jchavest13** [comment]
Hi everyone,

@misterakko - Upon review, looks like your case was resolved some time ago. So yes, I'd recommend you to submit a new one, especially considering that, as you said, there are new questions available in Developer Profile now. Once submitted your case will be evaluated accordingly and you will be contacted through the case if any additional information is required from your end.

@gopackagingproducts - You should be able to make updates and apply for additional access roles if needed, using the link below:
https://sellercentral-europe.amazon.com/developer/register

@hkncnr07 - I actually created an internal request on 09/03/2021 for them to review your appeal and proceed accordingly. We appreciate your patience on this matter and will work to address your case as soon as possible.

Regards,
Julian
Developer Registration Specialists, SP-API

**Comment by MojoManager** [comment]
Hi jchavest13 ,

Our github account was flagged and all tickets were spammed. Now it's active.  Please check following. 

SP-API Developer Profile Update : Restricted Access Request
Case ID 7287202882

We also experiencing the same problem with regards to getting access to the
Direct-to-Consumer Delivery(Restricted) API. Any help to get approved and access to the SP-API

Thank you for your response.

We have completed our assessment and have determined at this point in time that you are not eligible for Restricted SP-API access to build a publicly available application. While we appreciate your submission, we reserve Restricted SP-API access for developers that represent the greatest benefit to Amazon Customers and Selling Partners. As our Marketplace Appstore and your application evolve, you may reapply for this access in the future.

No changes have been made to your SP-API access at this time.

Please advise

Many thanks
Mojo Manager

**Comment by misterakko** [comment]
Hi @jchavest13 I tried again (case 7375723092) and again I was denied. This time, though, I was given a reason: «we only consider sharing Customer data (“Restricted access”) with third party Developers that offer features that are materially different from existing applications»
It looks like nobody bothered to read what we painstakingly wrote. There are exactly eight app developers in Italy, including us. Nobody but us has a solution which exports one's inventory simultaneously to Amazon, eBay Italy, ePrice, AbeBooks, Maremagnum, IBS. Please notice that three of the six are Italy-only websites, so I doubt that anybody ever will.

**Comment by misterakko** [comment]
After months, I'm leaving a comment here as a warning to other developers. Nobody will listen yo you about PIIs. The only way to get PIIs is to already get PIIs, as nobody at Amazon vets old accounts. Their security team is non-existent to unresponsive. I guess that maybe if you set up a new software solution without asking for PIIs and then you sell a billion euros of merchandise on their platform and then you ask for PIIs, someone could be bothered to look into you. But it's only guesswork.
All in all a clusterfuck that will leave your business and your very job at high risk. Tread with utmost care.
