### ISSUE TITLE
[BUG] Got an 403 Access to requested resource denied

### ISSUE THREAD

**Issue by t-poeschl** [amzn/selling-partner-api-docs#1374]
Hello, everyone

I've been working on the SP-API for several hours now and only ever get a 403 Unauthorized when querying the ListCatalogItems.

Error:
[403] Client error: `GET https://sellingpartnerapi-eu.amazon.com/catalog/v0/items?MarketplaceId=A1PA6795UKMFR9` resulted in a `403 Forbidden` response:
    {
      "errors": [
        {
          "message": "Access to requested resource is denied.",
         "code": "Unauthorized",
         "det (truncated...)

Here are my Response-Headers:
 #responseHeaders: array:7 [▼
    "x-amzn-RequestId" => array:1 [▼
      0 => "cdd3678d-79e3-47c1-b025-d0b3f642d142"
    ]
    "x-amzn-ErrorType" => array:1 [▼
      0 => "AccessDeniedException"
    ]
    "x-amz-apigw-id" => array:1 [▼
      0 => "FYioAG1njoEF_gA="
    ]
  ]

Do you have an idea?

Regards
Tobias

**Comment by ShivikaK** [comment]
Hello @t-poeschl 

Thank you for raising this issue.

To help troubleshoot access denied issues, we have a FAQ with list of steps to follow to investigate the root cause for this error. Please refer to below link for FAQs -

https://github.com/amzn/selling-partner-api-docs/wiki/SP-API---General-FAQs

[Why am I getting Unauthorized - Access Denied error (403 error code) for my API request after completing registration successfully?]

If error persists, you can open a support case with us to further investigate the issue.

Thanks,
Shivika Khare
Selling Partner API Developer Support
