### ISSUE TITLE
Invalid Input

### ISSUE THREAD

**Issue by zhanfjunjun** [amzn/selling-partner-api-docs#139]
When I requested feeds/2020-09-04/documents, I received an error Invalid Input. No matter what the contentType parameter is written, it is this error. Of course, when the contentType parameter does not exist, an error will be reported as missing one or more parameter

![1606204350(1)](https://user-images.githubusercontent.com/47973176/100064653-c5d02e80-2e6d-11eb-8e5e-d7170df3afa5.png)
![1606204452(1)](https://user-images.githubusercontent.com/47973176/100064696-d1235a00-2e6d-11eb-9ca2-9ee8324a32b5.png)

**Comment by JacksonJeans** [comment]
Hello @zhanfjunjun ,

I see that you use `PHP` and `Guzzle` like me.

The `contentType` in your header is wrong. In the createFeedDocument-operation it does not have to correspond to the `contentType` you specify in your `HTTPBody` for the following upload.

Also I would work with Guzzle with the request object. I definitely found it easier. I have created classes for the specifications which I then instantiate and pass them to the json_encode function filled with appropriate values. For the example I specified the array once, and once the small class.

Try it with this:
```
$params = array('contentType' => 'application/pdf');

$client = new \GuzzleHttp\Client(['exceptions' => false]);

$request = new \GuzzleHttp\Psr7\Request(
    'POST',
    'ENDPOINT/feeds/2020-09-04/documents',
    array(
        array('Content-Type' => 'application/json'),
        array('x-amz-access-token' => $resultData->access_token)
    ),
    json_encode($params)
);
```

My short class:
```

class CreateFeedDocumentSpecification
{

    /**
     * @var string $contentType [optional]
     * - Der Inhaltstyp des Feeds.
     */
    public $contentType;

    /**
     * @param string $contentType 
     * 
     */
    public function __construct($contentType = null)
    {
        $this->contentType = $contentType;
        return $this;
    }
}
```
Usage:

```
$client = new \GuzzleHttp\Client(['exceptions' => false]);

$CreateFeedDocumentSpecification = new CreateFeedDocumentSpecification();
$CreateFeedDocumentSpecification->contentType = 'application/pdf';

$request = new \GuzzleHttp\Psr7\Request(
    'POST',
    'ENDPOINT/feeds/2020-09-04/documents',
    array(
        array('Content-Type' => 'application/json'),
        array('x-amz-access-token' => $resultData->access_token)
    ),
    json_encode($CreateFeedDocumentSpecification)
);
```


Do you also build an authorization header? The Access-Token alone is not enough. The authorization header contains a canonical request that is hashed and derived by a StringToSign method. This is then hashed into a signature and is then included in the authorization header together with the credentials.

Otherwise I recommend you to read and understand [this task](https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html) of AWS.

- Julian

**Comment by zhanfjunjun** [comment]
@JacksonJeans  Hello:
Thank you very much for your reply. Today, I successfully requested results through a new method. The pdf in my request is the value of the test ContetType. I use this api to test product upload.
Anyway, thank you for your reply

**Comment by yao657355700** [comment]
> @JacksonJeans 您好：
> 非常感谢您的回复。今天，我通过一种新方法成功请求了结果。我请求中的pdf是测试ContetType的值。我使用这个 api 来测试产品上传。
> 不管怎样，谢谢你的回复

你是怎么解决的啊？
