### ISSUE TITLE
I can't authenticate

### ISSUE THREAD

**Issue by TxusBlack** [amzn/selling-partner-api-docs#14]
Hi everyone!

I'm trying to authenticate with the API. I've gone through all the steps to configure it but I can't authenticate with Postman (see screenshot).

![Captura de Pantalla 2020-09-18 a la(s) 4 02 42 p  m](https://user-images.githubusercontent.com/13071556/93644970-a2e65180-f9c8-11ea-87e0-85f6ad425e5d.png)

I also made a simple code using the [amazon-mws plugin](https://fullstacktechnology.com/nodejs/amazon-mws/) for JS. But I get the same response, access denied.

![Captura de Pantalla 2020-09-18 a la(s) 4 07 41 p  m](https://user-images.githubusercontent.com/13071556/93645347-6b2bd980-f9c9-11ea-89da-f61d0b8baf74.png)

In the authentication we are using the following:

![Captura de Pantalla 2020-09-18 a la(s) 4 19 04 p  m](https://user-images.githubusercontent.com/13071556/93645923-c1e5e300-f9ca-11ea-9300-8a010340ad5e.png)

I appreciate your collaboration.

**Edit:**

We also tested the [Amazon MWS Scratchpad](https://mws.amazonservices.com/scratchpad/index.html). And we get the same error with the primary and Seller credentials.

![Captura de Pantalla 2020-09-18 a la(s) 4 22 41 p  m](https://user-images.githubusercontent.com/13071556/93646154-47699300-f9cb-11ea-92af-a39b40087efa.png)

**Comment by charliecode** [comment]
> Hi everyone!
> 
> I'm trying to authenticate with the API. I've gone through all the steps to configure it but I can't authenticate with Postman (see screenshot).
> 
> ![Captura de Pantalla 2020-09-18 a la(s) 4 02 42 p  m](https://user-images.githubusercontent.com/13071556/93644970-a2e65180-f9c8-11ea-87e0-85f6ad425e5d.png)
> 
> I also made a simple code using the [amazon-mws plugin](https://fullstacktechnology.com/nodejs/amazon-mws/) for JS. But I get the same response, access denied.
> 
> ![Captura de Pantalla 2020-09-18 a la(s) 4 07 41 p  m](https://user-images.githubusercontent.com/13071556/93645347-6b2bd980-f9c9-11ea-89da-f61d0b8baf74.png)
> 
> In the authentication we are using the following:
> 
> ![Captura de Pantalla 2020-09-18 a la(s) 4 19 04 p  m](https://user-images.githubusercontent.com/13071556/93645923-c1e5e300-f9ca-11ea-9300-8a010340ad5e.png)
> 
> I appreciate your collaboration.
> 
> **Edit:**
> 
> We also tested the [Amazon MWS Scratchpad](https://mws.amazonservices.com/scratchpad/index.html). And we get the same error with the primary and Seller credentials.
> 
> ![Captura de Pantalla 2020-09-18 a la(s) 4 22 41 p  m](https://user-images.githubusercontent.com/13071556/93646154-47699300-f9cb-11ea-92af-a39b40087efa.png)

Hello @TxusBlack It's actually not possible to use the new SP-API as it hasn't launched publicly yet. It's more in document review at the moment. I would encourage you to read over the docs (link below) as things have changed quite a bit. There is a completely different, yet much more secure way of accessing it which requires setup as stated in the docs. You are not able to use your sellerId, mwsAuthToken etc with the new SP-API which is why you're getting access denied. Also MWS scratchpad is for the MWS API, not the SP-API. There is actually a new sandbox for testing, which is also not currently available until launch. When you read over the docs you'll notice instructions on how to become authenticated to use the new SP-API and sandbox. Please know that you're also not able to complete the instructions to do so as everything is not live yet. So, for the time being really familiarize yourself with the docs as well as the models which can be used to create your own API docs and client libraries for the new SP-API. I respond because I went through all the headaches you did as well and then finally learned why everything was not working. Read those docs! 

https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md

**Comment by mdmjg** [comment]
hi @charliecode do you know when the new API will be released fully?

**Comment by charliecode** [comment]
> hi @charliecode do you know when the new API will be released fully?

I do not. On the main page where the announcement is made, it says mid Sept, so now. Then I noticed the PM for the new SP-API mentioned later in September in a comment on one of the issues. I know they're in the final phases from what I've heard but it appears things are running a little behind schedule. Would be really nice if they could give us an update as their original projections seem to need updating.

**Comment by cafeasp** [comment]
your call is missing the token.  have you register your app per selling partner api dev guide? Once you have the app register by Amazon you can get a refresh token within Vendor Central/App page. With the refresh token you can request a token. Also, your post man call is missing - Under Authorization - Advanced Set AWS Region us-east-1(your own)
Set Service Name execute-api

**Comment by evdeg** [comment]
@TxusBlack The SP-API endpoints and registration is live now. Please try setting up your application and make calls to SP-API now. One thing to note, you must use the AWS credentials for your IAM User when calling SP-API which is different from your MWS credentials. If you still get access denied please [contact our Developer Support team](https://developer.amazonservices.com/support) so we can troubleshoot the issue further.
