### ISSUE TITLE
[BUG] Vendor Direct Fulfillment Purchase order 403 Acces to requested resource is denied.

### ISSUE THREAD

**Issue by IsmailTalhaKalkan** [amzn/selling-partner-api-docs#1433]
Hello, I want to make a request to sp API but get Access to resources is denied error. I have done everything right and still getting the error.

![Amzn1](https://user-images.githubusercontent.com/53086822/134500517-17802d2c-7a4a-447e-985c-f00bfb94262a.png)

Here's my code.

![Amzn2](https://user-images.githubusercontent.com/53086822/134500573-0c80f712-1305-4d6d-beef-d9f680d7f62e.png)
![AmznSigner](https://user-images.githubusercontent.com/53086822/134500652-707528f8-4461-4b19-817e-6ff768d302a5.png)
![Amzn3](https://user-images.githubusercontent.com/53086822/134500685-e2549f23-cbe4-4e2b-911a-58d3807fbd19.png)
![TokenAmzn](https://user-images.githubusercontent.com/53086822/134501172-ee2bb720-47d8-4184-a930-67469d5a7f33.png)
![AppAmzn](https://user-images.githubusercontent.com/53086822/134501261-777ddcec-9701-4cb1-8723-5c7879a0094d.png)
![AmznPolicy](https://user-images.githubusercontent.com/53086822/134501633-27162ad0-d585-4c83-8495-d353b986b18a.png)
![AmznPolicy2](https://user-images.githubusercontent.com/53086822/134501651-d30f5315-6637-4310-9dad-b8def865207b.png)

That's the error response.
![ResponseAmzn](https://user-images.githubusercontent.com/53086822/134501147-819d43b9-c76c-42b2-88dd-5849e5344e3e.png)

**Comment by IsmailTalhaKalkan** [comment]
Still getting same error,any ideas ?

**Comment by pucsdian** [comment]
check ur developer profile does it have directToConsumerShpping access

**Comment by IsmailTalhaKalkan** [comment]
> Still getting same error,any ideas ?

This is all i got.Btw do you mean Amazon Fullfilment ?

![AmznProfile](https://user-images.githubusercontent.com/53086822/135446191-d576891f-7b57-4d8b-996d-d916593fac80.png)

**Comment by pucsdian** [comment]
@IsmailTalhaKalkan 
 for calling Vendor DirectFulFillment routes u need to enable following Roles in ur app and developer profile
 
Direct-To-Consumer Delivery
Tax Invoicing
Tax Remittance

**Comment by pucsdian** [comment]
and Only Vendor Routes need amazon fulfillment role in both app and profile

**Comment by maethes** [comment]
Hi,
I am facing the exact same problem that I don't have access to download direct shipments from amazon vendor for our selling partners because I have not set those restricted roles in my developer profile.

I am only interested in downloading the dates, price and quantities of the orders. The tax information and personal data (PII) is not relevant for my use case.
Are there any routes or reports I could execute in order to get the requested information without using the RDTs (and without filling the tons of questions regarding PII)?

Thanks,
Matthias

**Comment by pucsdian** [comment]
@maethes 
if u want it for Vendor api's then i think we can't
they don't have any api for this

**Comment by maethes** [comment]
@pucsdian 
Thank you for your quick feedback. Yes. I need it for Vendor API.
Do you know if there is anything planned for future releases? Would it be possible to bring that up at the product development team?
Thanks, Matthias

**Comment by pucsdian** [comment]
@maethes 
i don't have any idea
but we can check here [https://github.com/amzn/selling-partner-api-docs/discussions](https://github.com/amzn/selling-partner-api-docs/discussions)

**Comment by rugved1991** [comment]
Hi @maethes @pucsdian,

In order to call vendor direct fulfillment api, you need to have Direct To Consumer Shipping role added to your application. For vendor retail API you need to have access to Amazon Fulfillment role.
If you don’t have access to it, you will need to request access to this role by editing your developer profile.
Once the role is added, vendor will have to reauthorize the app and then you can try the api request again.

Thanks,
Rugved 
Solutions Architect, SP API

**Comment by maethes** [comment]
Hi @rugved1991 ,
Thank you for your input. The role "Direct To Consumer Shipping" comes with a very long questionaire regards our treatment with PII. Therefore it would be very effortful to fill out all those questions.

As I only need access to the non-PII part of the data (e.g. quantity and purchase date) it would be great to add an interface which provides the data without the PII-relevant information. This would help smaller companies and startups who start using the SP API as they get access to an important part of the data without the need of taking responsibility of PII.

Is this something you can take up and see whether it is possible to bring up a solution for this scenario?

Thanks,
Matthias
