### ISSUE TITLE
Failed to get Orders error "Access to requested resource is denied"

### ISSUE THREAD

**Issue by daomeideshu** [amzn/selling-partner-api-docs#146]
For some merchant (around 5%  of all merchants), we can use SP API to get the sales via endpoint `/sales/v1/orderMetrics`, but when we try to get orders via `endpoint /orders/v0/orders`, it's always failed:
` {
                        "code": "Unauthorized",
                        "message": "Access to requested resource is denied.",
                        "details": ""
                }`

**Comment by BeeBee234** [comment]
Hello,

For C# users the following sandbox call works, using the example code in https://github.com/amzn/selling-partner-api-models/issues/31 :

            var resource = $"/orders/v0/orders";
            IRestRequest restRequest = new RestRequest(resource, Method.GET);
            restRequest.AddParameter("MarketplaceIds", "ATVPDKIKX0DER", ParameterType.QueryString);
            restRequest.AddParameter("CreatedAfter", "TEST_CASE_200", ParameterType.QueryString);

FYI, I encountered many 'Access denied/Unauthorized/Forbidden' responses before finally making a successful sandbox call to the following (which also works):

        var resource = $"/vendor/orders/v1/purchaseOrders";
        IRestRequest restRequest = new RestRequest(resource, Method.GET);
        restRequest.AddParameter("createdAfter", "2019-08-20", ParameterType.QueryString);
        restRequest.AddParameter("createdBefore", "2019-09-21", ParameterType.QueryString);

This confirmed to me that my credentials were set up properly and that 'Access denied' is bogus.  So even if you get 'Access denied' you might be very close to the correct syntax.

Good luck and have a wonderful day,

Brian

**Comment by MrYing** [comment]
I’ve also encountered this problem. I’ve checked my IAM account many times, and it’s consistent with the description in the document, but it still returns the authentication failure. It’s been a week since I encountered this problem, and I have also checked the similar problems of Issuses. But I still haven't found the answer to the related question. If your case is answered, I hope to inform you of the solution.
`BEGIN REQUEST++++++++++++++++++++++++++++++++++++
Request URL = https://sellingpartnerapi-eu.amazon.com/fba/inbound/v0/shipments/shipmentId1/preorder/confirm?marketplaceid=A1F83G8C2ARO7P&needbydate=2012-10-17

RESPONSE++++++++++++++++++++++++++++++++++++
Response code: 403

{
"errors": [
{
"message": "Access to requested resource is denied.",
"code": "Unauthorized",
"details": ""
}
]
}`

**Comment by melkelk** [comment]
Is it just this endpoint that is failing or all endpoints for that particular merchant? Can this (also) be related to #196?

**Comment by daomeideshu** [comment]
Just this endpoint
