### ISSUE TITLE
InvalidInput: 'Developer ID 8XXXXXXXXXX2 is not associated with the application id.

### ISSUE THREAD

**Issue by SShalini** [amzn/selling-partner-api-docs#1469]
I'm trying to migrate my users from MWS to SP-API using GET /authorization/v1/authorizationCode

I'm getting the following error:

{
  errors: [
    {
      code: 'InvalidInput',
      message: 'Developer ID 8XXXXXXXXXX2 is not associated with the application id.',
      details: ''
    }
  ]
}

I opened a case ( case id is 8998664311) but I'm posting this issue here in the hope I can solve it on my side.

Thanks for any help.

**Comment by jamesp26** [comment]
Is you application still in draft mode? I believe you have to go through the submission process before you can migrate users.

**Comment by SShalini** [comment]
Hi jamesp26, Thanks for the response,

Current status of my app is:-

Published
Current edit is pending approval

**Comment by jamesp26** [comment]
If you have published to the app store you need to wait. It took about 3 weeks for ours to be fully approved / published. Only once you are on the app store can you migrate MWS accounts.

**Comment by tobidon** [comment]
Hello to all,

we have the same problem, this does not seem to be a new one:

"message": "Developer ID 350xxxxxxxxx is not associated with the application id."

Our App is fully published. 

 This problem was covered already for example in [Issue #147](https://github.com/amzn/selling-partner-api-docs/issues/147). There were a number of cases where some configuration had to be done on the Amazon side. It seemed that the use of the Authorization API had to be enabled for the app, as this did not happen automatically on publishing process.

At that time @parvathm  could help - @parvathm can you please have a look at this? That would be great! Our case number is 7567700022.

Thank you very much and kind regards

**Comment by tobidon** [comment]
Update: after publishing our app again, the migration operation now works :+1:

**Comment by stefnats** [comment]
I can confirm that too!
