### ISSUE TITLE
InvalidSignature issue for POST SP-API requests (create Report API)

### ISSUE THREAD

**Issue by IamSantosh** [amzn/selling-partner-api-docs#1481]
Hi,

I've successfully obtained the LWA token for the user and also integrated the refresh token part. I've also been able to hit 'GET' API of Selling Partner and received success response. Below I've mentioned the working example of receiving all reports created from users.

**GET API Example :**
access_key_id = 'AKIAXXX'
secret_access_key = 'EY7XXXX'
token = 'Atza|IwXXXXXXX'
tsz = Time.now.utc.strftime("%Y%m%dT%H%M%SZ")
host = 'sellingpartnerapi-eu.amazon.com'
uri = 'https://sellingpartnerapi-eu.amazon.com/reports/2021-06-30/reports?marketplaceIds=A21TJRUUN4KGV&reportTypes=GET_MERCHANT_LISTINGS_DATA&pageSize=100'
headers = {
  'host' => host,
  'user-agent' => 'Outfy',
  'x-amz-access-token' => token,
  'x-amz-date' => tsz
}

signer = Aws::Sigv4::Signer.new(
  service: 'execute-api',
  region: 'eu-west-1',
  access_key_id: access_key_id,
  secret_access_key: secret_access_key
)
signature = signer.sign_request(
  http_method: 'GET',
  url: uri,
  headers: headers
)

signature.headers['x-amz-date']
signature.headers['x-amz-content-sha256']
signature.headers['authorization']

using the above 3 values, I hit the API on POSTMAN and received the success response. Below I've also attached the screenshot.
![sp_api_get_example](https://user-images.githubusercontent.com/19526862/136333061-b4189c1e-1de7-48c6-9f2b-58f8624ec6a2.png)

But the problem arise for POST request. Using same flow, when I'm trying to hit POST request fro creating a Report via API, I got invalid signature response.

**POST API Example:**
access_key_id = 'AKIAXXX'
secret_access_key = 'EY7XXXX'
token = 'Atza|IwXXXXXXX'
tsz = Time.now.utc.strftime("%Y%m%dT%H%M%SZ")
host = 'sellingpartnerapi-eu.amazon.com'
uri = 'https://sellingpartnerapi-eu.amazon.com/reports/2021-06-30/reports'
headers = {
  'host' => host,
  'user-agent' => 'Outfy',
  'x-amz-access-token' => token,
  'x-amz-date' => tsz
}

signer = Aws::Sigv4::Signer.new(
  service: 'execute-api',
  region: 'eu-west-1',
  access_key_id: access_key_id,
  secret_access_key: secret_access_key
)

body_hash = {
  'marketplaceIds' => [
        "A21TJRUUN4KGV"
    ],
  'reportType' => 'GET_MERCHANT_LISTINGS_DATA'
}

signature = signer.sign_request(
  http_method: 'POST',
  url: uri,
  headers: headers,
  body: body_hash.to_s
)

signature.headers['x-amz-date']
signature.headers['x-amz-content-sha256']
signature.headers['authorization']
using the above 3 values, I hit the API on POSTMAN and received the inalid signature response. Below I've also attached the screenshot.
![sp_api_post_example_1](https://user-images.githubusercontent.com/19526862/136333821-95b7fea6-9b38-4753-8f36-c9cf8191e40f.png)
![sp_api_post_example_2](https://user-images.githubusercontent.com/19526862/136333829-f352a9b5-e3c0-4b5f-8b5b-5579ab7105dc.png)

Please help me out here. I researched a lot regarding this on Stackoverflow also but didn't find any solution.

**Comment by ebarro** [comment]
I encountered the same issue. The same code that works for a GET request was always returning an invalid signature response from the API. I finally found a solution last night by adding Content-Type = application/json to my code it finally succeeded in creating the report via Amazon's SP-API.

**Comment by yourguide** [comment]
I am having the same issue... also using postman and my header does have The Content-Type= application/json in it.
Anyone help point me in the right direction?   GETs are working but so far no POSTs.

**Comment by Geek2017** [comment]
this is still an going issue I reported this to SP-API team and them themselves don't know how to address this there suggestion was to used the C# and java SDK instead which is unacceptable

**Comment by Geek2017** [comment]
I solve this by turning the docs upside down it seems like if where not to used AWS SDK for what any reason we need to sign every request we made to SP-API. since botoa is not compatible with SP-API I have created my own signer in python hope this help thou I appreciate you inputs @yourguide 

import hmac
import hashlib
import urllib.parse
import requests
import mysql.connector
from datetime import datetime, timedelta
import json

# Get the current date and time, 1 hour ago
now = datetime.utcnow() - timedelta(hours=3)

# Convert it to a string in the required format
formatted_timestamp =  now.strftime('%Y-%m-%dT%H:%M:%SZ')

with open('./../config.json') as config_file:
    config_data = json.load(config_file)
access_token = config_data['access_token']

# Get the AWS access key ID and secret access key from the config file
aws_access_key_id = "your aws_access_key_id "
aws_secret_access_key = "your aws_secret_access_key "

# Other parameters for the request
method = 'GET'
service = 'execute-api'
host = 'sellingpartnerapi-na.amazon.com'
region = 'us-east-1'
endpoint = 'https://' + host

# Adjusted parameters
canonical_uri = '/orders/v0/orders'
request_parameters = urllib.parse.urlencode(sorted({
    'CreatedAfter': formatted_timestamp,
    'MarketplaceIds': 'ATVPDKIKX0DER',
    'pageSize': 10000
}.items()))

# Create a date for headers and the credential string
t = datetime.utcnow()
amz_date = t.strftime('%Y%m%dT%H%M%SZ')
date_stamp = t.strftime('%Y%m%d')

# TASK 1: CREATE A CANONICAL REQUEST
canonical_headers = 'host:' + host + '\n' + 'x-amz-date:' + amz_date + '\n'
signed_headers = 'host;x-amz-date'
payload_hash = hashlib.sha256(('').encode('utf-8')).hexdigest()
canonical_request = method + '\n' + canonical_uri + '\n' + request_parameters + \
    '\n' + canonical_headers + '\n' + signed_headers + '\n' + payload_hash

# TASK 2: CREATE THE STRING TO SIGN
algorithm = 'AWS4-HMAC-SHA256'
credential_scope = date_stamp + '/' + region + \
    '/' + service + '/' + 'aws4_request'
string_to_sign = algorithm + '\n' + amz_date + '\n' + credential_scope + \
    '\n' + hashlib.sha256(canonical_request.encode('utf-8')).hexdigest()

# Key derivation functions
def sign(key, msg):
    return hmac.new(key, msg.encode('utf-8'), hashlib.sha256).digest()

def get_signature_key(key, date_stamp, region_name, service_name):
    kDate = sign(('AWS4' + key).encode('utf-8'), date_stamp)
    kRegion = sign(kDate, region_name)
    kService = sign(kRegion, service_name)
    kSigning = sign(kService, 'aws4_request')
    return kSigning

# TASK 3: CALCULATE THE SIGNATURE
signing_key = get_signature_key(
    aws_secret_access_key, date_stamp, region, service)
signature = hmac.new(signing_key, (string_to_sign).encode(
    'utf-8'), hashlib.sha256).hexdigest()

# TASK 4: ADD SIGNING INFORMATION TO THE REQUEST
authorization_header = algorithm + ' ' + 'Credential=' + aws_access_key_id + '/' + \
    credential_scope + ', ' + 'SignedHeaders=' + \
    signed_headers + ', ' + 'Signature=' + signature
headers = {'x-amz-date': amz_date, 'Authorization': authorization_header}

url = "https://sellingpartnerapi-na.amazon.com/orders/v0/orders?CreatedAfter=" + \
    formatted_timestamp+"&MarketplaceIds=ATVPDKIKX0DER&pageSize=10000"

payload = {}
headers = {
    'Accept': 'application/json',
    'x-amz-access-token': access_token,
    'X-Amz-Date': amz_date,
    'Authorization': authorization_header
}

response = requests.request("GET", url, headers=headers, data=payload)

# Process the response
response_json = response.json()

print(response_json)


#################################################################

for config.json content:
{"access_token": "yourtoken", "token_type": "bearer", "expires_in": 3600}
