### ISSUE TITLE
Registering as a public developer - no permissions

### ISSUE THREAD

**Issue by adbrew** [amzn/selling-partner-api-docs#1548]
Hi,

We want to register as a public developer, is it mandatory to be registered as a seller for that? If yes, why is that? Ideally public developer accounts should simply be linked to an organization, and they may or may not be a seller. Even the documentation simply mentions login to seller central with the credentials with which we want to register the developer profile. 

When we login to our seller central account, we are forced to choose a Seller Account and only then can we see the Partner Network tab. Even if I select one of the accounts, and go to Partner Network -> Develop Apps it says we do not have permissions to view the page.

Can you please help us navigate this?

**Comment by adbrew** [comment]
In that case what kind of account do I need to create? If I create an account `.com` marketplace, will I get access to APIs in all regions?

Even when creating an account in the `.com` marketplace, I see that there are various options like business/individual -- is there any detail on what kind of a seller account is requireD?

**Comment by abuzuhri** [comment]
> In that case what kind of account do I need to create? If I create an account `.com` marketplace, will I get access to APIs in all regions?

you need to register in all regions (3 regions)

**Comment by rugved1991** [comment]
Hi @adbrew,

You need to sign up for a Professional Seller Central account in order to integrate with Amazon Selling Partner API. You only need one seller central account in a region where most of your sellers are located. The application you create on the seller central account will be global and can be used to onboard sellers across the globe. You dont need to create multiple seller central accounts across regions.

You would need to log in to your seller central account with primary credentials. Only then you will be able to access all pages of the seller central account. 

Best,
Rugved
Solutions Architect, SP API

**Comment by mindstretch23** [comment]
@rugved1991 @parvathm Has this requirement changed? 

In the past, the "Develop Apps" page was only accessible while a Professional Selling account was active.

However, it seems this has changed recently. I can confirm that as of right now I do not have an active Professional Selling account, but unlike in the past, I can still access the "Develop Apps" page. On that page I can still view my Developer profile, all my apps, view all my apps and view/manage everything that's needed to develop/manage my apps.

Does this mean that the $40/month Professional Selling plan requirement for developers was removed? 

This seems to make more sense as nearly all developers are simply using seller central to develop apps, not to sell items on Amazon.

Clarity on this would be greatly appreciated so we all know for sure whether or not we need to maintain the Professional Selling plan.
