### ISSUE TITLE
New delegation use case added to Tokens API - Who and how

### ISSUE THREAD

**Issue by martin-hepworth** [amzn/selling-partner-api-docs#1592]
I have noticed that Amazon are now allowing delegated access to PII via a delegated app that has access to PII.

How can I find a list of these apps and how I would use them?

I desperately need the PII as the customers I am working for do direct to consumer deliveries and I can not get access signed off via the SP-API so this might give me a route to go down but there is no list or easy way to search for companies that would provide this information.

**Comment by tspicer** [comment]
For reference, https://github.com/amzn/selling-partner-api-docs/discussions/1393

Like most things RDT and PII, it is not entirely clear how this process is suppose to work. For example, if delegation occurs do both apps need to be approved for PII, meaning you can only delegate to an app that has gone through the approval process? I understand the intent, but the entire PII/RDT process is generally broken

**Comment by martin-hepworth** [comment]
Thanks, I'd seen the annoucement but it didn't provide me with any additional useful information.

I would expect both apps not to need PII approval or it would be pointless. If I got PII approval I wouldn't delegate the RDT request.

It seems Amazon have switched off PII from MWS without allowing people to access it via the SP-API route so they effectively stopping business like mine from being able to help people integrate their Amazon Seller Central system with their ERP and Courier systems.

**Comment by parvathm** [comment]
Hi @martin-hepworth 

To find apps to use delegation api please refer to App store that works for your use case.
Both apps doesn't need PII access.  Delegatee who has PII access can access the data. 

Thanks,
Parvathm
SP API Developer Support.

**Comment by tspicer** [comment]
@parvathm 
Can you explain the use case further? For example, I'm developer A. I have an existing app.  My public app is NOT approved for PII. My customer, developer B, created their own app. My understanding is they must undertake the review process for their app and be approved for PII. Correct? If developer B is approved, they can delegate PII access they were granted to developer A?

**Comment by martin-hepworth** [comment]
@parvathm 

Is there an easy way to search for these. I just need an app that has access to PII that will not cost me a fortune to use.

Thanks

**Comment by parvathm** [comment]
@tspicer ,

Yes, once Developer B has PII access. Developer A can delegate to Developer B . If you have any further questions. please open a support case.

Thanks,
SP API Developer Support.

**Comment by tspicer** [comment]
@parvathm , don't you mean that Developer B, who has been approved, can delegate PII access to Developer A app?

 I was told that Public apps are not allowed PII access. This is directly from the Amazon team  _**" accessing Personally Identifiable Information (PII) as a Public developer is not supported by our policies."**_
 
 If this is true, the only way a public app can get PII is by a customer delegating access to us.
 
I hope you can appreciate how frustrating this process is because our application is now almost 6 months long.  We have been a public app for almost 4 years. Why even allow a public app in the marketplace to undergo a review if the policy is what was communicated to us????
 
Delegation would only make sense if it is a form of access control for public apps like ours. A customer can go through an approval process on their own, and if they are approved, this allows them to "delegate" access to our app. This limits the scope of PII access so we can process DTC and tax info for them.

**Comment by martin-hepworth** [comment]
@parvathm I have opened multiple support cases around these issues and they keep getting closed with generic response like use SP-API. Here's a link to the form you completed.

Amazon are not offering up the details needed for the developers to do this work for their Seller Central Partners. It is almost like Amazon is trying to make Seller Central Integration impossible. A cynic would suggest this is an attempt to force those sellers onto vendor central where Amazon makes a better margin.

**Comment by tspicer** [comment]
@martin-hepworth I agree, the details on delegation and PII, in general, are severely lacking. I have a number of customers that will no longer be able to undertake FBM//MFN. While I understand the desire to protect PII/sensitive data, the process is broken. As it stands, I have customers that will need and plan to switch platforms (Shopify...) for any direct sales. 

Feel free to message me directly if you want to discuss this further.
