### ISSUE TITLE
Special rate limits for `GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL`?

### ISSUE THREAD

**Issue by moltar** [amzn/selling-partner-api-docs#1624]
We are experiencing strange behaviour with the `GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL` report.

It seems to be rate-limited on its own.

All other reports go through fine, but that one is continuously getting 429s when calling create report method, no matter how long the wait is in between.

Can you please shed some light on if and/or how this report should be handled differently?

---

The response is always:

```json
{
    "errors": [
        {
            "code": "QuotaExceeded",
            "message": "You exceeded your quota for the requested resource.",
            "details": ""
        }
    ]
}
```

---

Related: #843

Case ID: 9161753651

---

@ShivikaK @parvathm @jenilew any ideas?

**Comment by ShivikaK** [comment]
Hello @moltar 

Thank you for raising this issue.

The case is being investigated by the support team and will be updated accordingly for additional information or next steps.

Please continue monitoring the support case opened with us. As the case is currently being looked into, I will resolve this issue in favor of the case reported to us.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by arshul** [comment]
I am also experiencing similar behavior on this report type only

**Comment by jimmy-ross-xapix** [comment]
I am too.

**Comment by jgamboa-forumbrands** [comment]
2022 i have the same error.

**Comment by ToYonos** [comment]
Same issue here, using 2 kinds of report :

- GET_AMAZON_FULFILLED_SHIPMENTS_DATA_INVOICING (many Quota issues)
- GET_FLAT_FILE_ORDER_REPORT_DATA_INVOICING (Quota issues but less in proportion than the above)

I trusted the create report rate which is 0.0167 request per second (one per minute) but still, many errors

**Comment by maltunok** [comment]
+1

**Comment by maltunok** [comment]
+1

**Comment by maltunok** [comment]
+1

**Comment by NetRushJacob** [comment]
> 

@ShivikaK you closed this issue, stating that a support case should be monitored that was opened. If GitHub is going to be a place to identify and discuss bugs for us developers, moving conversations to private support cases shouldn't be the status quo. Closing this issue implies to the rest of us that the issue is fixed. 

@moltar were you able to get any progress on these requests through the support case? Any solution you could provide for the community?

We recently started requesting this same report and are also experiencing this odd throttling for this GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL report type. We can make other CreateReport requests at the stated limit, but this one fails even attempting to request one report every 20 minutes.

**Comment by ToYonos** [comment]
I opened a support case, a detailed one with verbose logs. It's been "Pending Amazon Action" for weeks now.
But I managed to deal with the issue regarding `GET_AMAZON_FULFILLED_SHIPMENTS_DATA_INVOICING`

I kind of reverse engineered the quota, guessing it after many tries. Asking this kind of report is possible once every 45 minutes. Maybe a little less but 30 minutes was failing. Hopefully for me, it's acceptable and since my app respects this quota, no more `QuotaExceeded`

Moreover, I still except an answer from Amazon's support as their last message was _I have reached out to the concerned team, and will get back to you once I have more information_

**Comment by NetRushJacob** [comment]
@ToYonos thank you for the information!  We've also identified something similar through trial and error for the GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL...we landed on an hour to completely eliminate errors.

Please let us all know what, if anything, support gets back to you on this!

**Comment by kelerensheng** [comment]
+1

**Comment by bolner** [comment]
For me this quota is not getting resetted even after waiting 4 hours.  There are too many problems with this API.

**Comment by superhorse622** [comment]
Hello

When I call the Amazon sp api, I get the following error:

[{'code': 'QuotaExceeded', 'message': 'You exceeded your quota for the requested resource.', 'details': ''}]

How can I increase my quota?

**Comment by bolner** [comment]
> Hello
> 
> When I call the Amazon sp api, I get the following error:
> 
> [{'code': 'QuotaExceeded', 'message': 'You exceeded your quota for the requested resource.', 'details': ''}]
> 
> How can I increase my quota?

The important thing to know is that the quota is not per app authorization, but per sales account. So if multiple apps are authorized for the same account, then it's possible that one of them is eating up the whole quota.

The only solution I see is to ask the owner of the account to uninstall all apps which do that, or to query the already generated reports and download them.
