### ISSUE TITLE
GET /fba/inbound/v0/shipments, Operation: getShipments, NextToken not work

### ISSUE THREAD

**Issue by FexusZ** [amzn/selling-partner-api-docs#164]
Hello,
When I call the getShipments method, I get the first list with the 50 shipments, but when I try to get the next 50 shipments via the NextToken parameter, I get exactly the same list.

Is the NextToken parameter implemented?

first request : 
https://sellingpartnerapi-eu.amazon.com/fba/inbound/v0/shipments
?LastUpdatedAfter=2020-11-01T10:21:20+00:00
&LastUpdatedBefore=2020-12-01T10:21:20+00:00
&MarketplaceId=A13V1IB3VIYZZH
&QueryType=DATE_RANGE
&ShipmentStatusList=WORKING,SHIPPED,RECEIVING,CANCELLED,DELETED,CLOSED,ERROR,IN_TRANSIT,DELIVERED,CHECKED_IN

second request : 
https://sellingpartnerapi-eu.amazon.com/fba/inbound/v0/shipments
?LastUpdatedAfter=2020-11-01T10:23:07+00:00
&LastUpdatedBefore=2020-12-01T10:23:07+00:00
&MarketplaceId=A13V1IB3VIYZZH
&NextToken= {TOKEN}
&QueryType=NEXT_TOKEN
&ShipmentStatusList=WORKING,SHIPPED,RECEIVING,CANCELLED,DELETED,CLOSED,ERROR,IN_TRANSIT,DELIVERED,CHECKED_IN

**Comment by JacksonJeans** [comment]
Hello @FexusZ  ,

Please try the following second request

```
https://sellingpartnerapi-eu.amazon.com/fba/inbound/v0/shipments
?NextToken={TOKEN}
&MarketplaceId=A13V1IB3VIYZZH
&QueryType=NEXT_TOKEN
```

I had a similar problem with the OrdersAPI, because I had included the optional parameters for the first request in the second one.
In the documentation the `QueryType`:

"Indicates whether shipments are returned using shipment information (by providing the `ShipmentStatusList` or `ShipmentIdList` parameters), using a date range (by providing the `LastUpdatedAfter` and `LastUpdatedBefore` parameters), or by using `NextToken` to continue returning items specified in a previous request."

`MarketplaceId` is present here because this parameter is required.
Therefore I recommend to use only `QueryType`, `MarketplaceId` and `NextToken` from the second request on.


Please let me know if it worked.

Good luck!

**Comment by FexusZ** [comment]
I tried, but the problem is still there, thank you for your answer

**Comment by JacksonJeans** [comment]
Oh. Very silly, I'm sorry. 

I would try wildly,... until only the last parameter NextToken is used for the request. With GET operations, not so much can go wrong as getting data, or even a "Forbidden".

**Comment by FexusZ** [comment]
Finally, it's my fault, I misplaced my code, everything works correctly .. sorry

**Comment by JacksonJeans** [comment]
Do you want to let us know if my suggestion with the second requirement is correct? I haven't tried the API yet and it might be helpful to know if in the second request `marketplaceIds`, `QueryType` and `NextToken` is only required, or if all additional parameters are passed back unchanged.

Very good that your implementation now works! Good luck in the future!

**Comment by FexusZ** [comment]
only marketplaceIds, QueryType and NextToken work
