### ISSUE TITLE
Unable to make calls to European regions "Access to requested resource is denied"

### ISSUE THREAD

**Issue by SM-StoreDev** [amzn/selling-partner-api-docs#173]
We have registered as a developer on our Amazon.com (North American) seller central account and all our API calls are working perfectly fine for US and Canada. When we try to call to UK or France or Germany we are unsuccessful. When we access our Developer Central console in the UK we are not able to create any client apps, but on US we are. We have contacted developer support and have been told that we only need to be registered in one region to make calls to all regions and that our account is approved for making global calls. Yet we are still seeing this error. Please check our developer support Cased ID: 7630460171.

Here is our workflow and response:

STS service is reponging for EU Regions ( eu-west-2 or eu-west-3 / UK or FR )
After getting SessionToken from STS we are going to SP API
When testing SP API using US region ( us-east-1 ) everything is ok
When testing SP API using EU region ( eu-west-1 ) response is:

{
"errors": [
{
"message": "Access to requested resource is denied.",
"code": "Unauthorized",
"details": ""
}
]
}

**Comment by smartmartstore** [comment]
We just created a new Case with Developer Support for this situation. Please check CaseID: 7684714661

**Comment by kerbalwzy** [comment]
#168

**Comment by jlevers** [comment]
I'm running into this issue as well. Would love to hear any advice that the Amazon team can provide

**Comment by cohlar** [comment]
Same here!

**Comment by MrYing** [comment]
I’ve also encountered this problem. I’ve checked my IAM account many times, and it’s consistent with the description in the document, but it still returns the authentication failure. It’s been a week since I encountered this problem, and I have also checked the similar problems of Issuses. But I still haven't found the answer to the related question. If your case is answered, I hope to inform you of the solution.
`BEGIN REQUEST++++++++++++++++++++++++++++++++++++
Request URL = https://sellingpartnerapi-eu.amazon.com/fba/inbound/v0/shipments/shipmentId1/preorder/confirm?marketplaceid=A1F83G8C2ARO7P&needbydate=2012-10-17

RESPONSE++++++++++++++++++++++++++++++++++++
Response code: 403

{
  "errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "Unauthorized",
     "details": ""
    }
  ]
}`

**Comment by melkelk** [comment]
Our development is halted with the same impediment. In order to help investigating: I believe this issue is related (or at least very similar) to #196.
