### ISSUE TITLE
Is there who anyone have PII access authorization in SP-Api?

### ISSUE THREAD

**Issue by hkncnr07** [amzn/selling-partner-api-docs#1730]
Hello,
As you know, you need to get PII (Direct-to-Consumer Shipping) access approval in order to get the shipping address of the order with SP-Api.
We have applied many times to obtain this authorization for months, we have submitted all the information and documents requested from us and fulfilled the conditions, but we have not yet get approval.
Has anyone applied and been approved for this access authorization in the last months?
I need help on this. I don't know exactly what I am missing and there is no unit on Amazon about SP-Api that you can contact and get support from.
Under this heading, we can help each other, those who receive this approval and those who do not.
Thanks

**Comment by tspicer** [comment]
Hi @hkncnr07  had similar issues with PII. What is frustrating is that Amazon seems to not care that they are allowing third-party screen scraping applications  to bypass all security measures to download the reports as a user proxy. 

They even reference this in their docs:
_"**Will enabling Two-Step Verification affect my third-party connections? (For example, screen scrapers, integrators, or data aggregators.):** Two-step verification might affect some connections from third parties using screen-scraping technology to sign in to your account via a username and password. We encourage you to explore whether Marketplace Web Service (MWS) or Reports in Seller Central can provide the functionality for which you use a third party."_

So, it is OK for companies to bypass the use of the API, backdoor the data,  and have these companies promote the fact no API access is needed to get this data. Amazon then places incredible barriers  for anyone going through the front door (API) in a safe, consistent, and expected manner. 

It is insane that Amazon allows applications to proxy as a user, screen scrape reports, yet puts API users through architectural SOC reviews. It seems, the best option is to simply screen scrape the data since Amazon seems to prefer that path.  Just crazy.

**Comment by hkncnr07** [comment]
Hi @tspicer,

Thanks a lot for your answer.
How long have you been trying to get PII access authorization?
Haven't you been successful yet for PII access approval?

Thanks

**Comment by optikalefx** [comment]
We have successfully applied to get PII access. The new security protocols are for large companies with IT departments, security departments, finance departments, legal departments, policy documentation and much more. If you are a large company with these types of resources, you can get access. But if you are a small company (200 or less people) it's unlikely you'll be able to comply with their security restrictions.
