### ISSUE TITLE
[BUG] Can't retrieve data from Listing API

### ISSUE THREAD

**Issue by robinchen123** [amzn/selling-partner-api-docs#1735]
We retrieve many NOT FOUND results from listing API with vendor code and model No. while these ASINs are selling right now.

**Comment by vonjourn8519** [comment]
For Duracell, most model numbers are not found. 

Below is an example, DURMN2400B4Z is the model number , its asin is B00A4BBCIE

API cannot find results:
/listings/2021-08-01/items/BF5VF/DURMN2400B4Z

![image](https://user-images.githubusercontent.com/60506925/144157299-75daa913-60d6-4008-b678-8ee882e61653.png)


However ASIN has result:
https://www.amazon.com/dp/B00A4BBCIE

But we also tried other clients, every ASIN/model number can be found in another client JLHome. So n ot sure why most Duracell products has no result from this API?

**Comment by rugved1991** [comment]
Hi @vonjourn8519 @robinchen123,

You would need to use the exact SKU value that was used to create the listing. The SKU contribution value should match for that specific Vendor Code.  If you are still not able to pull the listing, please open up a support case with the request and response details so that our Support Team can investigate further.

@vonjourn8519 
For the product you mentioned here, the SKU value is the same as the ASIN value. Try replacing the SKU value with ASIN value and test again. 

Best,
Rugved
Solutions Architect, SP API

**Comment by robinchen123** [comment]
Thanks, Rugved1991. Currently I need to use asin and model No. to identify which I should use to get listing content. It is confusing when i should use asin or model No.

**Comment by chapmanjw** [comment]
As @rugved1991 mentioned, the `getListingsItem` operation only retrieves an item by its exact SKU for the seller or vendor. We will be launching a search operation later in the year that will allow you to search for listings by ASIN, keywords, etc. Stay tuned for updates on that.

**Comment by cypris75** [comment]
@chapmanjw What is the best way today to find out what is the correct SKU to use for `getListingsItem`? We work with a vendor and sometimes it is the SKU, sometimes the EAN and sometimes the ASIN which is the value we need to provide in the request. I don't see a clear pattern yet.

**Comment by robinchen123** [comment]
> As @rugved1991 mentioned, the `getListingsItem` operation only retrieves an item by its exact SKU for the seller or vendor. We will be launching a search operation later in the year that will allow you to search for listings by ASIN, keywords, etc. Stay tuned for updates on that.

Will this feature allow us to know which number we should use to call the listing api?

**Comment by chapmanjw** [comment]
@cypris75 and @robinchen123 We will be launching a `searchListingsItems` in the future that behaves similar to the Manage Your Inventory page on Seller Central and My Catalog page on Vendor Central. This would enable to you search for the listings by ASIN, identifier, etc., so that you know which SKUs to use when editing. I do not have an exact timeframe for this yet other than it will be coming soon. 

Stay tuned to the Selling Partner API launch announcements for that: https://developer-docs.amazon.com/sp-api/page/release-notes. Additionally, if possible, we may provide a preview of what the API will look like as we did for the recently release Catalog Items v2022-04-01: https://github.com/amzn/selling-partner-api-docs/discussions/2017.
