### ISSUE TITLE
[FEATURE] ItemSalesRank add ProductCategoryId (categoryCode) filed just like MWS api

### ISSUE THREAD

**Issue by ihoment-meihui** [amzn/selling-partner-api-docs#1779]
**Describe the improvement**
operation getCatalogItem 
hope ItemSalesRank can add ProductCategoryId (categoryCode) filed just like MWS api.

**URL of the content on GitHub**
https://github.com/amzn/selling-partner-api-docs/blob/main/references/catalog-items-api/catalogItems_2020-12-01.md#itemsalesranks

**Screenshots**
![image](https://user-images.githubusercontent.com/35246538/145164711-3e064d5f-d5ab-4f3d-aa84-2fb6a46cbb71.png)
![image](https://user-images.githubusercontent.com/35246538/145164944-18a0ad5b-4891-4647-9c21-ee2094dc930f.png)

**Additional context**
In order to be compatible with the data previously obtained from MWS api.
In addition, we use ProductCategoryId to judge if the product category is a sub category.

**Comment by bchecketts** [comment]
Agreed. The text `title` is convenient, but I'd prefer to have the `BrowseNodeId` (which I think is a synonym with `ProductCategoryId`) in the response.  An integer ID makes it more useful, and easier to reference with the deeper Browse Tree.

**Comment by chapmanjw** [comment]
@ihoment-meihui and @bchecketts Thank you for the feedback. We are working on our next iteration of the Catalog Items API and will determine the feasibility of including this. 

At first glance, looking at this ASIN as an example: `B09KKJMR4L`, the MWS/v0 APIs return these product category rankings:

```
         <SalesRankings>
            <SalesRank>
               <ProductCategoryId>toy_display_on_website</ProductCategoryId>
               <Rank>6044</Rank>
            </SalesRank>
            <SalesRank>
               <ProductCategoryId>19431299011</ProductCategoryId>
               <Rank>115</Rank>
            </SalesRank>
         </SalesRankings>
```

And the v2020-12-01 APIs return:

```
  "ranks": [
    {
      "marketplaceId": "ATVPDKIKX0DER",
      "ranks": [
        {
          "title": "Toys & Games",
          "link": "http://www.amazon.com/gp/bestsellers/toys-and-games",
          "rank": 6044
        },
        {
          "title": "Dedicated Deck Card Games",
          "link": "http://www.amazon.com/gp/bestsellers/toys-and-games/19431299011",
          "rank": 115
        }
      ]
    }
  ]
```

The same data is ultimately feeding both of these APIs. However, `toy_display_on_website` isn't useful as an identifier here. We would need to identify a way to provide the browse node that represents that instead of the text-based identifier. If we are able to do that, we may be able to include this in our next revision. I will do some more research and get back to this thread.

**Comment by chapmanjw** [comment]
@ihoment-meihui We have released the v2022-04-01 version of the Catalog Items API. For sales ranks, they now show the browse classification or website display group that they apply to (which is what MWS showed). 

https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2022-04-01-model
