### ISSUE TITLE
[FEATURE] Could getShipments operation provide  the Amazon Reference ID of the shipment

### ISSUE THREAD

**Issue by ihoment-meihui** [amzn/selling-partner-api-docs#1780]
**Describe the improvement**
Could getShipments operation provide  the ReferenceId of the shipment?
It will make sellers and logistics providers to get the ReferenceId info easily.
**URL of the content on GitHub**
https://github.com/amzn/selling-partner-api-docs/blob/main/references/fulfillment-inbound-api/fulfillmentInboundV0.md#getshipments

**Comment by stefnats** [comment]
What ReferenceId are you referring to?

**Comment by ihoment-meihui** [comment]
At the bottom left of the picture
![image](https://user-images.githubusercontent.com/35246538/145203075-89f64242-98d6-46d7-bdf9-175133652f69.png)

**Comment by philmccarty** [comment]
+1

This is fairly important, as my understanding is that the Reference ID is **sometimes** necessary for Carrier Central appointments.  Without it, it will require another trip back into SC in order to retrieve the reference ID, and ideally this process be able to work around/without it.

**Comment by philmccarty** [comment]
Just thought I'd check in to see if there was any work-around for this or progress in the addition?

**Comment by wmxyy** [comment]
+1
now，it is no way to get amazon reference id throgh  sp api，if have ? please tell  how to get amazon reference id  by  sp api ? thanks!

**Comment by bjpierre** [comment]
We have recently had a few LTL carriers call in and say they need this number in order to schedule a drop off via carrier central. It seems to be random as to when they need it. We are then forced to manually go and fetch this number. Annoying that amazon is enforcing rules that require us to go and manually touch orders without offering an automated way to do so. Especially when the solution seems to clear from the outside.

**Comment by phsilva** [comment]
Still a valid issue. No API provides amazon's reference ID.

**Comment by promisepk** [comment]
Has anyone found api provide Amazon reference Id?
