### ISSUE TITLE
why listAllFulfillmentOrders missing  fulfillmentOrders value

### ISSUE THREAD

**Issue by YFBook** [amzn/selling-partner-api-docs#1783]
when i  call api listAllFulfillmentOrders , i get the response which have nextToken and fulfillmentOrders, but fulfillmentOrders is empty list ,so the response like that
`{'payload': {'nextToken': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'fulfillmentOrders': []}}`

nextToken is not empty, i can use nextToken to call listAllFulfillmentOrders, but also return empty list 

why fulfillmentOrders is empty list ?

It may be correct that the fulfillmentOrders is empty, but why are the nextToken not empty?

**Comment by tomasWainer** [comment]
I have this same issue. 
Could this be related to restricted access to Personally Identifiable Information (PII)?

**Comment by kk-wdt** [comment]
I have this same issue too.

**Comment by aev-mambro2** [comment]
I have the same issue.

**Comment by aeveltstra** [comment]
In my case the cause was that we were pulling from the regular Orders API endpoint instead of the FBA Orders API endpoint. The endpoint still shouldn't be returning empty lists and several nextTokens: if the orders cannot be read by the client then no nextTokens should be provided. Instead, an access-denied error should be returned.
