### ISSUE TITLE
[403] My request got approved, but still showing your developer registration is under review. 

### ISSUE THREAD

**Issue by xiaoyu-tamu** [amzn/selling-partner-api-docs#182]
![image](https://user-images.githubusercontent.com/33362998/101258131-00479000-36e6-11eb-8cea-4a3bfdeccf51.png)

I keep getting `403: Error: Access to requested resource is denied` error even with sandbox url. I use the AssumeRole trick, and included the x-amz-security-token in my header, but still no operations work properly except get access token.

There is a warning in my sellercentral says my developer registration is under review, but I already got approved. I am able to create new application, self authorize and get the refresh token.

Do you all see this warning in seller central? If not, I might need to contact amazon to see if they set up the correct permission for me.

**Comment by toreylittlefield** [comment]
@xiaoyu-tamu did you have any luck getting this resolved? 

I am also having experiencing the same problem you are describing. I hope support can fix this issue it seems to be happening to enough devs as per the sub.

**Comment by RJEspera** [comment]
I'm having the same problem.  I used self-authorization, got the refresh token, and got the access token.  Signed the request successfully, but I keep getting 'Access to requested resource is denied' error using sandbox endpoint.  

Have you found a solution?

**Comment by xiaoyu-tamu** [comment]
@toreylittlefield @RJEspera  not yet, i created a case in seller central but still waiting for response

**Comment by toreylittlefield** [comment]
@xiaoyu-tamu @RJEspera after carefully rereading the instructions carefully I noticed that I did not register my developer application with Amazon under the IAM ARN role I created but with my AWS user. as per the getting started guide.

`Important. When registering your application, the IAM ARN that you provide must be for the IAM entity to which you attached the IAM policy from Step 3. Create an IAM policy. In this workflow, that IAM entity is the IAM role from Step 4. Create an IAM role. If you register your application using your **IAM user,** be sure that the IAM policy is attached to it. Otherwise your calls to the Selling Partner API will fail. We recommend registering your application using an IAM role, as shown in this workflow, to help you better control access to your AWS resources.`

I went ahead and created a new app in seller central with my created AWS role instead of the USER and now I can successfully make all calls. 

Hope that helps someone else that made the same mistake.

**Comment by RJEspera** [comment]
@toreylittlefield Thanks for sharing.  I have verified this as well, and I'm using the role ARN on my app (test app).  I'm using self-authorization.  Does it work for you when using this (self-authorization) flow?

My developer profile is currently under review as well, since I re-submitted it, but I do have a existing app (test).  I have ticket open with Amazon on this, I figure this could also be causing my authentication issue.

**Comment by xiaoyu-tamu** [comment]
@toreylittlefield Thanks, I may put the wrong ARN when registering the app.

should I use the IAM user ARN or the IAM role ARN?

**Comment by RJEspera** [comment]
According to the documentation, it should be the role ARN.

**Comment by xiaoyu-tamu** [comment]
Thank you guys. My problem solved, I put the user ARN instead of role ARN when registering app.

I am closing this now, feel free to open another issue.
