### ISSUE TITLE
Failure to execute 'updateShipmentStatus' API endpoint

### ISSUE THREAD

**Issue by tahir1122** [amzn/selling-partner-api-docs#1873]
**Describe the bug**
The 'updateShipmentStatus' API endpoint for Orders API is not working at all.

**URL of the content on GitHub**
https://github.com/amzn/selling-partner-api-docs/blob/main/references/orders-api/ordersV0.md#updateshipmentstatus

**Issue Details**
Returns nothing useful because the API is broken.
Following is one of the requests I tried and it failed:

POST /orders/v0/orders/{orderId}/shipment
{
"marketplaceId": "A1VC38T7YXB528",
"shipmentStatus": "RefusedPickup"
}

Following is the response I get:
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Unsupported ShipmentStatus passed",
      "details": ""
    }
  ]
}

even though 'RefusedPickup' is a valid Shipment Status 
(https://github.com/amzn/selling-partner-api-docs/blob/main/references/orders-api/ordersV0.md#shipmentstatus)

Similarly, I get following error if I change the shipmentStatus:
"errors": [
{
"code": "InvalidInput",
"message": "Invalid Request Parameters",
"details": ""
}
]

I have been using the following spec for samples on the payload for the request:
https://raw.githubusercontent.com/amzn/selling-partner-api-models/main/models/orders-api-model/ordersV0.json

**Comment by lozo55** [comment]
Hi, i had simillar problem: 

I have a problem with the updateShipmentStatus endpoit.I have response code 400:

'code: "InvalidInput",
"message": "Invalid Request Parameters".
I don't understand what the problem is, all other endpoints work fine for me. Payload is correct in my opinion. I pass an array with marketplace_id and shipment_status, order_items I leave empty.
I pass the order_id and payload to the UpdateShipmentStatusRequest method. The data is in the format as in the documentation from amazon. Does anyone know what the problem is? I will accept any advice as I am tired of this.
