### ISSUE TITLE
getOrders API not returning all fields for Shipping Address even though RDT used.

### ISSUE THREAD

**Issue by dingledorf** [amzn/selling-partner-api-docs#1908]
I followed the steps here exactly

https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/tokens-api-use-case-guide/tokens-API-use-case-guide-2021-03-01.md.

After replacing x-amz-access-token with an RDT that's generated and successfully making a call to the getOrders API I am still unable to see the Name and AddressLine1 fields of the shipping address. I need to make a subsequent call to the getAddress API in order to pull that information and sometimes it randomly returns null for every field.

What are next steps to be able to get Shipping Address info consistently so that we can fulfill orders to customers promptly?

Thanks

**Comment by CKTara** [comment]
you don't have pii

**Comment by dingledorf** [comment]
I do.

**Comment by WWangYu** [comment]
@dingledorf  How did you get the PII permission?

**Comment by daniel031699** [comment]
@dingledorf Now I can get the RDT correctly. When calling the getorders interface with RDT, I always prompt unauthorized. Can you help me?
`{
  "errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "Unauthorized",
     "details": ""
    }
  ]
}`

**Comment by DaniZapata** [comment]
Hello 

We had our app already up and running everything was running fine but since last week we stopped receiving the PII information for shipping addresses in all our new customers stores. Last week we were able to just regenerate the tokens but the error keeps happening and we are no longer able to fix it by just regenerating the tokens has anyone figuered out something. 
I tried making the request by sending the RDT but the response stays the same.

Help is much appreciated
