### ISSUE TITLE
[BUG] Documentation

### ISSUE THREAD

**Issue by Sabinkv** [amzn/selling-partner-api-docs#1954]
Hi, Can anyone help me with error MD1000? 

Application is in the draft state and trying a production authorization workflow by adding the version=beta param in the URL, Still, I am getting the "MD1000. unable to find the application."

I was trying to connect the Amazon seller central account from my website (production)  by using OAuth URI like below.
https://sellercentral.amazon.com/apps/authorize/consent?application_id=appidexample&state=stateexample&version=beta

But after the two-step verification, It says ERROR: MD4100, Unable to find the application. 

Could anyone please help me to know what will be the reason for it?

**Comment by puppsupr** [comment]
Hi,

If you are still facing this issue, in order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end.

Thanks and Regards,
Supriya P
Solutions Architect, Selling Partner API
