### ISSUE TITLE
[BUG] GET /catalog/2020-12-01/items: searchCatalogItems by UPC should return correct child ASIN, not Parent ASIN

### ISSUE THREAD

**Issue by quynhkim** [amzn/selling-partner-api-docs#2022]
Issue of API https://github.com/amzn/selling-partner-api-docs/blob/main/references/catalog-items-api/catalogItems_2020-12-01.md#get-catalog2020-12-01items
Operation: searchCatalogItems

to search for UPC, example: UPC = 889698484688

- When I search this UPC 889698484688 on amazon.com, it returns the correct ASIN = B083MCT12J which is a child ASIN 
- But using the SP-API above, it returns the Parent ASIN = B08ZPHTPPC which is wrong 

Can Amazon SP-API developer team fix this issue please?

**Comment by chapmanjw** [comment]
@quynhkim This is a known issue we are working through (not a simple fix). For keywords (not product identifiers), this will be fixed later in the year (exact timeline TBD). For product identifiers, a fix is being deployed to return only the exact ASIN matched (instead of the parent). That should be fully rolled out within the next week. I will update this issue once I've confirmed it has been deployed. Thanks.

**Comment by chapmanjw** [comment]
@quynhkim Apologies for the delayed response. When you search for UPCs in the v2020-12-01, the resulting items no longer rollup to the parent ASIN and return the actual ASIN matched.

Additionally, we have launched the v2022-04-01 version of the Catalog Items API. This version allows you to search by up-to 20 identifiers explicitly (i.e. the new `identifiers` parameter takes a list of IDs to query by). https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2022-04-01-reference
