### ISSUE TITLE
Which report version is correct

### ISSUE THREAD

**Issue by vikingcodes** [amzn/selling-partner-api-docs#2023]
Right now two versions showing 

Version : 2020-09-04
Version : 2021-06-30

Which version is correct and updated?

**Comment by jenilew** [comment]
Hi @vikingcodes ,

Both versions of the Reports API are currently supported and up-to-date. You have the option of using whichever version best suits your use cases. 

We always encourage folks to use the most recent version, (in this case, version 2021-06-30) because it will have the latest and greatest features. 

The primary difference between the versions is that the requirement for client-side encryption has been removed from version 2021-06-30; making integration easier. 

Thank you,

Jenilew
Selling Partner API Developer Support
