### ISSUE TITLE
[BUG] Access to requested resource is denied

### ISSUE THREAD

**Issue by tanaililing** [amzn/selling-partner-api-docs#2053]
Hi, I need your help, I can use the authorization interface of spapi to get the accesstoken according to refreshtoken, but if I call any business, I will report the following error, please help me to check what is wrong, thank you

![image](https://user-images.githubusercontent.com/42733436/154428868-936d96f4-341d-4a1e-8bd1-56fc02d777fa.png)

{
  "errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "Unauthorized",
     "details": ""
    }
  ]
}

requestId: 3a958ffd-7a27-4249-9731-8fd2a23839ea

**Comment by rohitdobariya** [comment]
Hi @tanaililing I saw that you try to convert MWS token to SP-API?

**Comment by lobotomisador** [comment]
@tanaililing the error means that the credentials you are using to generate the signature do not have the permissions to request an authCode. This can happen because the credentials tied to your amazon IAM role don't have permission to access the `execute-api` resource or the seller has not authorized your app as a manager.

**Comment by lobotomisador** [comment]
@tanaililing now that I think a about it, you are missing the `amz-security-token` header.

**Comment by sungolivia** [comment]
Hey @tanaililing not sure if you are still running into this issue but feel free to check out this troubleshooting error [blog](https://developer-docs.amazon.com/sp-api-blog/docs/troubleshooting-selling-partner-api-authorization-errors)!
