### ISSUE TITLE
Access to requested resource is denied. - Unathorized

### ISSUE THREAD

**Issue by tabbedy** [amzn/selling-partner-api-docs#2091]
Hello together,

i already tried to contact developer support, but the answer was not helpful... I want to try it here. 

i try to get Access to Selling Partner API and have problems in authorizing.

- I did the steps 1 to 5 from Creating and configuring IAM policies and entities.
- I added MFA to the user because i read that it could be a point
- I use Self authorization mode and created the Access token with the /auth/o2/token request successfull
- I created temp credentials within the sts request with the call AssumeRole and i used them in my final request
- i added the x-amz-access-token and also the X-Amz-Security-Token in the header information
- i added Authorization to my header with the following value AWS4-HMAC-SHA256 Credential=ASIA4KA7FL73A7ROU/20220302/us-east-1/execute-api/aws4_request, SignedHeaders=host;x-amz-access-token;x-amz-date;x-amz-security-token, Signature=ad0d92f2fcade3bdd72b4334d91b31dcd418714bc83a549d7d5d1fa57a245

i start requesting https://sandbox.sellingpartnerapi-na.amazon.com/orders/v0/orders?CreatedAfter=2022-02-09T18:34:56.518Z and received

{
"errors": [
{
"message": "Access to requested resource is denied.",
"code": "Unauthorized",
"details": ""
}
]
}

can you help me please? I am a little bit helpless.

I used Postman v9.14.7 for tests of the api. The AWS signature Authorization is already included there, but the automatically added headers are with capital letters:
- X-Amz-Date
- X-Amz-Security-Token

RequestId:11196db6-311a-4d90-bc06-8b8a01ee179a
TimeStamp:Wed, 02 Mar 2022 18:34:58 GMT
RequestApplicationId:amzn1.sp.solution.99b9130f-059c-42e2-b701-f425b56a3d72

Thank you so much for your help.
Best regards
Patrick Janz

**Comment by sungolivia** [comment]
Hey Patrick,

Would you mind sharing the case ID that you had with the developer support team? I would like to take a look to get more context!

There are few things you can check when you get Unauthorized errors:
* Account status: Check that seller account you are making a requests has a healthy status. You can check in [Seller Central Developer Console](https://sellercentral.amazon.com/) > Performance > Account Health.
* Region mismatch: Check the seller account that you are making request to is in the same region as the endpoint you are using in the request. Please note that application is global but not the seller accounts.
* API Access: Check the API operation you are making a request to and verify if your application has access to that API. To verify role permissions, within Seller Central, navigate to Apps & Services > Develop App's and click the Edit App button for the app you are using to view the App registration form. The check boxes selected will tell you the roles you have added to your application.
* Missing SP API Role: If you are missing the role you need for the API access, navigate to Developer Profile to ensure you requested access to that role. Please note that for restricted roles you may need to re-submit your Developer Profile for access to it. Once the role is added, re-authorize your application i.e. Generate a new LWA Refresh token to make valid API calls.
* Missing IAM ARN: If you have all the correct roles and permissions added, verify your IAM ARN is added to the application. The IAM ARN added should be the one to which the IAM policy was attached during registration process.
    * If IAM ARN is IAM Role, ensure that IAM policy is attached to the role.
    * If IAM ARN is IAM User, ensure that IAM policy is attached to the IAM User and not to the IAM Role.
    * If the IAM ARN added to the application is IAM Role, ensure that you are using the temporary credentials and a session token obtained from AWS Security Token Service (AWS STS) in your request along with LWA access token.

Since you also mentioned that you are using [sandbox](https://developer-docs.amazon.com/sp-api/docs/the-selling-partner-api-sandbox) to test, are these values hard coded? 
Have you included the marketplace as well?

I am most curious about what roles you have as well. 

Also please redact all the credentials and keys in the post!!!

**Comment by tabbedy** [comment]
The Credentials in my post are changed :)
That was my point -> i thougt the region has no matter, but it has. I changed the region and now i am a step further 👍 
Thank you very much!
