### ISSUE TITLE
Please add postedAfter-postedBefore params to /finances/v0/financialEventGroups/{eventGroupId}/financialEvents

### ISSUE THREAD

**Issue by nafberger** [amzn/selling-partner-api-docs#2121]
a lot of people poll the finance API by eventGroupId which corresponds to an amazon settlement report.

those reports stay open for 2 weeks and new transactions get posted to them,
if someone wants to get the bew stuff he has to be able to filter by postedAfter-postedBefore justlike it is is the listFinecialEvents call. this is very important

**Comment by theunixbeard** [comment]
We have this issue too at [Empire Flippers](https://empireflippers.com/about-us).

It's the same issue as the following other open issues:

- https://github.com/amzn/selling-partner-api-docs/issues/2139
- https://github.com/amzn/selling-partner-api-docs/issues/708

Everyone's goal is to recreate the "Date Range" reports as seen in Seller Central, going back 2 years as was possible with MWS.

In the Date Range reports there are 2 dimensions by which we split up the finance data, by month and by marketplace.

As explained in this issue: https://github.com/amzn/selling-partner-api-docs/issues/1733

There are fees like Adjustments, Service Fees, etc which have no identifying information when returned by the Finances API.

In MWS you could implicitly assign a given fee to a specific month / marketplace by querying with BOTH FinancialEventGroupID (e.g. the Marketplace, Spain vs France vs Netherlands) AND postedAfter-postedBefore (set to the start/end of a given calendar month).

Then, if a fee was returned by the API, you knew what month/marketplace to assign it to, even though the XML/JSON itself didn't contain this info.

However, with SP API we can no longer query the API by BOTH FinancialEventGroupID AND postedAfter-postedBefore, but ONLY one of the two.

The other approach, querying for this data via the Reports API rather than the Finances API, is also deprecated in SP-API: https://github.com/amzn/selling-partner-api-docs/issues/967

**_Counting this issue, that's 5 open issues regarding the same problem..._**

Obviously we brought this issue up with Amazon Support many times, but in each ticket they simply say they'll pass the info along and nothing gets done. Example case IDs include: 9776857691, 9776768131, 9562103261

I guarantee if Amazon doesn't fix this issue or delay the December 31st deadline for turning off MWS for the Financial Events API that many, many companies reporting use-cases will be broken.

@nafberger I assume that you still have this problem as well?

CC @chapmanjw @sungolivia @jevoniuk can any of you please give us some insight into this important issue?

**Comment by tspicer** [comment]
@theunixbeard We have also observed the refund information is always NULL. It is not clear if this is an API issue, a documentation issue, or something we are doing incorrectly on our end (maybe it is all three).

**Comment by histonedev** [comment]
@theunixbeard We still face the issue. They just pass along the info to their team and nothing gets done after many support tickets over last 18 months. 

Now, they are not even replying to deadline extension requests. Few of our most important features are at stake here.

**Comment by Yvan8** [comment]
Is there a new solution, big shots

**Comment by napter** [comment]
Does anyone from Amazon read /respond to these issues?
