### ISSUE TITLE
is Tax Remittance and Tax Invoicing Roles needed to get PII information for seller API

### ISSUE THREAD

**Issue by coder771** [amzn/selling-partner-api-docs#2140]
Can we not get PII information just by Direct-to-Consumer Delivery(Restricted) Role for seller api?

**Comment by lenn-mark** [comment]
Same here,
Security team asks unusual questions about Tax Invoicing and Tax Remittance like below

_2. How do you confirm that your tax calculation is reliable for government reporting standards?_
_4. Justify why you need a tax invoicing mechanism other than the one already available through Seller Central._

Intention is 
1. Get shipping data (buyer name, address, zipcode, phone number etc.) in order to prepare shipping labels etc. for FBM sellers
2. Just get all financial events to calculate profit/loss including taxes (HST,GST,Marketplace Facilitator etc...)

Could you please share the link about the scope of "Tax Remittance and Tax Invoicing" ? 
Which endpoints and which fields are affected?

Developer profile is created at 2019 so i have no idea about even we need them or not. 

Please advise.
