### ISSUE TITLE
Cannot submit application for Approval SPDC300

### ISSUE THREAD

**Issue by mlepine** [amzn/selling-partner-api-docs#2164]
Our application is currently in draft state and when we submit to be published we get the error SPDC300 with no further explanation. We have opened and re-opened a case multiple times and it keeps getting closed after 3 weeks with a generic response. This is currently gating us from migrating away from MWS to the SP-API.

**Comment by puppsupr** [comment]
Hi,

Error SPDC300 generally occurs if you are providing unacceptable html tags or phone number format. If you are still facing this issue, can you please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation.
Once you do so, please post the Case ID here so that Ill make sure someone is looking into.

Thanks and Regards,
Supriya P
Solutions Architect, Selling Partner API
