### ISSUE TITLE
FATAL / CANCELLED Errors in Reports Data 

### ISSUE THREAD

**Issue by webs-harsh-rana** [amzn/selling-partner-api-docs#2181]
When I call a report in a loop and when we get the report data it always returns a FATAL status, what is the reason?

I am fetching reports of the whole week in a loop day by day, so I get the report id from createReport API, but when I call getReport it will always return FATAL, can anyone explain to me why it returns FATAL.

I have a logic for reports to check the whole week data in a loop day by day, and if it is found that any of the day's reports are not generated then it will call that particular date report data,

like let's say, my cron is running daily and it will execute the loop something like this

`$firstday = date('Y-m-d', strtotime("this week")); 
$end_date = date('Y-m-d');

while (strtotime($firstday) <= strtotime($end_date)) {
    if($firstday <= $end_date){
        //my logic to check the report is generated for that day if not then call create report
        $startDate = date('Y-m-d', strtotime('-1 day', strtotime($firstday)));
        $startDate .= " 00:02:00";
        $endDate = $firstday;
        $endDate .= " 00:01:59";
        $reportType = 'GET_FBA_FULFILLMENT_INVENTORY_HEALTH_DATA';
    }
    $firstday = date ("Y-m-d", strtotime("+1 day", strtotime($firstday)));
}`

So this is my logic that how I can fetch the report for a single day.

Also, this same logic I was using in MWS and is working fine till now. I am facing this issue only in SP API.

**Comment by stefnats** [comment]
It seems that there is no data for this date range, could you confirm that? 
Also, `CANCELLED` is often times the term for "no data" as stated here:

https://github.com/amzn/selling-partner-api-docs/issues/920
https://github.com/amzn/selling-partner-api-docs/issues/1329

Also this error was raised in another issue before:

https://github.com/amzn/selling-partner-api-docs/issues/1906

This is, in my opinion, a flaw in the API (or in the reports department) and makes developer's life a bit more difficult.

You should also switch the Report Type from `GET_FBA_FULFILLMENT_INVENTORY_HEALTH_DATA` to `GET_FBA_INVENTORY_PLANNING_DATA `, because it's deprecated: https://github.com/amzn/selling-partner-api-docs/discussions/2165

I hope this helps!

**Comment by webs-harsh-rana** [comment]
Thanks for the reply,

we got the same issue in the below reports, some of the reports are successfully get
GET_FBA_FULFILLMENT_INVENTORY_SUMMARY_DATA - DONE
GET_FBA_FULFILLMENT_INVENTORY_ADJUSTMENTS_DATA - DONE
GET_FBA_FULFILLMENT_CUSTOMER_RETURNS_DATA - DONE


**Below are the Reports that return FATAL/CANCELLED**

GET_FBA_MYI_UNSUPPRESSED_INVENTORY_DATA - FATAL
GET_RESERVED_INVENTORY_DATA - FATAL
GET_FBA_FULFILLMENT_REMOVAL_ORDER_DETAIL_DATA - CANCELLED
GET_FBA_FULFILLMENT_CUSTOMER_SHIPMENT_REPLACEMENT_DATA - CANCELLED

**Comment by JennyHung1212** [comment]
I also "sometimes" got a FATAL with these two reports

GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL
GET_FBA_FULFILLMENT_REMOVAL_ORDER_DETAIL_DATA
