### ISSUE TITLE
[FEATURE] Amazon Developer API consulting

### ISSUE THREAD

**Issue by kiddmana** [amzn/selling-partner-api-docs#2185]
Hello,
       1. We are an Amazon seller software service company, specializing in providing Amazon seller customers with SaaS services for store management and advertising management.
       2. Now we have applied for Amazon Store Developer Account (sp-api) and Amazon Advertising Developer (Ads API) using two different company entities.
       3. All our software functions are integrated into the same SaaS project, which means our projects will use the same domain name and be deployed on the same server.
       4. In this case, if we provide SaaS services for seller customers, will it have an associated impact on the seller's store?
       5. If there is, how should we deal with it here, please help to give some suggestions.

thank you.

**Comment by stefnats** [comment]
I think you should be open about that up-front and create a ticket with Amazon Support and request their permission.
If there should be any trouble with it later, you can always refer to that ticket and the answer.

**Comment by sungolivia** [comment]
Hey @kiddmana 

Since this was awhile ago, not sure if you are still running into this but I would highly suggest making note of everything you said in your developer profile when you are applying access for SP API.
It will provide insight and use case for the team!

Thanks,
Olivia
Solutions Architect, SP API
