### ISSUE TITLE
SellingApiForbiddenException: [{'message': 'Access to requested resource is denied.', 'code': 'Unauthorized', 'details': ''}]

### ISSUE THREAD

**Issue by paulamascot** [amzn/selling-partner-api-docs#2193]
Hello,

I have this error: SellingApiForbiddenException: [{'message': 'Access to requested resource is denied.', 'code': 'Unauthorized', 'details': ''}],  when trying to get Vendor Orders information through the SP API for the Marketplaces: IT, SE and NL.

I was able to get Vendor Orders information normally for UK, DE and ES.

Does anyone know what is happening with IT, SE and NL?

Thank you.

**Comment by stefnats** [comment]
I don't use Vendor API Calls, but i have the same behaviour:

Since yesterday - so really the timing from this issue - i had the same issue getting the Unauthorized / Forbidden error for some Non-EU Marketplaces (North America / Far East Region)

*What helped was that the seller re-authorized our app.*

In Seller Central, before re-authorizing, our app was still authorized for a few months (some even until next year). So, try out re-authorizing.

At Amazon: Do you know about this error, could you make a statement about this?

**Comment by Adrian-T-AMZN** [comment]
Hello @[paulamascot](https://github.com/paulamascot),


In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end.


Thanks,

Adrian T.

Selling Partner API Developer Support
