### ISSUE TITLE
Vendor central integration

### ISSUE THREAD

**Issue by discover59** [amzn/selling-partner-api-docs#2247]
Hi,

I am using selling partner API for both sellers and vendors.
When vendor authorizes my application, it returns `amzn1.vg.xxxxx` as partner id while seller authorization returns market id.

I want to map this vendor id and the id from advertising API which starts with `ENTITY`.

Is there any API to get entity id for vendor account?

Thanks

**Comment by Adrian-T-AMZN** [comment]
Hello @[discover59](https://github.com/discover59),

In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end.

Thanks,
Adrian T.
Selling Partner API Developer Support
