### ISSUE TITLE
MWS - SP-API Hybrid - Sellers are unable to renew their MWS credentials on SC - They are taken to the SP-API renew process

### ISSUE THREAD

**Issue by nrogers805** [amzn/selling-partner-api-docs#2275]
MWS - SP-API Hybrid - Sellers are unable to renew their MWS credentials on SC - They are taken to the SP-API renew process

They should be taken through the original MWS process. 

My App is not yet fully SP-API compliant as I am working though this process.

Why is the renewal process doing this?

Thanks

**Comment by avvarga** [comment]
Hello @nrogers805,

Thank you for reaching out regarding the MWS renewal process.

I understand the confusion generated for this situation since, once the Application is converted into Hybrid, the old MWS process is no longer available.

In the new SP API renewal process, however, once your customer completes the authorization process through the OAuth method, the response URL will contain both a new MWS Authorization Token and a Selling Partner Authentication Code, which can be exchanged for a Refresh Token.

You can find details regarding this in our [Amazon SCPN authorization workflow](https://developer-docs.amazon.com/sp-api/docs/amazon-seller-central-partner-network-authorization-workflow).

If the information available in the documentation link provided above does not fully resolve your inquiry, please [open a support case](https://developer.amazonservices.com/support) with us.

Thanks,
Alejandro C.
Selling Partner API Developer Support

**Comment by nrogers805** [comment]
"In the new SP API renewal process, however, once your customer completes the authorization process through the OAuth method, the response URL will contain both a new MWS Authorization Token and a Selling Partner Authentication Code, which can be exchanged for a Refresh Token."

Where is this mentioned in the documentation ?

**Comment by avvarga** [comment]
Hello @nrogers805,

The tokens are provided to you on [Step 4](https://developer-docs.amazon.com/sp-api/docs/amazon-seller-central-partner-network-authorization-workflow#step-4-amazon-sends-you-the-authorization-information) of the workflow.

Thanks,
Alejandro C.
Selling Partner API Developer Support

**Comment by nrogers805** [comment]
I meant where is the below stated in any of the current documentation ?

"Ionce your customer completes the authorization process through the OAuth method, the response URL will contain both a new MWS Authorization Token and a Selling Partner Authentication Code, which can be exchanged for a Refresh Token."
