### ISSUE TITLE
How Selling Partner API throttling algorithm works

### ISSUE THREAD

**Issue by ynaft** [amzn/selling-partner-api-docs#2279]
I'm trying to figure out the "token bucket algorithm" for rate limiting how many API requests a user can make. so I have a burst of 10, which means the bucket has initially 10 tokens, so I can make 10 requests, then I have a restore rate of 45 seconds, which means it takes 45 seconds for a token to be deposited in to the bucket, so I should be able to make another one request.

Now based on what I understand, if I empty out all 10 at once, then I'll have to wait 45 seconds to get one token back in, and then at 90 seconds I'll have 2 tokens back in and at 135 I'll have 3 and so on until the bucket is filled with 10 tokens. but when I'm actually testing it with the Selling Partner API, I get a total different picture.

My test with a stopwatch showed, that when I finished emptying the whole bucket (10 requests) which took 00:00:11.50 I was able to get a new token (execute a successful request) at 00:00:48.14 which is less than 45 seconds from the 'last' request, so I figured maybe I have to count from the 'first' request, but then at the later requests I saw a totally mixed up pattern how they come in, the next one was in at 26 seconds than one at 4 seconds and so on with different time laps, see screenshot.

![image (6)](https://user-images.githubusercontent.com/105665156/168644170-8cad601a-3fbc-45b2-bf76-7c2a580dad83.png)

Can anyone explain?

**Comment by ttimbul** [comment]
Perhaps the documentation refers to a "guaranteed stable rate", so the smart thing would be to:

- Use the value from the documentation as an initial value for 'sleep'.
- Inspect the throttle headers from each response to re-configure your throttling code.
- In the end you will want to end up with code that calls every 45.045 seconds _on average_. It may help to use a lock/throttler library that allows you to specify the rate per second instead of manually calling 'sleep'. If you call from multiple threads, make sure the locking/throttling code is concurrent/thread-safe.
- When I code for the API I do not take into account the 'burst' allowance, so that it helps to smooth out small timing issues.

**Comment by tmyers273** [comment]
x2. There seems to be some undocumented logic about the throttling algorithm.

It appears that there is some per-item throttling in place, instead of the per-request throttling alluded to in [the docs](https://developer-docs.amazon.com/sp-api/docs/product-pricing-api-v0-reference#get-productspricingv0competitiveprice) and hinted at [here](https://github.com/amzn/selling-partner-api-docs/discussions/2017#discussioncomment-2127613), at least on the `/products/pricing/v0/competitivePrice` endpoint. 

If this is true, with the upcoming SP API [throttling reductions](https://github.com/amzn/selling-partner-api-docs/discussions/2369), we have big worries about our use case being slowly deprecated (related [1](https://github.com/amzn/selling-partner-api-docs/discussions/2370) [2](https://github.com/amzn/selling-partner-api-docs/issues/975)). 

We have users trying to analyze ~100k products at a time. Coming from MWS with a [10 items / sec limitation](https://docs.developer.amazonservices.com/en_US/products/Products_GetCompetitivePricingForASIN.html) to the planned change in the SP API of 1 item every 2 seconds will increase the minimum run time to analyze 100k products for our users by 20x (jumping from ~2.7 hours to a whopping 54 hours).

### Test Results

<img width="459" alt="image" src="https://user-images.githubusercontent.com/10467493/178805392-55cf9a71-c68a-4933-9cf8-4df47ac4e1fe.png">
<img width="656" alt="image" src="https://user-images.githubusercontent.com/10467493/178808826-5b1c5759-6474-4f91-ae92-335ab82526de.png">

The correlation between asins per call and the number of throttling errors is quite apparent.

If the API was really throttling on a per-request basis (as documented), we should see near zero throttling errors for all asin counts. But that is clearly not the case.

### Testing Methodology

Tests done on the `/products/pricing/v0/competitivePrice` endpoint. To test, I essentially looped through 1,000 iterations with a different number of ASINs in each call, calling the endpoint in a separate thread.

```go
for i := 0; i < 1000; i++ {
    go callGetCompetitivePricing(asins)
    time.Sleep(100 * time.Millisecond)
}
```

**Comment by ttimbul** [comment]
Looks like I commented prematurely and naively, as we're now experiencing the same inverse relationship between the number of asins per call vs error rate, so something is definitely off. It doesn't seem Amazon engineers know what they're doing either or has either of you got any meaningful response out of them?
