### ISSUE TITLE
[FEATURE] Documentation

### ISSUE THREAD

**Issue by lashaLobjanidzeXentral** [amzn/selling-partner-api-docs#2310]
**If you need help troubleshooting a problem with Selling Partner APIs, please [open a support case](https://developer.amazonservices.com/support). Issues are for reporting documentation bugs and enhancements only.**

**Describe the improvement**
Improve documentation.

**URL of the content on GitHub**
[shippingservice](https://github.com/amzn/selling-partner-api-docs/blob/main/references/merchant-fulfillment-api/merchantFulfillmentV0.md#shippingservice)

**Description of what the documentation currently says**
`RequiresAdditionalSellerInputs` is required.

**Description of what the documentation should say**
`RequiresAdditionalSellerInputs` is optional.

**Screenshots**
![Bildschirmfoto 2022-05-24 um 10 06 09](https://user-images.githubusercontent.com/81755255/169984743-a74b54e0-9552-409f-b4cf-e1b41c952c85.png)

**Additional context**
-

**Comment by Trimakas** [comment]
Unfortunately the help desk is completely worthless. I've contacted them multiple times and all I ever get is more links to documents that are incomplete. I was also told that they are unable to do any research on calls made outside of Postman, and in fact they have no more information than what is returned by the API itself. Furthermore the error messages returned by the API are also worthless, and never state what the issue is, but instead provide generic mis-direction.
