### ISSUE TITLE
Important Notice: Developers using Selling Partner API for Direct Fulfillment must implement RDT by July 31, 2022

### ISSUE THREAD

**Issue by moriend1976** [amzn/selling-partner-api-docs#2352]
Our company uses amazon SP-API Vendor Orders API.
https://sellingpartnerapi-na.amazon.com/vendor/orders/v1/purchaseOrders
I tried to use RDT for this API,
But with RDT token, can't get orders.
The payload for RDT token is below.
{
    "restrictedResources": [{
        "method": "GET",
        "path": "getPurchaseOrders"
    }]
}
Maybe, Vendor Orders API not requires RDT ?
Or path is wrong ?

**Comment by CrionaAm** [comment]
Hello @moriend1976,

In order to correctly resolve this issue, please open a support case (https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end. In your case please include the full request and response, including headers, provided a a .txt attachment.

Thanks,
Críona
Selling Partner API Developer Support
