### ISSUE TITLE
[BUG] Report - Start - End -Date

### ISSUE THREAD

**Issue by kevinvenclovas** [amzn/selling-partner-api-docs#2353]
Hi im very confused.

I want some some datas from my order. So i use this report :  ReportTypes.GET_FLAT_FILE_ORDER_REPORT_DATA_INVOICING

Some information about my order:

PurchaseDate = **10:56:02 UTC Time**
LastUpdateDate = **12:10:51 UTC Time**

Now i cant find this order in the report result with all combinations of the available timestamps.
I tried some random timestamps and got the order only back on the timestamp: **11:35:31 UTC Time**

What is this for an timestamp? This make zero sense for me!

**Comment by CrionaAm** [comment]
Hello @kevinvenclovas 

In order to correctly resolve this issue, please open a support case: (https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end. Please make sure to include:

 Request and response, untruncated, including headers and as a .txt format file attachment.
 Application ID
 Order ID
ReportIDs

Thanks,
Críona
Selling Partner API Developer Support
