### ISSUE TITLE
When using putListingsItem to add a product, the attribute main_product_image_locator provides the correct AWS URL, and the upload is also successful, but why can't the image be displayed?

### ISSUE THREAD

**Issue by DDDDDID** [amzn/selling-partner-api-docs#2372]
When using putListingsItem to add a product, the attribute main_product_image_locator provides the correct AWS URL, and the upload is also successful, but why can't the image be displayed?

**Comment by Adrian-T-AMZN** [comment]
Hello @[DDDDDID](https://github.com/DDDDDID),

In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end.

Thanks,
Adrian T.
Selling Partner API Developer Support

**Comment by ThanhLuan0932** [comment]
Hi @DDDDDID, I'm having a little trouble with providing the `attributes` for the `putListingsItem `API. Can you give me a reference to your Json attribute file?
![image](https://user-images.githubusercontent.com/33895995/180114988-f27e898e-0cdf-48a6-b69f-f82b2b09551b.png)

Thanks for your help !
