### ISSUE TITLE
[BUG] searchCatalogItems does not return pagination if provide pageSize=20

### ISSUE THREAD

**Issue by hamduc7** [amzn/selling-partner-api-docs#2377]
**API URL:**
https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2022-04-01-reference#searchcatalogitems

**BUG:**
If we add PageSize=20 in this call, you will see 30 items, in this case, we should have "pagination.NextToken" because we only see 20 items.

https://sellingpartnerapi-na.amazon.com/catalog/2022-04-01/items?marketplaceIds=ATVPDKIKX0DER&identifiers=033331022328,046501006325,046501006332,046501020628,046501121400,046501155009,046501155108,046501155306,046501155405,046501401823,046501402486,046501403049,046501403100,046501404206,046501404251,046501404428,046501405555,046501405562,046501405586,046501405593&includedData=summaries&identifiersType=UPC&pageSize=20

`"numberOfResults": 30,
 "items"`[....]`

But if we REMOVE PageSize=20, we will see the pagination, the first call will have 20 items, the next call uses the nextToken will return next 10 items
`numberOfResults": 30,
    "pagination": {
        "nextToken": "sssssss"
    },
    "items"`[
..............
]

**Comment by LindaNC** [comment]
Hello @CLK240,

In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation. Please make sure to provide the following:

- Full request and response in .txt format
- Request id 
- Timestamp
- API call

Thanks,
Linda
Selling Partner API Developer Support

**Comment by chapmanjw** [comment]
@hamduc7 I have been able to reproduce the issue on our end and have created a backlog item for my team to address this. I will update this Github issue once we have a fix rolled out. Thanks for reporting the issue.

**Comment by hamduc7** [comment]
@chapmanjw Thank you very much.

**Comment by Bowserlord** [comment]
Same problem here. 
I dont get always pagetoken if numberOfResults> 20. Sometime a pagetoken will return but the requests dont add up to numberOfResults.

**Comment by kallen** [comment]
Having the same issue.  Is there any update on this by chance?

**Comment by jim-foley** [comment]
Hi @chapmanjw ...do you have any estimated time of resolution on this? It's a major issue for our software which uses this endpoint for product mapping; and it's one of the bugs that is preventing us from going live with our SP version. Our concern is the deadline is coming up quick and we need to make sure our SP version is in production well before MWS is turned off. Thank you for your time.

**Comment by chapmanjw** [comment]
Hi @jim-foley,

The fix for this issue was deployed earlier today. One important aspect to note is that the `numberOfItems` in the responses is an estimate. As we paginate through the results, deleted ASINs get filtered out, occasionally resulting in less actual results that the `numberOfItems` count. (Well be updating the documentation on this operation to make this more clear). 

Thanks!

**Comment by dc-harsh-dt** [comment]
This is insane. Still not able to perform pagination on `searchCatalogItems`. Even if the `pageSize` is 1, `NumberOfItems` are `369566`. But not getting any pagination/nextToken/previousToken.
Thanks

**Comment by chapmanjw** [comment]
> This is insane. Still not able to perform pagination on `searchCatalogItems`. Even if the `pageSize` is 1, `NumberOfItems` are `369566`. But not getting any pagination/nextToken/previousToken. Thanks

@dc-harsh-dt Can you share timestamps and request ids for requests where these were missing? The only times we should be omitting them is when there aren't any next/previous pages to reference.
