### ISSUE TITLE
[BUG] getItemOffersBatch truncate zero if the ASIN has prefix '0'

### ISSUE THREAD

**Issue by hamduc7** [amzn/selling-partner-api-docs#2380]
API:
https://developer-docs.amazon.com/sp-api/docs/product-fees-api-v0-reference#getmyfeesestimates

Let say the ASIN is: 0812995414, notice the '0' at the begin:
This is the batch request:
`{
    "requests": [
        {
            "uri": "/products/pricing/v0/items/0812995414/offers",
            "method": "GET",
            "MarketplaceId": "ATVPDKIKX0DER",
            "ItemCondition": "New",
            "CustomerType": "Consumer"
        } 
    ]
}`

**The ASIN in payload.ASIN is 812995414, the '0' is removed**.  Works correctly in the getItemOffers function
`{
	"responses": [{ 
			"body": {
				"payload": {
					"ASIN": "812995414",
				 
					"Identifier": {
						"MarketplaceId": "ATVPDKIKX0DER",
						"ItemCondition": "New",
						"ASIN": "812995414"
					} 
				}
			} 
		}
	]
}
`

**Comment by LindaNC** [comment]
Hello hamduc7

Thank you for bringing this to our attention.

In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation and provide the following details:

- What is the expected behavior and the issue you are encountering? 
- A copy of your request and the response you received, not truncated and attached as .txt document 
- Request and Response details: 
- API and operation called in the request 
- The Timestamp (available in the request) 
- The Request ID (available in the response)

Once you do so, please post the Case ID so we can keep track of the situation.

Thanks,
Linda
Selling Partner API Developer Support

**Comment by hamduc7** [comment]
Hi @LindaNC 
This is a bad response I have received. I reported a bug but you asked about things that are not related.
Is there anything in my report that is not clear for you to reprocedure the same problem on your end?
