### ISSUE TITLE
GET_VENDOR_INVENTORY_REPORT is missing metrics that are available in dashboard

### ISSUE THREAD

**Issue by wolendranh** [amzn/selling-partner-api-docs#2385]
Hi! 

 Currently `GET_VENDOR_INVENTORY_REPORT` is missing following fields that are present in dashboard. 
- procurable product OOS
- confirm rate
- and receive fill rate

Are they expected to be added to report or maybe it is possible to request extended report?

EDIT:

here is screenshot of dashboard with fields that I mentioned:
![Screen Shot 2022-06-28 at 9 01 56 PM](https://user-images.githubusercontent.com/6746231/176398801-62922a4a-4ac7-4611-9c64-410c1035f8ac.png)

Thank you in advance!

**Comment by LindaNC** [comment]
Hello @wolendranh,

In order to correctly resolve this issue, please open a support case (https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end. In your case please include the full request and response for the report you are indicating and the screen shot for the dashboard also.

Thanks,
Linda
Selling Partner API Developer Support
