### ISSUE TITLE
[BUG] Documentation

### ISSUE THREAD

**Issue by Aditya-php** [amzn/selling-partner-api-docs#2387]

**Comment by LindaNC** [comment]
Hello @Aditya-php,

This issue is missing a description of the problem, please post one within the next 5 days or we will be marking this issue as closed.

Please also take into consideration that for most questions, our documentation and frequently asked questions can be found [here](https://developer-docs.amazon.com/sp-api/) (https://developer-docs.amazon.com/sp-api/).

If this is a technical issue that requires additional troubleshooting steps because you are getting any kind of error response from the API, please [open a support case instead](https://developer.amazonservices.com/support) (https://developer.amazonservices.com/support).

Thanks,
Linda
Selling Partner API Developer Support

**Comment by Adrian-T-AMZN** [comment]
Hello @[Aditya-php](https://github.com/Aditya-php),

We are now resolving this issue as there was no reply from your end.

Thanks,
Adrian T.
Selling Partner API Developer Support
