### ISSUE TITLE
Shipping API v1 /shipping/v1/shipments/{shipmentId}  always 400

### ISSUE THREAD

**Issue by XRLZX8** [amzn/selling-partner-api-docs#2388]
when i request "/shipping/v1/shipments/{shipmentId}" with a shipmentId, always
`<Response [400]>
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Invalid input.",
      "details": "Shipment not found for specified shipmentId"
    }
  ]
}`
this api only need one parameter "shipmentId" , i dont know where are the problems.
and after request   "/shipping/v1/account",  it show my account is valid, which means my header or other auth are alright.
can anyone help me?

**Comment by LindaNC** [comment]
Hello @XRLZX8

In order to correctly resolve this issue, please open a support case: (https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end. Please make sure to include:

Request and response, untruncated, including headers and as a .txt format file attachment.
Application ID
Request id 
Timestamp

Thanks,
Linda
Selling Partner API Developer Support
