### ISSUE TITLE
[FEATURE] Documentation

### ISSUE THREAD

**Issue by pagelc17** [amzn/selling-partner-api-docs#2395]
I need some help understanding how to update inventory quantities without updating handling time. Some of our customers using Amazon FBM use custom handling times and when we set inventory values the handling time is being reset to zero.

**Comment by Adrian-T-AMZN** [comment]
Hello @[pagelc17](https://github.com/pagelc17),

In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end.

Thanks,
Adrian T.
Selling Partner API Developer Support

**Comment by chapmanjw** [comment]
@pagelc17 This is a current known limitation of the Listings Items API `patchListingsItem` operation. We have this on our roadmap to implement (i.e., granular patching of fields within attributes). We are currently evaluating different approaches to this and would love your input. 

The `patchListingsItem` operation uses a standard RFC6902 JSON Patch document: https://datatracker.ietf.org/doc/html/rfc6902. The path contained within a JSON Path uses JSON Pointers, which presents a unique challenge for Amazon listing payloads. Each attribute is a list, including `fulfillment_availability`. However, elements in the list are not ordered (meaning that an index-based path will not work) and indicating which element in the list to update is done by its selectors. For `fulfillment_availability` that is the `fulfillment_channel_code`.

Example listing:

```
{
  "fulfillment_availability": [
    {
      "fulfillment_channel_code":"OTHER_FULFILLMENT_PROGRAM",
      "quantity":20
    },
    {
      "fulfillment_channel_code":"DEFAULT",
      "quantity":10
    }
  ]
}
```

When patching the "DEFAULT" fulfillment channel quantity, the JSON Pointer specification would use: `/fulfillment_availability/1/quantity` to identify the path. However, in order to correctly identify which quantity to update, we need the fulfillment channel code, not the index ordinal. 

Some ideas we have been thinking about: 

1. Accept JSON Path (https://goessner.net/articles/JsonPath/) as the format for the patch path (in addition to the current JSON Pointers). This would allow expressions like `$.fulfillment_availability[(@.fulfillment_channel_code="DEFAULT")].quantity`, which provides the selectors needed using a common format. This has the downside of having to limit the expressions supported only to selectors like this as well as diverging from the JSON Patch specification. 
2. Customize JSON Pointers to include selectors like `/fulfillment_availability["fulfillment_channel_code"="DEFAULT"]/0/quantity`. This has the downside of diverging from the JSON Pointer specification.
3. Something else? Ideally, we would not diverge from the standard specifications here, but we have not yet come up with an option that works. Open to suggestions :-).

**Comment by chapmanjw** [comment]
@pagelc17 In the meantime, a read-before-write may be the only option to ensure you are including the previous values without clobbering them.

**Comment by pagelc** [comment]
Thanks I'll talk to our team about a read before write and have asked our lead developer to comment if he has any ideas.
