### ISSUE TITLE
The application isn't configured with Roles

### ISSUE THREAD

**Issue by JacobShirley95** [amzn/selling-partner-api-docs#2420]
Hi there,

I'm getting an error when trying to convert an MWS auth token over to an LWA token. My app is published as a hybrid app so I don't see what the issue is. Here is the error: The application isn't configured with Roles

Related to: https://github.com/amzn/selling-partner-api-docs/issues/347

Any help appreciated

Thanks,
Jake

**Comment by CrionaAm** [comment]
Hello @JacobShirley95,

When you register as an SP-API developer you are granted specific roles to access the data you need to us. When you then register your SP-API app you also need to assign roles to the app. Please log into seller central and go to: Partner Network>Develop Apps. Your app should be registered here. Please edit it to assign apps. If this does not resolve the issue please open a case with Developer Support directly so that we can offer more detailed troubleshooting and support: https://developer.amazonservices.com/support

Thanks,
Críona,
Selling Partner API Developer Support
