### ISSUE TITLE
Wrong Order Data - Vendor Orders API

### ISSUE THREAD

**Issue by Krawatsu** [amzn/selling-partner-api-docs#2421]
Hello,

We're trying to download vendor purchase orders via API. 
The problem is the data is incorrect between API and Vendor Central.

As you can see on the screenshot below - there is -3 quantity ordered. In fact there were 6 pieces ordered. 

![vendor bug](https://user-images.githubusercontent.com/102365997/178698374-041ce1ac-16e8-4252-87d7-764f50cdd838.jpg)

**Comment by CrionaAm** [comment]
Hello @Krawatsu 

In order to correctly resolve this issue, please log into the account used to register the app and open a case to Developer Support. If a seller account was used please use https://developer.amazonservices.com/support. In the case please include the full request and response attached as a .txt case and the app id. This will help us to troubleshoot the response for discrepencies. 

Thanks,
Críona
Selling Partner API Developer Support
