### ISSUE TITLE
UPLOAD_VAT_INVOICE

### ISSUE THREAD

**Issue by pengjinfei520** [amzn/selling-partner-api-docs#2425]
Feed Processing Summary:	
Number of records processed		1	
Number of records successful		0
original-record-number	sku	error-code	error-type	error-message1		
79525	Error	Amazon will generate invoice for shipmentId N/A, orderId N/A

**Comment by CrionaAm** [comment]
Hello @pengjinfei520 

It sounds like you are getting an input error when trying to upload an Invoice feed. 

In order to correctly resolve this issue, please open a support case (https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end. Please make sure to include the feed ID, and if possible both the full request and response attached to the new case for our Develope rSupport team to review. 

Thanks,
Críona
Selling Partner API Developer Support

**Comment by pengjinfei520** [comment]
Call&nbsp;UPLOAD_VAT_INVOICE&nbsp;&nbsp;Return information：


Feed Processing Summary:	
Number of records processed		1	
Number of records successful		0
original-record-number	sku	error-code	error-type	error-message1		
79525	Error	Amazon will generate invoice for shipmentId N/A, orderId N/A





This Is My Feed ID :&nbsp;79504019191，Please check the reason！Thank you!


彭进飞
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "amzn/selling-partner-api-docs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月15日(星期五) 晚上8:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [amzn/selling-partner-api-docs] UPLOAD_VAT_INVOICE (Issue #2425)





 
Hello @pengjinfei520
 
It sounds like you are getting an input error when trying to upload an Invoice feed.
 
In order to correctly resolve this issue, please open a support case (https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end. Please make sure to include the feed ID, and if possible both the full request and response attached to the new case for our Develope rSupport team to review.
 
Thanks,
 Críona
 Selling Partner API Developer Support
