### ISSUE TITLE
[Question] Can Vendor Central account create FEED with SP-API ?

### ISSUE THREAD

**Issue by ThanhLuan0932** [amzn/selling-partner-api-docs#2427]
I have a question, as a Vendor Central user, can I use the API https://developer-docs.amazon.com/sp-api/docs/feeds-api-v2021-06-30-reference to bulk products on my Vendor central site (https://vendorcentral.amazon.com/hz/vendor/members/products/mycatalog) ?
 
I tried to use that APIs but was denied access ["message": "Access to requested resource is denied.", "code": "Unauthorized"]. 
![errorAuthen](https://user-images.githubusercontent.com/33895995/179150283-55ee02b5-5650-45a3-b08f-ad02babe225d.PNG)

I'm use C# language, only those 2 APIs below works fine in my case:
https://developer-docs.amazon.com/sp-api/docs/vendor-retail-procurement-apis-v1-use-case-guide
https://developer-docs.amazon.com/sp-api/docs/selling-partner-api-for-a-content-management

Please advise me with this problem. Thanks !

**Comment by chapmanjw** [comment]
The `JSON_LISTINGS_FEED` feed type is the only product-related feed that supports vendors with the Feeds API: https://developer-docs.amazon.com/sp-api/docs/feed-type-values.

Schema for the feed type: https://developer-docs.amazon.com/sp-api/docs/listings-feed-schema-v2

Related Product Type Definitions API for retrieving the schemas for the attributes content to put within the feed messages: https://developer-docs.amazon.com/sp-api/docs/product-type-api-use-case-guide

Additionally, the Listings Items API allows for vendor product submissions one at a time rather than uploading documents to the Feeds API: https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-use-case-guide

**Comment by ThanhLuan0932** [comment]
Hi @chapmanjw, thank you for your attention for above case. 
Now, I'm using API: `/listings/2021-08-01/items/{sellerId}/{sku}` with GET method (https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-reference) and I have this info
![image](https://user-images.githubusercontent.com/33895995/179891287-d743ce5b-0816-4964-834d-8b1ac1ae4eb6.png)
and then I use API:` /listings/2021-08-01/items/{sellerId}/{sku}` with POST method  to put another Listings Item, but I don't know how to get `value`, it seems to be ID of Product Category, please help me explain what it is and tell me which API to get it.
Thanks !

**Comment by chapmanjw** [comment]
@ThanhLuan0932 The Product Type Definitions API provides the schemas that include the valid values for enumerated fields, including their display names: https://developer-docs.amazon.com/sp-api/docs/product-type-api-use-case-guide. The value of product category is a number, whereas the textual representation is a display name.

Additionally, you can use the Catalog Items API to retrieve the reconciled ASIN data (rather than the listing/SKU data). The `vendorDetails` includes both the value and display name for product category in the 2022-04-01 version of the API.

**Comment by ThanhLuan0932** [comment]
@chapmanjw, thanks for your support, and now, I getting response:
`  {
    "sku": "HH-TEST-001",
    "status": "ACCEPTED",
    "submissionId": "396932b5e2e945049cbdd67f278a24a9",
    "issues": []
}`
but I can't find this item on `https://vendorcentral.amazon.com/`, can you help me this case. Thanks !

**Comment by chapmanjw** [comment]
@ThanhLuan0932 To investigate your submission further, please contact developer support: https://developer.amazonservices.com/support. They will be able to open a support ticket with the team that can investigate this further. Thanks!
