### ISSUE TITLE
[BUG] Can't get any information from the buyer

### ISSUE THREAD

**Issue by namlv94** [amzn/selling-partner-api-docs#2438]
**If you need help troubleshooting a problem with Selling Partner APIs, please [open a support case](https://developer.amazonservices.com/support). Issues are for reporting documentation bugs and enhancements only.**

**Describe the bug**
can't get any buyer information eg BuyerInfo, BuyerAddress

**URL of the content on GitHub**
[Please provide the GitHub URL for the documentation where you see the bug.](https://developer-docs.amazon.com/sp-api/docs/orders-api-v0-reference#buyerinfo)

I don't know what else I need to get this information

**Comment by sungolivia** [comment]
hey @namlv94  have you read through this? https://developer-docs.amazon.com/sp-api/docs/tokens-api-use-case-guide
those info are considered PII so you would need to apply for restricted roles via developer profile in order to access them!
Check out the restricted roles section: https://developer-docs.amazon.com/sp-api/docs/roles-in-the-selling-partner-api#role-definitions
