### ISSUE TITLE
Changing prices of the same item has different time delay (2 sellers account)

### ISSUE THREAD

**Issue by jakobowsky** [amzn/selling-partner-api-docs#2451]
Hi!

I am building repricing software for Amazon Marketplace
Right now I am using 2 different seller accounts and I am repricing the same item (they are both selling the same item).
For some reason, on my 1st account, it takes ~ 15-20mins to change the price on the item. However, on the 2nd account, it takes much more, usually ~ 40mins. They both are set up separately, having 2 different private apps and 2 different AWS accounts.

On the other hand, when I want to change the price on this item using 3rd party repricing software, there is no issue.

Do you know why is this happening and what would be the solution?

**Comment by LindaNC** [comment]
Hello @[jakobowsky](https://github.com/jakobowsky),

In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end.

Thanks,
Linda 
Selling Partner API Developer Support
