### ISSUE TITLE
GetReport - You cannot get products based on multiple marketplaceId's

### ISSUE THREAD

**Issue by Muschke** [amzn/selling-partner-api-docs#2457]
So instead of a simple getAllProducts-request, in the sp-api we have to perform:
- post getReportId
- Get getReport
- Get getReportDocument

getReportId is based marketplaceId parameters. If you do not pas in at least one, it doesn't work. Our client has 9 marketplaces. So we pass in alle id's. What do we get back? zero products in the eventual report. If we pass it in on by one, we get double products, we sometimes get over our burst rate,.. we'd prefer it in 1 request.

How can we get all the products over all marketplaces? What are we misunderstading about these requests?

**Comment by LindaNC** [comment]
Hello @[Muschke](https://github.com/Muschke),

In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end.

Thanks,
Linda
Selling Partner API Developer Support

**Comment by Muschke** [comment]
Hello Linda 

We have opened a support case more than a week ago. We don't answers, while we think it is  a simple question. That is why we use this forum to try and get reaction. Maybe you should mark it as unresolved instead.
