### ISSUE TITLE
FBA Customer return data has multiple return dates for one return

### ISSUE THREAD

**Issue by jayallu** [amzn/selling-partner-api-docs#2459]
### Discussed in https://github.com/amzn/selling-partner-api-docs/discussions/2458

<div type='discussions-op-text'>

<sup>Originally posted by **jayallu** July 26, 2022</sup>
Recent returned data fetched through API for a **_FBA Customer return report_** has **_more than one return date._**
The pulls were made with different date parameters.
Can someone help as we are unable to de dupe due to this and are reporting exaggerated returns

![FBA_Returns](https://user-images.githubusercontent.com/91160490/181049882-f040d3fc-e28f-404d-90bf-76d22eef75ec.jpg)
</div>

**Comment by LindaNC** [comment]
Hello @[jayallu](https://github.com/jayallu),

In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end.

Thanks,
Linda
Selling Partner API Developer Support
