### ISSUE TITLE
[BUG] Documentation of "orders-api-v0-reference" HTTP status codes of getOrder are not correct

### ISSUE THREAD

**Issue by Cacodaimon** [amzn/selling-partner-api-docs#2460]
Operation: getOrder
Endpoint: **GET /orders/v0/orders/{orderId}**

I think this is rather a bug in the API, but the documentation points out that a HTTP 404 status code gets used in case "The resource specified does not exist."

But when fetching an order with an invalid order ID e.g. `api.getOrderWithHttpInfo("123-1234567-1234567")`  the HTTP status code is **200** with a response body like this one:

```json
{"payload":{}}
```

I expect a REST API to properly implement the common HTTP status codes and return a 400+ error code, to handle errors correctly and avoid strange assumptions on application side like `skip row if order_id is null…`.

**Comment by LindaNC** [comment]
Hello @[Cacodaimon](https://github.com/Cacodaimon),

In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end.

Thanks,
Linda
Selling Partner API Developer Support
