### ISSUE TITLE
Getting empty finance response for some orders - amazon.de

### ISSUE THREAD

**Issue by Nilanth** [amzn/selling-partner-api-docs#2489]
For some shipped orders, finance data is empty. I tried with the below APIs. Is this an issue in SP API?

Marketplace: **A1PA6795UKMFR9**

```
/finances/v0/orders/{orderId}/financialEvents
/finances/v0/financialEvents
```

**Comment by LindaNC** [comment]
Hello @{[Nilanth](https://github.com/Nilanth)},

In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end.

Thanks,
Linda
Selling Partner API Developer Support
