### ISSUE TITLE
[FEATURE] Is it possible to determine which account a Disbursement (GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2) is for without parsing the file?

### ISSUE THREAD

**Issue by bjpierre** [amzn/selling-partner-api-docs#2509]
Our company sells in both the US and Canada. We'd like to keep the two seperate for marketing purposes. Calling the GetReports end point for GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2 with the United States marketplaceId (ATVPDKIKX0DER) returns every Settlement report ever, and they all have 6 marketplace Id's listed. Calling with the Canada MarketplaceId (A2EUQ1WTGCTBG2) yields the same exact results. But I'm able to look at these reports and the last ten (I didn't look any further) seem to be separated out, one report is all of our Canada Sales, one report is all of our US sales. The two are never mixed. 

Can I tell this information somehow or filter my results to only be for one or the other without downloading the report and parsing it out to see if the lines are for the US or CA?

Also, I know we're supposed to open a support case for things like this, not post here, but the three times I've tried that I've been told to refer to the documentation (twice with a link that was a copy of the link I referenced in my request) and that if the docs don't answer then to refer to third party forums. So here we are.

**Comment by tspicer** [comment]
@bjpierre , this behavior is present for other reports as well for multi-market/unified seller accounts. It seems that the API does not respect, or understand, the marketplace setting in a request. In your example, rather than returning the US settlement report for a CA request, the CA request should return NO DATA or something else. An alternative is to supply a unified REGION level report, with market identifiers. None of that exists, which makes dealing with the outputs difficult.

We wrote a help doc on the topic here https://docs.openbridge.com/en/articles/6538970-how-to-query-amazon-multi-market-accounts-with-data-duplication

**Comment by steven-so** [comment]
We have the same experience. We have to download every report to determine if it is the marketplace we want.
