### ISSUE TITLE
Regional Availability Issues for the Vendor Center Authorized Selling Partner API Application

### ISSUE THREAD

**Issue by YEE271** [amzn/selling-partner-api-docs#2514]
Excuse me, in the explanation of the official document, whether it is VC or SC authorization is regional
The official documentation explains the following
Authorization is regional, so when authorization is complete, your app will have access to seller accounts in any marketplace in North America. The same concept applies to vendors using Vendor Central.
The premise is that the same report in Germany is successfully called and there is a French site
Why can't I use the Token to call the French market ID after I authorize the VC German site to successfully obtain the German Token?
The downloaded error message is as follows
{
     "errorDetails" : "The requested marketplaceId does not match the marketplace associated with the selling partner account: A1PA6795UKMFR9. You must specify the marketplaceId that corresponds to the selling partner account."
}
Any help would be greatly appreciated. thanks.

` String vcDEToken = "********";

        ReportsApi reportsApi = GetAmazonApi.getReportsApi(AzamonVAL.REGION_EU_WAST, vcDEToken, AzamonVAL.REGION_ENDPOINT_EU);
        List<String> marketplaceIds = Arrays.asList(AzamonVAL.MARKETPLACEID_FR);

        OffsetDateTime iso_start = OffsetDateTime.parse("2022-07-03T00:00:00.000Z");
        OffsetDateTime iso_end = OffsetDateTime.parse("2022-07-09T23:59:59.000Z");

        CreateReportSpecification body = new CreateReportSpecification();
        ReportOptions reportOptions = new ReportOptions();
        reportOptions.put("reportPeriod","WEEK");
        reportOptions.put("distributorView","SOURCING");
        reportOptions.put("sellingProgram","RETAIL");
        body.setReportOptions(reportOptions);
        body.setReportType("GET_VENDOR_SALES_REPORT"); //VC销售报告
        body.setMarketplaceIds(marketplaceIds);
        body.setDataStartTime(iso_start);
        body.setDataEndTime(iso_end);`

**Comment by 468092882** [comment]
你如果使用供应商账号创建的应用程序，那么你就必须在每个国家都创建一个应用程序，然后使用对应的授权信息获取数据。

**Comment by CrionaAm** [comment]
Hello @YEE271,

The cited seller Id is only active on one single marketplace- i.e. not an entire region, just one marketplace in a region. Therefor if you attempt to call any marketplaces other than that singel marketplace the call will fail. 

If you require more detailed information in relation to this please open a support case with us directly so that we can discuss the seller account A1PA6795UKMFR9 and it's limitation in detail with you:

https://developer.amazonservices.com/support

Thank you,
Críona
Selling Partner API Developer Support
