### ISSUE TITLE
[BUG] QuotaExceeded started on 9/1/2022

### ISSUE THREAD

**Issue by fr3shn3ss** [amzn/selling-partner-api-docs#2531]
Has amazon started throttling MWS? We have a Private app and we're seeing QuotaExceeded errors today without making any changes to the code

**Comment by fr3shn3ss** [comment]
I think throttling started when I tried to change my developer account from Private to Public

**Comment by DanielaZamoraUribe** [comment]
@fr3shn3ss I am experiencing the same issue when making calls to the Catalog API, and this was not happening one week ago. Did you find any solution to your problem already?.

**Comment by fr3shn3ss** [comment]
nope! I guess they started throttling without notice. I've been switching everything to SP

**Comment by jbockler** [comment]
Which APIs do you have problems with?
For the Catalog Items API, Product Fees API and Product Pricing API there were announced changes (https://developer-docs.amazon.com/sp-api/changelog/sp-api-throttling-adjustments).

We are experiencing the QuotaExceeded error for the createReport operation since beginning of september.

**Comment by fr3shn3ss** [comment]
Oh that seems to be related to this. I wish I would've received an email!
https://developer-docs.amazon.com/sp-api/changelog/sp-api-throttling-adjustments
