### ISSUE TITLE
[BUG]  GET /products/pricing/v0/price failing on SKUs with special characters

### ISSUE THREAD

**Issue by Trimakas** [amzn/selling-partner-api-docs#2536]
Around the world the call to get prices is failing for SKUs with special characters. Even when escaped some calls are still failing.

The reason I know that it fails is that the inventory call works fine. Specifically 
GET /fba/inventory/v1/summaries works well for these skus.

These are some example skus
BL_BR_GO_JP_18,5+4 - escaped is "BL_BR_GO_JP_18%2C5%2B4"
BL_NL_GO_MO_50+5 -  escaped is "BL_NL_GO_MO_50%2B5"
BL_NL_GO_ON_40+5 - escaped is "BL_NL_GO_ON_40%2B5"

We happen to be using Ruby and `CGI.escape`

**Comment by repriceit** [comment]
We had similar issues, and found we had to URLEncode the skus, and then replace any encoded '+' characters with a space since the 'sku' in the batch operations is part of the uri.   For example (java):

String sku2 = URLEncoder.encode(sku, StandardCharsets.UTF_8.toString());
String formattedSKU = sku2.replace('+', ' ');
offerRequest.setUri("/products/pricing/v0/listings/" + formattedSKU + "/offers");

For the other non-batch pricing operations you just need to URLEncode the skus since the skus are sent as parameters and the '+' (space) is interpreted correctly.

I'm not sure why they embedded the SKU in the uri for the batch operations, but it makes it very confusing and inconsistent.

**Comment by Trimakas** [comment]
wow, thanks for responding!

**Comment by damianelder** [comment]
yeah getPricing and getCompetitivePricing not working as the SKU is in the query string.  The listing example above like some of the other Product Pricing API calls which have SKU in the "PATH" work fine once encoded.

Using ASIN is fine.  ;-). 
 support case open will keep you posted.
