### ISSUE TITLE
Invalid ASIN causes a batch SearchCatalogItems request fail

### ISSUE THREAD

**Issue by gokigoks** [amzn/selling-partner-api-docs#2543]
If a batch request for the SearchCatalogItems endpoint includes an invalid asin (ex. 20DOMINANT), it returns an error that basically disregards the rest. 

The error message we get back is only:
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Invalid \u0027asin\u0027 provided.",
      "details": ""
    }
  ]
}

This is unacceptable as SPAPI doesn't even return which ASIN is invalid IN A BATCH REQUEST along with failing the whole request. This is obviously a bug so please fix it asap. We're desperately trying to migrate before the end-of-life date and these big issues are a real stopper.

**Comment by gokigoks** [comment]
Hello, Good day. @chapmanjw is there any chance this behavior from the API could be changed?

**Comment by chapmanjw** [comment]
While the `searchCatalogItems` operation accepts some list parameters when performing a query, it is performing a single operation. It's not a "batch" call in the sense that you are passing in 20 separate requests and getting 20 separate responses. 

There are a few options to how you might build your solution with the way this API operation works:

1. You could validate the input prior to calling the API. The format of ASINs is relatively simple, here is an example regex pattern: `[0-9]{9}[0-9X]|[A-Z][A-Z0-9]{9}`. 
2. For human input where you are not sure if the input is a valid ASIN, you could use the `keyword`-based search instead where we will detect valid ASINs or product identifiers to lookup by and fallback to an actual keyword search when not a valid ASIN or product identifier.
3. Alternatively, for human input where you want the specific input validation provided by the API, calling one at a time instead of performing a multi-identifier lookup.

**Comment by gokigoks** [comment]
@chapmanjw Thank you for your response. That said, if one invalid ASIN is going to fail the whole request, the least you could do is return the culprit. I was hoping that's a given for batch requests aside from it not failing due to 1 invalid item. 

1. Unfortunately, this regex pattern doesn't work 100%. Can you please share a standard validation for ASINs that may be similar to how Amazon validates it for the community?
2. It's a shame as it defeats the purpose of searching the catalog and being confident you are getting a 1-1 identifier to result ratio from the response. 
3. Same as #2 which will also greatly hurt performance (and more throttle). This is really out of question given the fact that we're having trouble as were getting a lot of connection timeouts. 

I apologize in advance if this was rude. We're just hectic as heck due to the tight schedule and the deadline looming closer (which might be true for you guys as well). That said, I once again hope you could do something to suppress the error (or something else?). Thank you for your time. Cheers.

**Comment by gokigoks** [comment]
Not sure if this helps anyone, but this is a regex pattern that currently works best for me: ^(B[\dA-Z]{9}|\d{9}(X|\d))$
