### ISSUE TITLE
Selling account temporarily deactivated

### ISSUE THREAD

**Issue by bpyzikvc** [amzn/selling-partner-api-docs#2560]
I recently got an email that my account was temporarily inactivated and I need to go through a process to get it back up. The card on the account has not expired so I'm not sure what has caused this. Here is the text from the email.\

"Hello,

We have temporarily placed your selling account in an inactive status.

To reactivate your selling account, verify your account and update your credit card information in Seller Central.

To update your credit card information, on the “Account Info” page, go to “Payment Information”, select “Charge Methods”, and add your credit card details."

**Comment by sungolivia** [comment]
I would suggest emailing back on what to do about it unless it's from no-reply email.
Otherwise, I would suggest checking with the dev support team to take a look at your account since it is related to your account specifically. They should be able to direct it to who can help as well!
https://developer.amazonservices.com/support
