### ISSUE TITLE
[BUG] [SP-API] [Issue] Cannot create RDT

### ISSUE THREAD

**Issue by NA-Dev** [amzn/selling-partner-api-docs#2603]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type
/tokens/2021-03-01/restrictedDataToken
/vendor/directFulfillment/orders/v1/purchaseOrders

## Expected Behavior
I have a Vendor app and want to fetch DTC orders. So I am trying to create an RDT to fetch Vendor Direct Fulfillment orders. I have checked the RDT box in my App Registration to allow this. Then I created a new refresh token for the app. I expected to be good to go to fetch the RDS token via a request properly signed. 

## Current Behavior
The response from the token request is always status 400 with message "Application do not have access to some or all requested resource" or "Application does not have access to one or more requested data elements: [buyerInfo, buyerTaxInformation, shippingAddress]".

The access tokens and request signing are all good, no issues there. Is there just some long time delay in gaining access once I add the checkbox in the app registration?

## Context/Screenshots

My request body looks like this
{
  "restrictedResources": [
    {
      "method": "GET",
      "path": "/vendor/directFulfillment/orders/v1/purchaseOrders",
      "dataElements": ["buyerInfo","shippingAddress","buyerTaxInformation"]
    }
  ],
  "targetApplication": "{{appID}}"
}

## Your Environment
Postman with specs imported from the documentation

**Comment by NA-Dev** [comment]
Ahh, if I make the path  "path": "purchaseOrders" instead of "path": "/vendor/directFulfillment/orders/v1/purchaseOrders" it works. Maybe the documentation should be more clear on this.

**Comment by NA-Dev** [comment]
I take it back, I got a token with that path, but it was not valid when making the API request to fetch orders. Response was "The access token you provided is revoked, malformed or invalid."

**Comment by rugved1991** [comment]
Hi @NA-Dev,

Please check your developer profile and confirm if you have requested "Direct-To-Consumer Shipping" role. If you do not have it yet, please request this role so that you can receive DirectFulfillment Purchase Orders through the API. 
https://developer-docs.amazon.com/sp-api/docs/registering-as-a-developer

Once the role is approved on your developer profile, you need to enable it on your application config. You will have to reauthorize once the role is added to the app so that the newly generated token has access to the DirectFulfillment APIs.
The option you are selecting on the app config currently is for delegating restricted data to a third party application. If you are not delegating access to another application, you should not be selecting this option on the configuration.

Best,
Rugved
Solutions Architect, SP API
