### ISSUE TITLE
[BUG][SP-API] Reports API is not working as intended to documentations.

### ISSUE THREAD

**Issue by DAMACANER** [amzn/selling-partner-api-docs#2721]
`{"reportType":"GET_MERCHANTS_LISTINGS_FYP_REPORT","marketplaceIds":"[ATVPDKIKX0DER]"}`

When I send this body data to /reports/2021-06-30/reports **WITHOUT NO PARAMETERS BECAUSE THIS IS WHAT YOU DOCUMENT** , I get

`{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "One or more required parameters missing",
      "details": "marketplaceIds;"
    }
  ]
}
`

but according to documentation only required thing is body data.
![image](https://user-images.githubusercontent.com/92731060/201469826-52c24ee1-fb66-4144-ab72-66b2a4e14df0.png)

See also [#1349 ](https://github.com/amzn/selling-partner-api-docs/issues/1349)

[#235](https://github.com/amzn/selling-partner-api-docs/issues/235)

**Comment by canercetin-randomguy** [comment]
Also see [#2195](https://github.com/amzn/selling-partner-api-docs/issues/2195)

**Comment by canercetin-randomguy** [comment]
![image](https://user-images.githubusercontent.com/92731060/201470333-7a1d14b6-a438-414f-90fb-53e7fc51bfb3.png)

don't rely on AWS or SP-API documentation at all, in the end, you will always fix your problem at the stack overflow or issues tab over here. congrats on making the worst documentation work for developers.

See [#2155](https://github.com/amzn/selling-partner-api-docs/issues/2155), he couldnt make it because content-type was never documented there.

See [#1681](https://github.com/amzn/selling-partner-api-docs/issues/1681), where in the world "encode the params in the url path" is documented in SP-API? Also it doesnt work.

See [#1246](https://github.com/amzn/selling-partner-api-docs/issues/1246), that dude couldnt even solve the problem because there were no details on what was wrong, so future readers cant also figure out what was wrong and fix our problems inspired by that.

you. are. worst. api. developers. ever. ever.

**Comment by canercetin-randomguy** [comment]
See also [#2039](https://github.com/amzn/selling-partner-api-docs/issues/2039)

I fixed my issue with sending

`"marketplaceIds":["ATVPDKIKX0DER"]`

instead of 

`"marketplaceIds":ATVPDKIKX0DER`

So what, send the report ID back to amazon servers? Hell nah fella.

![image](https://user-images.githubusercontent.com/92731060/201512661-efee56ef-4e51-42a1-ba58-cde9cfda50af.png)

It seems like 

` {"reportId":"500XXXXX"}`

needs to be combinated with something as it doest accept it and **it isnt clearly stated in documentation again,** GOD, FUCK ME.

**Comment by canercetin-randomguy** [comment]
![image](https://user-images.githubusercontent.com/92731060/201512740-9f94e8c0-5ed9-448b-a39f-2a0e56331688.png)

What does this even mean? WHAT? HOW?

**Comment by stefnats** [comment]
Seems like you are confusing reportId and reportDocumentId. ReportId is usually a number and reportDocumentId is a longer string.
When you create (request) a report you will receive a reportId. 
When this report is finished, reports api will return reportDocumentId alongside the reportId.
With reportDocumentId you can request the download url for the report.

I hope this clarifies it a bit better.

**Comment by stefnats** [comment]
> Access to requested resource is denied

is this error happening when you call the URL that you obtained the day before?
So: Did you call getReportDocument, saved the url and download the next day?

In that case i would think that this is caused, because the URL that was returned *might* be available only for a certain short time period. If you want a new link you have to call it again.
Again, this is just a guess.
