### ISSUE TITLE
Retrieve reports scheduled in the Seller Central -> Order Reports

### ISSUE THREAD

**Issue by easy-easy** [amzn/selling-partner-api-docs#276]
Hello,

how can I retrieve the order reports that are scheduled in the seller central (See screenshot).

![amazon-schedule](https://user-images.githubusercontent.com/11597226/103975561-b9313c80-5174-11eb-8fbc-48cefacdeab7.png)

Is there an equivalent to _GET_FLAT_FILE_ORDERS_DATA_ from MWS?

Regards.

**Comment by webinsect-rishabh** [comment]
@easy-easy Have you got any idea about this ?

**Comment by ulandj** [comment]
@easy-easy @webinsect-rishabh 
> Is there an equivalent to GET_FLAT_FILE_ORDERS_DATA from MWS?
have you found a solution for this?

**Comment by ulandj** [comment]
@ShivikaK @rugved1991 
regarding [this](https://github.com/amzn/selling-partner-api-docs/issues/563) announcement:
Do I understand correctly that MWS API `_GET_FLAT_FILE_ORDERS_DATA_` report type is deprecated and it is not recommended to use it in the SP API from the following part of the announcement?
```
All Amazon MWS Reports will be deprecated as previously mentioned. Accessing the correlating report types for these Amazon
MWS reports in SP-API will require the use of the new access protocol via the Tokens API and Restricted Data Token (RDT):
_GET_AMAZON_FULFILLED_SHIPMENTS_DATA_
_GET_FLAT_FILE_ACTIONABLE_ORDER_DATA_
_GET_FLAT_FILE_ALL_ORDERS_DATA_BY_LAST_UPDATE_
_GET_FLAT_FILE_ALL_ORDERS_DATA_BY_ORDER_DATE_
_GET_FLAT_FILE_ORDERS_DATA_
_GET_FLAT_FILE_VAT_INVOICE_DATA_REPORT_
_GET_GST_MTR_B2B_CUSTOM_
_GET_ORDERS_DATA_
_GET_VAT_TRANSACTION_DATA_
_GST_MTR_B2B_
_SC_VAT_TAX_REPORT_
```

Or may we use it in the SP API using the new access protocol via the Tokens API and Restricted Data Token (RDT) in order to get all orders with statuses - unshippped, shipped, pending from all regions - NA, EU, FE?

Thanks in advance!

**Comment by VishruthVB** [comment]
Hi Instead of GET_FLAT_FILE_ORDERS_DATA from mws which report I need to use in sp-api?
