### ISSUE TITLE
Getting GET_VAT_TRANSACTION_DATA without RDT Token

### ISSUE THREAD

**Issue by marfitec** [amzn/selling-partner-api-docs#2904]
Hi,

I would like to retrieve the GET_VAT_TRANSACTION_DATA report. But for this a RDT token is needed. 
What do I need to set on the developer profile to retrieve this report?
Or is there another report that I can use to retrieve outgoing invoice data (generated by Amazon)?

Greetings
Marcus

**Comment by tusbar** [comment]
Something seems wrong with these reports.

@marfitec what makes you think that a RDT is needed? They do not include PII. Requesting them now yields a 403 since jan 2023.

**Comment by marfitec** [comment]
@tusbar Thank you for the answer.
Until January 2023 I was able to retrieve the GET_VAT_TRANSACTION_DATA report without any problems. Now not anymore. I get the message "forbidden".
Why can't I request PII anymore and what does it mean I get 403?
Is there another report that can be used to get information about the A/R invoices created by Amazon?

Regards
Marcus

**Comment by evangelosdaniil** [comment]
Hello @marfitec, 

We have encountered the same issue since the 23rd of January, 2023. We haven't solved this yet, but I have found some things that might help. 

The error we are getting (forbidden) means we don't have the correct permissions to perform the API call. Amazon introduced stricter roles related to data consumption in Amazon SP. To get the VAT report using the Amazon SP APIs, according to the documentation, you need to have [Tax Invoicing (Restricted) role](https://developer-docs.amazon.com/sp-api/docs/tax-invoicing-restricted-role). If you scroll to the bottom of the page, you will see that this permission is required to get or create  `GET_VAT_TRANSACTION_DATA` reports. To update your roles, you need the Data Access section of the Amazon developer profile.  

This is not the only problem, though. @tusbar, to answer your question, the Tax Invoicing (Restricted) role is considered a restricted role containing Personally Identifiable Information (PII), which is why RDT is required. From what I understand, RDT is needed only when you get the report using the `getReport` API, so it's unnecessary when you create it using the `createReport` API.

Q: did you migrate from MWS to the SP APIs? Is your API application hybrid (i.e. can you use MWS and SP simultaneously)?

**Comment by tusbar** [comment]
@evangelosdaniil thanks for your message.

I’ve just got an answer from a support case telling me that `GET_VAT_TRANSACTION_DATA` reports now require the Tax Invoicing (Restricted) role.
It didn’t use to be the case, and it doesn’t make sense as that report does not expose any PII.

We did migrate from MWS, but the application hasn’t been hybrid for a few months.

**Comment by evangelosdaniil** [comment]
Thank you for the update, @tusbar! This is really helpful!

**Comment by sungolivia** [comment]
+1 to what @tusbar said, closing this issue as the answer was provided thanks to @tusbar!

**Comment by marfitec** [comment]
Hello all,

I have now added the Tax Accounting and Tax Transfer roles to the DeveloperAccount.

Unfortunately, I can't manage to create a restricted token for CreateReport. I don't know which dataElements I have to pass.

It doesn't work, a DocumentID is required, but I only have it after CreateReport.

{"restrictedResources":[{"method":"GET","path":"/reports/2021-06-30/reports","dataElements":[]}]}

That doesn't work either.
{
  "restrictedResources": [
    {
      }, "method": "GET",
      "path": "/reports/2021-06-30/reports",
      "dataElements": [
        "buyerInfo",
        "paymentInfo"
      ]
    }
  ]
}

Does anyone have an idea how I can now create and retrieve the GET_VAT_TRANSACTION_DATA using the RDT?

@evangelosdaniil @sungolivia
