### ISSUE TITLE
how to get SKU number for a product using ASIN ? 

### ISSUE THREAD

**Issue by arcmax1998** [amzn/selling-partner-api-docs#2930]
SP o i am working with the Amazon seller api. I have my catalog and pricing api working. I am able to retrieve the details using the ASIN values. What i need is the inventory for those products. The inventory feed required SKU number. I cant seem to find the SKU number in any of the feeds. And the inventory feed seems to only work with sku, i have tried other identifiers available in the summery but none of them work.

any help would be appreciated.

thanks

**Comment by puppsupr** [comment]
Hi @arcmax1998,

If you do a Catalog Item Get on an ASIN the identifiers contains mapped SKU for the seller, if there is one.
https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2022-04-01-reference#includeddata

Thanks and Regards,
Supriya P
Solutions Architect, Selling Partner API
[SP API Blogs](https://developer-docs.amazon.com/sp-api-blog/docs/getting-started) | [SP API YouTube Channel](https://www.youtube.com/@amazon-sp-api)

**Comment by PeterTough2** [comment]
@puppsupr 
Is there a sandbox with API credentials and list of ASIN I can use for a test, I am implementing this on Google sheet.

Here is the endpoint I am calling from Postman, I need the test header parameters

https://sellingpartnerapi-na.amazon.com//products/pricing/v0/competitivePrice?MarketplaceId=ATVPDKIKX0DER&Asins=B08V57P86Z,B0964K3MC7,B00J31YARQ

@arcmax1998 Do you care to share your request headers?

Thanks.

**Comment by widdydev** [comment]
> Hi @arcmax1998,
> 
> If you do a Catalog Item Get on an ASIN the identifiers contains mapped SKU for the seller, if there is one. https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2022-04-01-reference#includeddata
> 
> Thanks and Regards, Supriya P Solutions Architect, Selling Partner API [SP API Blogs](https://developer-docs.amazon.com/sp-api-blog/docs/getting-started) | [SP API YouTube Channel](https://www.youtube.com/@amazon-sp-api)

It seems that the catalog items API does not always return the correct identifiers in the response.
I could verify this by performing 2 search queries. 1 by ASIN and 1 by the corresponding SKU. Both gave me the same item in the response. But the SKU in the identifiers response is missing when queried by ASIN. The SKU identifier is present when querying by SKU. So apparently there is some inconsistency.

Is there a way to solve this issue?
Thanks in advance

**Comment by gusbarba** [comment]
> > Hi @arcmax1998,
> > If you do a Catalog Item Get on an ASIN the identifiers contains mapped SKU for the seller, if there is one. https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2022-04-01-reference#includeddata
> > Thanks and Regards, Supriya P Solutions Architect, Selling Partner API [SP API Blogs](https://developer-docs.amazon.com/sp-api-blog/docs/getting-started) | [SP API YouTube Channel](https://www.youtube.com/@amazon-sp-api)
> 
> It seems that the catalog items API does not always return the correct identifiers in the response. I could verify this by performing 2 search queries. 1 by ASIN and 1 by the corresponding SKU. Both gave me the same item in the response. But the SKU in the identifiers response is missing when queried by ASIN. The SKU identifier is present when querying by SKU. So apparently there is some inconsistency.
> 
> Is there a way to solve this issue? Thanks in advance

I have the same problem...

https://sellingpartnerapi-na.amazon.com/catalog/2022-04-01/items?marketplaceIds={mktplaceId}&includedData=attributes,summaries,identifiers,relationships,images,dimensions,productTypes,salesRanks&identifiersType=ASIN&identifiers={asin}

the response is

`      "identifiers": [
        {
          "marketplaceId": "{mktplaceId}",
          "identifiers": [
            {
              "identifierType": "EAN",
              "identifier": "{eanCode}"
            }
          ]
        }
      ],`

but if i use the corresponding SKU for that ASIN....

https://sellingpartnerapi-na.amazon.com/catalog/2022-04-01/items?marketplaceIds={mktplaceId}&sellerId={sellerId}&includedData=attributes,summaries,identifiers,relationships,images,dimensions,productTypes,salesRanks&identifiersType=SKU&identifiers={sku}

the response is....

`      "identifiers": [
        {
          "marketplaceId": "{mktplaceId}",
          "identifiers": [
            {
              "identifierType": "EAN",
              "identifier": "{ean}"
            },
            {
              "identifierType": "SKU",
              "identifier": "{sku}"
            }
          ]
        }
      ],`

so... maybe then the origin of the problem lies in the sellerId parameter (that is mandatory when using SKU).... SO! if i try with

https://sellingpartnerapi-na.amazon.com/catalog/2022-04-01/items?marketplaceIds={mktplaceId}&sellerId={sellerId}&includedData=attributes,summaries,identifiers,relationships,images,dimensions,productTypes,salesRanks&identifiersType=ASIN&identifiers={asin}

the response is...

`      "identifiers": [
        {
          "marketplaceId": "{mktplaceId}",
          "identifiers": [
            {
              "identifierType": "EAN",
              "identifier": "{ean}"
            }
          ]
        }
      ],`

no sku :disappointed:.... thank you amazon...

i understand that the problem lies in using the sellerId only when the identifier is SKU. and the SKU only returns when it knows which seller we are using (can't it obtain it from the token?). so when we use ASIN, it ignores the sellerId parameter and does not include the SKU in the response.

anyway, to solve the following problem...

> SP o i am working with the Amazon seller api. I have my catalog and pricing api working. I am able to retrieve the details using the ASIN values. What i need is the inventory for those products. The inventory feed required SKU number. I cant seem to find the SKU number in any of the feeds. And the inventory feed seems to only work with sku, i have tried other identifiers available in the summery but none of them work.
> 
> any help would be appreciated.
> 
> thanks

can use that: https://developer-docs.amazon.com/sp-api/docs/reports-api-v2021-06-30-reference

make a report calling https://sellingpartnerapi-na.amazon.com/reports/2021-06-30/reports (POST) with the body 
`{"reportType": "GET_MERCHANT_LISTINGS_ALL_DATA", "marketplaceIds": ["{mktplaceId}"]}`

get the report status with https://sellingpartnerapi-na.amazon.com/reports/2021-06-30/reports/{reportId} (the response of the previous request)

when its done, call https://sellingpartnerapi-na.amazon.com/reports/2021-06-30/documents/{reportDocumentId} (
this comes with the status in the response of the previous request)

this return that

`{"reportDocumentId":"{reportDocumentId}","url":"{urlOfDocument}"}`

this returns a listing with all the users products, which includes ASIN and SKU for all the products!

is this terrible? YES! once again... thank you, Amazon. :sweat_smile:... but it is a solution that may help someone.

**Comment by xEverth** [comment]
Is there a planned update for the CatalogItems to return the seller SKUs when querying by ASIN and providing the SellerId as well?

**Comment by chapmanjw** [comment]
> Is there a planned update for the CatalogItems to return the seller SKUs when querying by ASIN and providing the SellerId as well? Edit: Some marketplaces like France may not always provide asin1, so this is not a suitable method: [#580 (comment)](https://github.com/amzn/selling-partner-api-docs/issues/580#issue-853366257)

Not as part of the Catalog Items API. In a future release of the Listings Items API, a search operation will be added that allows for querying listings (SKUs) for a given list of ASINs (or other product identifiers).
