### ISSUE TITLE
New Ledger Reports GET_LEDGER_DETAIL_VIEW_DATA & GET_LEDGER_SUMMARY_VIEW_DATA - Adjustment Documentation

### ISSUE THREAD

**Issue by nrogers805** [amzn/selling-partner-api-docs#2986]
I'm looking for documentation for the reason code given for Adjustments in the new Inventory Ledger reports.

I have information for these codes for the original adjustment report but the new ledger report has introduced new codes, example new code is "G"

**Comment by sungolivia** [comment]
Hi @nrogers805 please submit your feedback for documentation via our documentation [website](https://developer-docs.amazon.com/sp-api/docs/report-type-values)!
![Screenshot 2023-03-07 at 10 25 38 AM](https://user-images.githubusercontent.com/7606170/223515441-f4f3b28f-30c8-41b6-a543-640f5aed1a73.png)

Scroll down to the bottom and fill out the feedback form!

**Comment by nrogers805** [comment]
> Hi @nrogers805 please submit your feedback for documentation via our documentation [website](https://developer-docs.amazon.com/sp-api/docs/report-type-values)! ![Screenshot 2023-03-07 at 10 25 38 AM](https://user-images.githubusercontent.com/7606170/223515441-f4f3b28f-30c8-41b6-a543-640f5aed1a73.png)
> 
> Scroll down to the bottom and fill out the feedback form!

This is an unacceptable response!

There is no description for the new adjustment code G anywhere

Why are you guys making this so difficult !!

**Comment by Xriuk** [comment]
It is really weird that half of the documentation is on the SP-API website while other can be (hardly) found on the Seller Central docs, here is the table of all the reasons: https://sellercentral.amazon.com/help/hub/reference/external/4FKT5KQWFFJ7LDN#wjz_cjc_jcb-6

<html><body>


Code | Type | Reason | Definition
-- | -- | -- | --
6 | - | Damaged at Amazon fulfillment center | A decrease to your carrier-damaged inventory level. This code is  always followed by a P code increase to your fulfillment-center-damaged  inventory level.
7 | - | Damaged at Amazon fulfillment center | A decrease to your expired inventory level. This code is always  followed by a P code increase to your fulfillment-center-damaged  inventory level.
E | - | Damaged at Amazon fulfillment center | A decrease to your sellable inventory level. This code is always  followed by a P code increase to your fulfillment-center-damaged  inventory level.
H | - | Damaged at Amazon fulfillment center | A decrease to your customer-damaged inventory level. This code is  always followed by a P code increase to your fulfillment-center-damaged  inventory level.
K | - | Damaged at Amazon fulfillment center | A decrease to your defective inventory level. This code is always  followed by a P code increase to your fulfillment-center-damaged  inventory level.
U | - | Damaged at Amazon fulfillment center | A decrease to your distributor-damaged inventory level. This code is  always followed by a P code increase to your fulfillment-center-damaged  inventory level.
D | - | Inventory disposed of | A decrease to your inventory level because inventory has been disposed of
F | + | Inventory found | An increase to your inventory level because missing inventory has been found
N | + | Inventory found | An increase to your inventory level because inventory that was  incorrectly assigned has been transferred to your account or because you  received an Amazon reimbursement
M | - | Inventory misplaced | A decrease to your inventory level because inventory is missing from a bin location in a fulfillment center
5 | - | Inventory misplaced | A decrease to your inventory level because inventory is missing from a bin location in a fulfillment center
3 | + | Product redefinition transfer in | Two products with separate identifiers (SKUs) are determined to be  the same item. One SKU will be removed from your inventory (code 4) and  added (code 3) as the other SKU.
4 | - | Product redefinition transfer out | Two products with separate identifiers (SKUs) are determined to be  the same item. One SKU will be removed from your inventory (code 4) and  added (code 3) as the other SKU.
O | - | Inventory correction | Units that have been transferred out of your account because they  were incorrectly received into your inventory or because Amazon has  reimbursed you for them
P | + | Inventory disposition change | Units of a certain disposition are added to your inventory after the  removal from a different disposition. This code always follows a code  6, 7, E, H, K, U, or Q adjustment.
Q | - | Inventory disposition change | Units of a certain disposition are removed from your inventory and  then added back to your inventory as a different disposition. This code  is always followed by a P code adjustment.
G | - | Inventory disposed of | Inventory was removed as part of a donation to charity.


</body>
</html>

**Comment by johnkw** [comment]
Please reopen this github bug to make it easier to find the answer for this documentation failure.
