### ISSUE TITLE
Create Feed Invalid Input

### ISSUE THREAD

**Issue by bpyzikvc** [amzn/selling-partner-api-docs#2993]
I am running into an intermittent issue for some users where the CreateFeed API for POST_ORDER_FULFILLMENT_DATA. The response is vague with Invalid input. The applications works for most users/shipments even when the input looks identical, however not clear on how to fix the ones that fail. Below are the relevant feed process inputs and outputs. Please advise

CreateFeed API URL:
https://sellingpartnerapi-na.amazon.com/feeds/2021-06-30/feeds

Feed document:
`<?xml version='1.0' encoding='UTF-8'?>
<AmazonEnvelope>
    <Header>
        <DocumentVersion>1.0</DocumentVersion>
        <MerchantIdentifier>XXXXXXXXX</MerchantIdentifier>
    </Header>
    <MessageType>OrderFulfillment</MessageType>
    <Message>
        <MessageID>1</MessageID>
        <OrderFulfillment>
            <AmazonOrderID>XXX-XXXXXXX-XXXXXXX</AmazonOrderID>
            <FulfillmentDate>2023-02-27T21:19:43</FulfillmentDate>
            <FulfillmentData>
                <CarrierCode>UPS</CarrierCode>
                <ShippingMethod>2nd Day Air</ShippingMethod>
                <ShipperTrackingNumber>1ZXXXXXXXXXXXXXXXX</ShipperTrackingNumber>
            </FulfillmentData>
        </OrderFulfillment>
    </Message>
</AmazonEnvelope>`

CreateFeed API Input (Edit: updated to array):
`{
    "feedType": "POST_ORDER_FULFILLMENT_DATA",
    "marketplaceIds": ["ATVPDKIKX0DER"],
    "inputFeedDocumentId": "XXXXXXXXXXXXX"
}`

CreateFeed API Output:
`{
    "errors": [
        {
            "code": "InvalidInput",
            "message": "Invalid request parameters",
            "details": ""
        }
    ]
}`

CC: @sungolivia

**Comment by rugved1991** [comment]
Hi @bpyzikvc,

Thanks for sharing the request response details. The request body you are sending is not formatted correctly. 
Please use this example for reference: https://developer-docs.amazon.com/sp-api/docs/feeds-api-v2021-06-30-use-case-guide#request-example-1

the marketplaceIds attribute accepts an array. Please make the change and try again. If you are still seeing the same issue, I would recommend you to open a developer support case for further investigation.
I hope this information helps.
Have a great day!

Best,
Rugved
Solutions Architect, SP API

**Comment by bpyzikvc** [comment]
@rugved1991  Yes that's my fault, we actually did send it as an array and I input it here incorrectly. I guess I'll have to do that, thanks

**Comment by YueXiaolong** [comment]
> `{ "errors": [ { "code": "InvalidInput", "message": "Invalid request parameters", "details": "" } ] }`
However, the issue is caused by the inactive account issue and the seller needs to check their account status in this marketplace
https://developer-docs.amazon.com/sp-api-blog/docs/ensuring-healthy-seller-account-status#receiving-an-api-error

The createFeed operation can only be completed successfully if the relevant seller account is fully active. If the account is currently dormant, this is usually because the account does not receive orders regularly and the dormant account needs to be reactivated: Please have the owner log in and re-enter manually Credit card details, the account will come out of hibernation within 48 hours.

If you encounter similar problems, you can verify the above solution and give me feedback if it works.
