### ISSUE TITLE
"salesRanks" does not return the BSR of the root category

### ISSUE THREAD

**Issue by hamduc7** [amzn/selling-partner-api-docs#3012]
Dear Amazon,

Currently then "salesRanks" node only does not return the root BSR, it only returns children salesrank

https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2022-04-01-reference#getcatalogitem

For example, the ASIN **B07G39GXL5**. This is what we see on Amazon product page:
Best Sellers Rank: #25,790 in Beauty & Personal Care (See Top 100 in Beauty & Personal Care)
#626 in Nail Polish
#803 in Climate Pledge Friendly: Beauty
 
This is what returned by the API:
`"salesRanks": [
                {
                    "marketplaceId": "ATVPDKIKX0DER",
                    "classificationRanks": [
                        {
                            "classificationId": "11059321",
                            "title": "Nail Polish",
                            "link": "https://www.amazon.com/gp/bestsellers/beauty/11059321",
                            "rank": 626
                        },
                        {
                            "classificationId": "21377129011",
                            "title": "Climate Pledge Friendly: Beauty",
                            "link": "https://www.amazon.com/gp/bestsellers/climate-pledge/21377129011",
                            "rank": 803
                        }
                    ],
                    "displayGroupRanks": [
                        {
                            "websiteDisplayGroup": "climate_product_display_on_website",
                            "title": "Climate Pledge Friendly",
                            "link": "https://www.amazon.com/gp/bestsellers/climate-pledge",
                            "rank": 4346
                        }
                    ]
                }
            ],`

So is there a way we can get the BSR of the root. In this case, I would like to get 25,790 in Beauty & Personal Care

Thank you

**Comment by txphi592** [comment]
We have seen this same thing. 

ISSUE-  Some main category Sales Ranks are displayed correctly on Amazon website product page but not reported by searchCatalogItems API.  We are an app developer with thousands of Amazon seller customers and this issue is creating problems for us and our customers. 

We started a case for this a few months ago and the Amazon rep responses are really frustrating/clueless. (CASE ID 11811268941) 

Here is the latest response where Amazon closed the case-

"The backend team have confirmed that not all sales ranking information displayed on the product details page is returned via API. They have confirmed that the data which is being returned is consistent with the backend resource which the API queries. Additional sales ranking information may be gathered from other resources and presented on the product detail page, but they are not factored into the API query. While this may lead to some information being omitted, I have received confirmation that this operation is working as intended, and returning the data it queries from the backend resources it works with."

@chapmanjw

**Comment by kairav646** [comment]
@txphi592 @hamduc7 @prashanthseshadri @chapmanjw I am facing the same issue, did you guys get any solution?

**Comment by txphi592** [comment]
Nope. I have tried with support, with an Amazon project manager that supports us, on this board, nada. They either misunderstand the issue completely or they don't care.

**Comment by burhan-sancakli** [comment]
Is there any updates to this problem?
