### ISSUE TITLE
[BUG] [SP-API] [Issue] ApiError : Authorization : Client Authentication is Failed

### ISSUE THREAD

**Issue by RiyaSathavaraBISTA** [amzn/selling-partner-api-docs#3030]
## I'm submitting a...
Orders_Instance = Orders(credentials =credentials, marketplace=Marketplaces.US, account='MY_ACCOUNT_NUMBER', version='beta')
# requesting orders
result = Orders_Instance.get_orders(CreatedAfter=date.isoformat(date.today() - timedelta(days=1)),MaxResultsPerPage=1)

Python Library: https://github.com/saleweaver/python-amazon-sp-api

## Expected Behavior
We have tried to Authorize client Applications and shared authorize links with clients we had clicked on Authorize button and we are also able to see our client applications.

Using auth/02/token we can able to get the refresh token and using that refresh token we can access our client Orders data

## Current Behavior
Authorize is Completed 
But when we try to generate a refresh token then faced an error from the Library
Right now, we have directly taken a Refresh token from the client seller account directly but still, we are trying to get_ORders then again raising the error like ('invalid_client', 'Client authentication failed', 401)

**Comment by ritikacd** [comment]
Hi @RiyaSathavaraBISTA,

Thanks for reaching out. 

As of February 6, 2023, you were required to rotate your Login With Amazon (LWA) credentials (client secrets) for all applications every 180 days. After rotating the credentials, if you continue to use the old credentials instead of the new credentials, your Request a Login with Amazon access token will result in the "Client authentication failed" error message. Using the new LWA credentials should resolve the issue. I would also recommend taking a look at this documentation page:   https://developer-docs.amazon.com/sp-api/docs/rotating-your-apps-lwa-credentials

Thanks,
Ritika
Solutions Architect, SP-API
