### ISSUE TITLE
Error: Please verify if you have correct Vendor Group Rights

### ISSUE THREAD

**Issue by moltar** [amzn/selling-partner-api-docs#3106]
Could you pleae shed some light as to what this error means and how to mitigate it?

> Error in report request: Report requested with invalid user inputs. Please verify if you have correct Vendor Group Rights and/or required permissions to request this report.

Thanks!

**Comment by puppsupr** [comment]
Hi moltar,

Can you please provide the API request details ?

 Thanks and Regards,
Supriya P
Solutions Architect, Selling Partner API
[SP API Blogs](https://developer-docs.amazon.com/sp-api-blog/docs/getting-started) | [SP API YouTube Channel](https://www.youtube.com/@amazon-sp-api)

**Comment by stthsuntec** [comment]
Hello,
i have the same Problem while requesting 
"GET_VENDOR_NET_PURE_PRODUCT_MARGIN_REPORT" and "GET_VENDOR_FORECASTING_REPORT"

`response = Reports(credentials=client_config, marketplace=Marketplaces.DE).create_report(
            reportType="GET_VENDOR_FORECASTING_REPORT",
            reportOptions={
            "sellingProgram":"RETAIL",
            },
        ).payload`
this is my create_report request.
after that i request the get_report with the fetched ID and then I download the get_report_document response.

the .json file says

> {
  "errorDetails" : "Error in report request: Report requested with invalid user inputs. Please verify if you have correct Vendor Group Rights and/or required permissions to request this report."
} 

I think I have all the necessary rights, because I can succefully request the vendor inventory and sales reports.

Any help would be highly apreciated!

**Comment by moltar** [comment]
> Hi moltar,
> 
> Can you please provide the API request details ?

```http
X-Amzn-Requestid: 53a65f6b-447c-4f3f-b801-cf68ad98819e
```

```json
{
    "reportDocumentId": "amzn1.spdoc.1.4.eu.1c9acaf6-7daa-42d9-8d5b-53cf196206d3.TWLB8UH1ZE8YE.75300"
}
```

**Comment by moltar** [comment]
Case Log ID: 12738895741

**Comment by artgregorian** [comment]
Was this resolved?

**Comment by jakubriegel** [comment]
Any updates here?
@puppsupr @moltar
