### ISSUE TITLE
Which time zone to use for date boundaries for the vendor retail analytics reports?

### ISSUE THREAD

**Issue by moltar** [amzn/selling-partner-api-docs#3107]
Does it matter which time zone is used for the `dataStartTime` and `dataEndTime` values?

Source: https://developer-docs.amazon.com/sp-api/docs/report-type-values#vendor-retail-analytics-reports

> Requests must include the reportPeriod, distributorView, and sellingProgram properties. Use the dataStartTime and dataEndTime parameters to specify the date boundaries for the report. The dataStartTime and dataEndTime values must correspond to valid first and last days in the specified reportPeriod. For example, dataStartTime must be a Sunday and dataEndTime must be a Saturday when reportPeriod=WEEK .

Thanks!

**Comment by puppsupr** [comment]
Hi @moltar,

The SLA for weekly reporting periods (i.e. Saturday datasets) is EOD Monday, 48 hours after close of period. The SLA for non-Saturday daily reporting periods is 72 hours after close of period.  All the timezones are in PST.

Thanks and Regards,
Supriya P
Solutions Architect, Selling Partner API
[SP API Blogs](https://developer-docs.amazon.com/sp-api-blog/docs/getting-started) | [SP API YouTube Channel](https://www.youtube.com/@amazon-sp-api)

**Comment by puppsupr** [comment]
Hi @moltar,

Since ARA only goes by days, we don't use the timestamp beyond the day. The rest (hour:min:second) is ignored. so timezone ends up not mattering much at all.

Here is the schemas link : https://github.com/amzn/selling-partner-api-models/tree/main/schemas/reports

Thanks and Regards,
Supriya P
Solutions Architect, Selling Partner API
[SP API Blogs](https://developer-docs.amazon.com/sp-api-blog/docs/getting-started) | [SP API YouTube Channel](https://www.youtube.com/@amazon-sp-api)

**Comment by moltar** [comment]
> we don't use the timestamp beyond the day. The rest (hour:min:second) is ignored. so timezone ends up not mattering much at all.

Perfect, thanks! That also confirms my thinking :)
