### ISSUE TITLE
[BUG] [SP-API] [Issue] /catalog/2022-04-01/items get 403 Unauthorized but no problems when call /orders/v0/orders

### ISSUE THREAD

**Issue by hlouis** [amzn/selling-partner-api-docs#3134]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

In the sandbox environment, I was able to successfully call /orders/v0/orders to retrieve orders, but when calling APIs related to products, I received an error message indicating that access was denied.

`/catalog/2022-04-01/items`
```json
{
  "errors": [
    {
      "code": "Unauthorized",
      "message": "Access to requested resource is denied.",
      "details": ""
    }
  ]
}
```

## SP-API Name and Version or Report/Feed Type
`/catalog/2022-04-01/items`

## Expected Behavior

Successfully call API `/catalog/2022-04-01/items`.

## Current Behavior

Always give 403 error.

## Context/Screenshots

- Our SP-APP id is: `amzn1.sp.solution.f6fc38c7-8bfe-4ef2-a70c-af72dd49ef21`
- Sandbox API prefix is: `https://sandbox.sellingpartnerapi-eu.amazon.com`
- Region is: eu-west-1

"I have checked and confirmed that the testing app has the role of Product Listing and Pricing."

**Comment by rugved1991** [comment]
Hi @hlouis,

Please open a developer support case to troubleshoot the cause of the 403. You can use one of these links to open a developer support case:
Developer Support EU: https://developer.amazonservices.co.uk/support
Developer Support NA: https://developer.amazonservices.com/support
Developer Support APAC: https://developer.amazonservices.com.au/support

Please make sure you are adding the complete request and response along with headers in the support case so that the team can investigate further. I would also recommend to take a look at this [documentation page](https://developer-docs.amazon.com/sp-api-blog/docs/troubleshooting-selling-partner-api-authorization-errors#access-to-requested-resource-is-denied) to make sure you have confirmed its not due to one of the documented reasons.

Best,
Rugved
Solutions Architect, SP API
