### ISSUE TITLE
Drop in keyword count of API based monthly Search Term Report since November 2022

### ISSUE THREAD

**Issue by Adam2022Lever** [amzn/selling-partner-api-docs#3145]
We have been noticing that the Search Terms report volume has been drastically falling since November 2022. Specifically, there has been drastic drop in the April month's keyword count for all markets except USA. Requesting @krithic15 @puppsupr to help us with the reason behind this drop. We had raised it as a case on Amazon Vendor Central however, we didn't get any response on this.

**Comment by krithic15** [comment]
Hello @Adam2022Lever,

We have updated our click threshold to show the highest quality data and reduce the number of search terms with the lowest customer engagement. Please let us know if there are any other concerns. As for the support case, please make sure you are opening the case under 'API Support' so that it is routed to the appropriate team.

Best,
Krithi
Solutions Architect, SP API
