### ISSUE TITLE
[BUG] [SP-API] Receiving all automatically generated reports always 10 TIMES at once using Notifications API and SQS Queue

### ISSUE THREAD

**Issue by paulo2703** [amzn/selling-partner-api-docs#3195]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior
We connected the SP API Notifications via a SQS queue to receive notifications when reports are finished/errored. We now experience that we receive 10 TIMES the same message for the reports e.g., "GET_XML_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL" or "GET_FBA_FULFILLMENT_CUSTOMER_RETURNS_DATA" when being finished. All of these notifications have the same reportId, so the report gets somehow pushed 10 TIMES into the queue?! 

This must obviously a bug, as we can technically only assign a single subscription for receiving reports and the messages are appearing directly in the queue.

## Current Behavior

Please see the following SQS AWS except and also our logging.
<img width="621" alt="Bildschirmfoto 2023-06-18 um 19 16 07" src="https://github.com/amzn/selling-partner-api-docs/assets/70726673/74186bc3-03e7-4c01-be4b-cc24cc56280d">
<img width="827" alt="Bildschirmfoto 2023-06-18 um 19 16 37" src="https://github.com/amzn/selling-partner-api-docs/assets/70726673/7157bb17-aafd-4495-bd20-cbb1963e05ef">

**Comment by owsiakl** [comment]
Hey @paulo2703, we had a similar problem - in our case it was duplicating the message for each requested marketplace.

Our best guess is because how MWS API was working before - you could create notification subscription for a single marketplace, but since SP-API is handling the whole region, you are "automatically" subscribed to all marketplaces in that region which causes sending multiple notifications.

For a short term solution, you can deduplicate those messages using notification id as a deduplication key.

**Comment by rodrifed** [comment]
Hi @paulo2703 and @owsiakl,

Thank you for reporting this issue, and providing a workaround.

We have taken a note of it, and will prioritize a solution accordingly. Once a change is applied, you can expect an announcement in our public documentation website: https://developer-docs.amazon.com/sp-api.

Thank you,
Federico
Selling Partner Developer Services
