### ISSUE TITLE
[BUG] [SP-API] catalog items: generic_keyword attribute removed

### ISSUE THREAD

**Issue by jimmy-ross-xapix** [amzn/selling-partner-api-docs#3205]
## I'm submitting a...

<pre><code>[X] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type
Catalog Items API v2022-04-01 
Operation: getCatalogItem

## Expected Behavior
- Until approximately last Friday 23.06, the **attributes** Item contained the **generic_keyword** field, looking like this:

   "generic_keyword": [
        {
          "language_tag": "en_US",
          "value": "keyword data abc123",
          "marketplace_id": "ATVPDKIKX0DER"
        }

## Current Behavior
- When we pulled latest product data on Friday, the generic_keyword data had been removed from the attributes item and has still been missing on the days since then

## Context/Screenshots
The generic_keyword data is critical, as it reflects the Search Terms entered by sellers for ranking on search results of Amazon. We are helping sellers add relevant search terms there to improve their performance but now cannot access the latest values that they have entered. 

## Your Environment
We are pulling this data daily on behalf sellers via our application listed on the seller central marketplace, for each asin/marketplace combination

**Comment by jimmy-ross-xapix** [comment]
i opened a case and its not a bug apparently :(

**Comment by taibaimoyu** [comment]
i asked the amazon ,and they say:
I am Stacy from the Developer Support Team.

I understand you are unable to retrieve generic_keyword trough Catalog API. 

Please note that the product team recently performed some edits and due to the generic_keyword attribute is proprietary seller-specific data it will not longer be returned by the Catalog Items API. 

Selling Partners may see the values they submitted using the Listings Items API.
i test the  Listings Items API(https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-use-case-guide), the result include generic_keyword   ,may help sombody
