### ISSUE TITLE
[BUG] [SP-API] [Issue]

### ISSUE THREAD

**Issue by Uraix** [amzn/selling-partner-api-docs#3229]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type
API Name: createReport
Version: 2021-06-30

## Expected Behavior

using createReport to request for type `GET_VAT_TRANSACTION_DATA`  should return a job status of DONE with a document id to download the report.

## Current Behavior

it returns `Error getting LWA Access Token` occasionally.  I found that history has solved this problem, but when I download the latest version, the problem persists. 

## Context/Screenshots

```
class CreateReportSpecification {
    reportOptions: class ReportOptions {
        {startTimeStr=2023-04-01}
    }
    reportType: GET_VAT_TRANSACTION_DATA
    dataStartTime: 2023-04-01T00:00Z
    dataEndTime: 2023-04-30T23:59:59Z
    marketplaceIds: [A1PA6795UKMFR9]
}
```

## Your Environment

linux

**Comment by rodrifed** [comment]
Hi @Uraix,

I kindly ask you to contact [Developer Support](https://developer.amazonservices.com/support) to report this issue, since it requires debugging on your specific developer account and request, which we can't do here.
Our support team will be able to help you troubleshoot and fix the problem.

Thank you,
Federico
Selling Partner Developer Services
