### ISSUE TITLE
Invoice path always return http 403!

### ISSUE THREAD

**Issue by jfromjefferson** [amzn/selling-partner-api-docs#3251]
I'm trying access the **/delivery/2022-07-01/invoice** and **/delivery/2022-07-01/invoice/status** but in both, always return http 403:

![image](https://github.com/amzn/selling-partner-api-docs/assets/42497861/db85ce50-9dd3-444a-86c4-b8b93a5a0f2d)

The doc says: **For the x-amz-access-token field, use the normal access token (not the RDT)**. <a href="https://pt-br-group.readme.io/amazon-portuguese/docs/dba-caso-de-uso#shipment-invoicing-api--getinvoicestatusbyorderid">Link (in portuguese)</a>

When i access the /v0/orders with the same access_token, i receive http 200: (sandbox)

![image](https://github.com/amzn/selling-partner-api-docs/assets/42497861/a5c9ac0e-c01d-4044-b35c-4f3ca56aa6d5)

Any help would be very much appreciated.

Thanks,
Jeff

**Comment by leonardonakagawa** [comment]
Hello @jfromjefferson ,

Thank you for reaching out regarding DBA API.

As the documentation says, you do not need to use the RDT token in this operation, it is used the AccessToken normally. Please, ensure that your application has the **Inventory and Order Tracking Role** in order to make this call successfully. Also know that the invoice into your body need to be encoded into Base64 has the contentMD5value into the body.


You can find details regarding the roles in [Inventory and Order Tracking Role](https://developer-docs.amazon.com/sp-api/docs/inventory-and-order-tracking-role).

If the information available in the documentation link provided above does not fully resolve your inquiry, please [open a support case](https://developer.amazonservices.com/pt-br-support) with us.

Thanks,
Leonardo Nakagawa
Selling Partner API Developer Support
