### ISSUE TITLE
SP-API Developer Profile Update : Restricted Access Request Amazon Case Help

### ISSUE THREAD

**Issue by KKBBAMZ** [amzn/selling-partner-api-docs#3308]
Hello,

We are continuing to have our restricted access request denied, after multiple submissions of the requested information. If someone could tag the respective Amazon Reps, that would be greatly appreciated.

Case ID: 13498835581

Thanks,

**Comment by jjmg1945** [comment]
Hello,

We had a private application running in a customer since few years, because with MWS Api the customer could authorize us as developers from his seller central panel, and get the authorization token to use with MWS Api.

With the new SP-API, this procedure to authorize developers does not work, and we requested the profile update to public developer, but we are waiting for several weeks, and our customer service will be impacted.

Case ID: 8952449572

Thanks

**Comment by michelexport** [comment]
Hey @KKBBAMZ  & @jjmg1945 !

I can help you for Restriced Access Request Amazon Case.
Feel free to get in touch with me at x-port.it

Thanks

**Comment by puppsupr** [comment]
Hi,
I see that the cases have been actioned. Hence closing this.

Thanks and Regards,
Supriya P
Solutions Architect, Selling Partner API
[SP API Blogs](https://developer-docs.amazon.com/sp-api-blog/docs/getting-started) | [SP API YouTube Channel](https://www.youtube.com/@amazon-sp-api)
