### ISSUE TITLE
[BUG] [SP-API] [Issue] Missing role optional list in profile

### ISSUE THREAD

**Issue by zhouyan2525** [amzn/selling-partner-api-docs#3334]
When I registered for a new app, I found that I could only choose two limited roles. Upon checking the profile, I found that only these two roles were applied for. When I updated my profile, I found that there were no more role lists to choose from

![image](https://github.com/amzn/selling-partner-api-docs/assets/60634481/0497a23b-b487-4ff9-adad-2c724dcbecb5)

**Comment by rugved1991** [comment]
Hi @zhouyan2525,

This usually happens when the developer profile is under review. Once the developer profile is approved or the role is rejected, you will be able to edit the developer profile again. Please confirm if you are able to see the roles once the review is complete. If not, you will need to open a developer support case with screenshot of the issue. If you can also add [HAR file](https://repost.aws/knowledge-center/support-case-browser-har-file) from the browser, it will help the team investigate the issue.

Best,
Rugved
Solutions Architect, SP-API
