### ISSUE TITLE
[BUG] Documentation

### ISSUE THREAD

**Issue by thesky2017** [amzn/selling-partner-api-docs#335]
hello!
When I call spapi, the following error and signature are correct. What's the reason for this?
{
  "errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "Unauthorized",
     "details": ""
    }
  ]
}

**Comment by vikingcodes** [comment]
Share your code

**Comment by ShivikaK** [comment]
Hello @thesky2017 

Thank you for raising the issue.

Please provide more details on the request you are making. 

Please feel free to open a support case with us if you'd like deeper assistance with this issue.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by thesky2017** [comment]
> Hello @thesky2017
> 
> Thank you for raising the issue.
> 
> Please provide more details on the request you are making.
> 
> Please feel free to open a support case with us if you'd like deeper assistance with this issue.
> 
> Thanks,
> Shivika Khare
> Selling Partner API Developer Support

I found the problem, security_ The token parameter is missing. I don't see this parameter in the document. The API is the generated PHP version.

thank you!

**Comment by ShivikaK** [comment]
Hello @thesky2017 

Please share your request details and IAM information.

If you are referring to the AWS STS token, please refer to below 2 links to understand how to generate temporary credentials and add it to the request -

https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#step-4-create-and-sign-your-request

https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_request.html 

Please clarify if the issue is related to a different security token.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by weiliguo15634145** [comment]
Have you found the answer , I had the same problem , And I need your help.
