### ISSUE TITLE
[BUG] [SP-API] [When a report is created using the createReport api, the transmitted reportType is A. After the reporttid is created successfully, the returned Reporttid is used to query the getReport api. reportType is not the reportType I transmitted, but another reportType.]

### ISSUE THREAD

**Issue by justinwujian** [amzn/selling-partner-api-docs#3367]
![image](https://github.com/amzn/selling-partner-api-docs/assets/65995025/62927aa7-e8f7-46e2-8855-0e7145ccb120)

When calling spapi to create a report interface, the report type passed is type A. After the report is created, use reporttid to run the get report interface to view the report. Why is the returned report type B? The details are as follows. I call spapi to create the report interface (createReport), and the reportType passed is GET_LEDGER_SUMMARY_VIEW_DATA. After the report is created successfully, I use reportId to call the report information acquisition interface (getReport) for query. In the obtained results, you can see that the reportType is not "GET_LEDGER_SUMMARY_VIEW_DATA" but "GET_XML_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL". why is that?

**Comment by justinwujian** [comment]
This question has bothered me for a long time

**Comment by leonardonakagawa** [comment]
Hi @justinwujian!

Thank you for reaching out regarding reports.

I reproduced this operation in my side, and it seems to be working right to me. In order to see if all is working well or not,

Can you please run this [Tutorial: Request a report](https://developer-docs.amazon.com/sp-api/docs/reports-api-v2021-06-30-tutorial-request-a-report) into Postman with the reportType GET_LEDGER_SUMMARY_VIEW_DATA and a date range less than 90 days?

Using the Postman to test the API will guarantee you are making the right calls and retrieving the right responses to make the Reports API call flow.

If the information available in the documentation link provided above does not fully resolve your inquiry, please [open a support case](https://developer.amazonservices.com/support) with us.

Thanks,
Leonardo Nakagawa
Solutions Architect, Selling Partner API Developer Support

**Comment by justinwujian** [comment]
Hello, I encountered this problem when requesting multiple reports at the same time. Every time I request 10 reports at the same time, I will encounter such a problem. Some of them are normal, and some of them have mismatched report types.

**Comment by justinwujian** [comment]
> Hi @justinwujian!
> 
> Thank you for reaching out regarding reports.
> 
> I reproduced this operation in my side, and it seems to be working right to me. In order to see if all is working well or not,
> 
> Can you please run this [Tutorial: Request a report](https://developer-docs.amazon.com/sp-api/docs/reports-api-v2021-06-30-tutorial-request-a-report) into Postman with the reportType GET_LEDGER_SUMMARY_VIEW_DATA and a date range less than 90 days?
> 
> Using the Postman to test the API will guarantee you are making the right calls and retrieving the right responses to make the Reports API call flow.
> 
> If the information available in the documentation link provided above does not fully resolve your inquiry, please [open a support case](https://developer.amazonservices.com/support) with us.
> 
> Thanks, Leonardo Nakagawa Solutions Architect, Selling Partner API Developer Support

Hello, I encountered this problem when requesting multiple reports at the same time. Every time I request 10 reports at the same time, I will encounter such a problem. Some of them are normal, and some of them have mismatched report types.

**Comment by leonardonakagawa** [comment]
Hi @justinwujian 

Do you also use or request the report GET_XML_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL for something? I'm wondering if you are calling getReports and maybe the report GET_XML_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL is scheduled and that's why sometimes it is generated. Could you review that? 

Thanks,

Leonardo

**Comment by justinwujian** [comment]
> 你好@justinwujian
> 
> 您是否还使用或请求报告 GET_XML_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL 来进行某些操作？我想知道您是否正在调用 getReports ，也许报告 GET_XML_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL 已计划，这就是有时会生成它的原因。你能回顾一下吗？
> 
> 谢谢，
> 
> 列奥纳多

GET_XML_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL is just one of them. The requested A report should return type B report. Not only do you encounter this problem when you create GET_XML_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL, you also encounter the same problem when you create other reports. Currently, we suspect that a scenario in which multiple reports are requested at the same time may cause some reports to be inconsistent with the types of reports. Instead of requesting multiple reports concurrently, we're going to try using a loop that requests each report in turn to see if the problem persists
