### ISSUE TITLE
Catalog API not returning product_description fields

### ISSUE THREAD

**Issue by IsaacSee** [amzn/selling-partner-api-docs#3406]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type
SP-API Catalog Items API v2022-04-01

## Expected Behavior
The attribute values `product_description` should be present in the response of the search.

## Current Behavior
`product_description` is missing while requesting the `attribute` scope.

## Context/Screenshots
This product https://www.amazon.com.br/dp/B086H5CJZC has a description, which is not returned by the catalog API

## Your Environment
dotnet

**Comment by IsaacSee** [comment]
Hi, any update?

**Comment by leonardonakagawa** [comment]
Hello @IsaacSee,

Thank you for reaching out regarding `product_desctiption` attribute.

We have submitted the report to our respective engineering team and is currently being investigated. Once the root cause is identified, I will get back to you with further details and next steps to resolve the same. If you have opened a support case with us, please continue monitoring it as well for further updates.


Thanks,
Leonardo Nakagawa
Solutions Architect, Selling Partner API Developer Support

**Comment by leonardonakagawa** [comment]
Hi @IsaacSee,

After following this up with our engineering team, even if an ASIN description is shown in the Detail Page, we cannot guarantee the API will return the `product_description` attribute. This is due to how the ASIN was created before and who was the contributor to that information. We are discussing with our engineering team to have a proper data handling to this attribute, but by now we could not give any updates.

Thanks,
Leonardo Nakagawa
Solutions Architect, Selling Partner API Developer Support
