### ISSUE TITLE
Authorization API GetAuthorizationCode Error "The application isn't configured with Roles"

### ISSUE THREAD

**Issue by 4deeptech** [amzn/selling-partner-api-docs#347]
What is this error really saying and how do we get this resolved?

Where are these "Roles" assigned to the Application?

Authorization API: GetAuthorizationCode Error: "The application isn't configured with Roles"

**Comment by ShivikaK** [comment]
Hello @4deeptech 

Thank you for raising this issue.

Can you please provide us with more details of your application such as the app ID and the request details?

Please feel free to open a support case with us so we can troubleshoot the issue.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by pprbhm** [comment]
Hi, I am going to close the issue but if you still are facing issue, please open a [support case](https://developer.amazonservices.com/support) and it will be addressed on personal basis. Thank you.

**Comment by marconline** [comment]
I'm facing the same issue. Amazon answered to my case, telling that this happens because the app is still not published and that it would have taken 10 business days. More than 10 business days have passed and the application is still not published and this call still doesn't work. You are requiring us to complete the integration with SP-API before September 2021 but we are not in the condition of doing that. If you are not capable of supporting your developer ecosystem, you cannot set deadlines that are difficult to reach even if everything goes smoothly.

So, what's the answer to this issue? Do we really have to wait? Or there is a different solution?
Thanks

**Comment by ShivikaK** [comment]
Hello @marconline 

Apologies for the inconvenience caused. Can you provide me details of your application ID along with the case created to get the application published. I will review the status of your app and expedite it accordingly.

 Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by hamduc7** [comment]
Hi @ShivikaK 

Could you check my case ID **8386687141**?
I have this same issue

Le

**Comment by marconline** [comment]
Hello @ShivikaK .
our application ID is **amzn1.sellerapps.app.985d401a-6834-4bbb-943d-8cf0feae960b** and the case ID is **6995119312**. 
Please, consider that our situation is a bit complex (due to Amazon's fault) and you will find that our application is actualy linked to:
- 2 European Developer IDs (one with access to PII - the original and main one - and one without, linked to the new Amazon Seller user we opened few months ago)
- 1 North American Developer ID (with access to PII)
- 1 Far East Developer ID (without access to PII)

What I would like to reach is to have - and if I ready it correctly it will be possible with SP-APIs - is **one** set of credentials, with access to PII (**please, remind that we have been succesfully audited by Deloitte and Amazon, and I can provide you with all the paperwork and documents produced**), working across all the regions, linked to our application that is on our new Seller Central account and capable of migrating all of our old MWS tokens.

Thanks

**Comment by marconline** [comment]
Hello @ShivikaK , please consider that yesterday I forgot to mention that we brought on the case on the case ID **6995052062** in order to gain PII access on our second European Developer ID. This case is still open, waiting for Amazon reply.

**Comment by ShivikaK** [comment]
> **8386687141**

Hello @hamduc7 

Your application has not been published yet. Please note that the case mentions that it takes up to 10 days for the app to be fully published. Currently the application publish process is under progress. Please wait to see the status of the app updated in Seller Central prior to making a request to Authorization API.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by ShivikaK** [comment]
> **6995119312**

Hello @marconline 

Thank you for the detailed explanation.

Can you explain which seller account is used to create the application amzn1.sellerapps.app.985d401a-6834-4bbb-943d-8cf0feae960b and are all developer IDs added to this hybrid application?

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by hamduc7** [comment]
> > **8386687141**
> 
> Hello @hamduc7
> 
> Your application has not been published yet. Please note that the case mentions that it takes up to 10 days for the app to be fully published. Currently the application publish process is under progress. Please wait to see the status of the app updated in Seller Central prior to making a request to Authorization API.
> 
> Thanks,
> Shivika Khare
> Selling Partner API Developer Support

Thank you. Amazon sets the dead line but you are too slow to support things related to this migration

**Comment by marconline** [comment]
Hello @ShivikaK ,
it seems that right now our application has been published and it seems that everything works as expected.

I wonder if this result has been reached thanks to your help and my messages on GitHub or because of the "normal" process. I guess you should provide a better developer support on your official channels because, sometimes, it's really frustrating for us as developers, since we see you - Amazon - as a partner and we often don't get back a decent support. 

Thanks anyway for your help.
Marco
