### ISSUE TITLE
[BUG] [SP-API] SP API QuotaExceeded Error for put listing with mode="VALIDATION_PREVIEW" (Not working for more than 2 days)

### ISSUE THREAD

**Issue by TITANHACKY** [amzn/selling-partner-api-docs#3578]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type
Listing API - Put Listing Operation

## Expected Behavior
For the Put Listing Operation with mode="VALIDATION_PREVIEW" the request rate limit per second is 1

## Current Behavior
I'm trying the api for the past 2 days, getting the error: "You exceeded your quota for the requested resource". Not received a single success response

#### Latest Response:
<pre><code>
{
    "message": "You exceeded your quota for the requested resource.",
    "amzn_code": "QuotaExceeded",
    "error": [
        {
            "code": "QuotaExceeded",
            "message": "You exceeded your quota for the requested resource.",
            "details": ""
        }
    ],
    "headers": {
        "Server": "Server",
        "Date": "Wed, 07 Feb 2024 06:28:00 GMT",
        "Content-Type": "application/json",
        "Content-Length": "156",
        "Connection": "keep-alive",
        "x-amz-rid": "FFEW5G1EJZNGxxxx",
        "x-amzn-RequestId": "1b7b37b2-c2c0-47cc-ad6c-77a28xxxx",
        "x-amz-apigw-id": "OPF1b7b37bxxxx",
        "X-Amzn-Trace-Id": "Root=1-65c322f0-1b7b37b2c2xxxx",
        "Vary": "Content-Type,Accept-Encoding,User-Agent",
        "Strict-Transport-Security": "max-age=47474747; includeSubDomains; preload"
    }
}
</code></pre>

I have reviewed the token bucket algorithm used by Amazon. According to the algorithm, tokens should be refilled over time, right?

**Comment by leonardonakagawa** [comment]
Hello @TITANHACKY,

Thank you for reaching out regarding Validation Preview mode in Listing API.

In order to investigate better this case, we need more information about your application and merchant being used to make the calls. 

Could you please [open a support case](https://developer.amazonservices.com/support) with us providing detailed information about your Application and merchant id which you are not receiving the expected response?  


Thanks,
Leonardo Nakagawa
Solutions Architect, Selling Partner API Developer Support
