### ISSUE TITLE
RDA Token Issue

### ISSUE THREAD

**Issue by jparker1986** [amzn/selling-partner-api-docs#3579]
Hello,

Having a hard time understanding how the RDA token is supposed to work.

On the SP-API, I am able to generate an RDA Token, which I am then passing into the GetOrders API Call, as "x-amz-access-token", but it simply returns the error:
```

{
    "errors": [
        {
            "code": "Unauthorized",
            "message": "Access to requested resource is denied.",
            "details": ""
        }
    ]
}
```

If I pass the old access token into the header, it works once more? Am I missing something? 

The RDA Access Token is generated using the following:

```
  "restrictedResources": [
    {
      "method": "GET",
      "path": "/orders/v0/orders/",
      "dataElements": ["buyerInfo", "shippingAddress"]
    }
  ]
}
```

**Comment by Landsailor** [comment]
@jparker1986 You are _not_ going crazy. It _is_ confusing. 

First, the correct term is "RDT" for RestrictedDataToken, so that will help when you're searching for answers. Assuming it's the Orders API based on the call.

That RDT call is requesting blanket permission to access buyerInfo and shippingAddress for _all_ the orders in bulk. You could also request an RDT for a specific order by appending the Order ID.

It's been a long time (and hundreds of thousands of calls) since I was fighting through it, but according to the notes in my script, I am sending the RDT when accessing these endpoints:

- /orders/v0/orders/XXX-XXXXXXX-XXXXXXX 
- /orders/v0/orders/XXX-XXXXXXX-XXXXXXX/orderItems
- /orders/v0/orders/XXX-XXXXXXX-XXXXXXX/address
- /orders/v0/orders/XXX-XXXXXXX-XXXXXXX/buyerInfo

At one point, I remember being able to access (almost?) all the required data in one call, but believe that I decided to use those endpoints to not have to worry about future compatibility issues. (IIRC, there was one endpoint that did _not_ return PII based on a note "Will need RDT here by July 31, 2023".)

Hope that helps!

**Comment by leonardonakagawa** [comment]
Hello @jparker1986,

Thank you for reaching out regarding RDT Token usage.

I would ask you to review if you have access to restricted roles to access PII data.

- Direct-to-consumer shipping. Required to access shipping address information.
- Tax remittance. Required to access buyer information.
- Tax invoicing. Required to access buyer information. 

You can find details regarding this in our [Tutorial: Get authorization to access restricted report types with PII information](https://developer-docs.amazon.com/sp-api/docs/tokens-api-use-case-guide#tutorial-get-authorization-to-access-restricted-report-types-with-pii-information) and [Roles in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/roles-in-the-selling-partner-api).

If the information available in the documentation link provided above does not fully resolve your inquiry, please [open a support case](https://developer.amazonservices.com/support) with us.

Thanks,
Leonardo Nakagawa
Solutions Architect, Selling Partner API Developer Support
