### ISSUE TITLE
[BUG] [SP-API] [Issue] createRestrictedDataToken does not work for getReports and getReport operations

### ISSUE THREAD

**Issue by SudhamsuAtCleo** [amzn/selling-partner-api-docs#3671]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type
Name: Tokens API
Version: 2021-03-01

## Expected Behavior

It is expected that the `createRestrictedDataToken` call work for all restricted operations listed under [Restricted Operations](https://developer-docs.amazon.com/sp-api/docs/tokens-api-use-case-guide#restricted-operations) in the developer docs. `getReports` and `getReport` operations are listed as restricted operations under the Reports API section in the same page.

## Current Behavior

The `createRestrictedDataToken` call fails to generate an RDT for the `getReports` and `getReport` operations. Attached a screenshot below where `createRestrictedDataToken` fails to generate an RDT for the `getReports` API endpoint with a `400 Bad Request` and shows the error: `"Invalid or unsupported document ID found"`. I am using the latest version of the Reports API (`2021-06-30`) in `"path"` in the request payload.

## Context/Screenshots

![image](https://github.com/amzn/selling-partner-api-docs/assets/110598650/6e250683-9964-4ce9-b1b8-4d2fbf829375)

## Your Environment

The request was executed in Postman with the proper access token configured for the request. The call is successful in generating RDTs for other restricted operations.

**Comment by SudhamsuAtCleo** [comment]
Can anyone pls look into this?

**Comment by leonardonakagawa** [comment]
Hello @{developer(s)},

Thank you for reaching out regarding the usage of RDT token with Reports API.

In order to generate an RDT token for the Reports API you need to first generate one of the [Restricted Reports](https://developer-docs.amazon.com/sp-api/docs/tokens-api-use-case-guide#restricted-report-types) using the createReport and getReport operation.

 With the reportDocumentId in hands you use it to specify the getReportDocument path in the RDT `restrictedResources`.

It will be something like this:

```
{
  "restrictedResources": [
    {
            "method": "GET",
            "path": "/reports/2021-06-30/documents/yourReportDocumentId",
            "dataElements": ["buyerInfo", "shippingAddress"]
    }
  ]
}
```

Then, you'll be able to generate the RDT token for it.

You can find details regarding this in our [Restricted operations](https://developer-docs.amazon.com/sp-api/docs/tokens-api-use-case-guide#restricted-operations).
If the information available in the documentation link provided above does not fully resolve your inquiry, please [open a support case](https://developer.amazonservices.com/support) with us.

Thanks,
Leonardo Nakagawa
Solutions Architect, Selling Partner API Developer Support

**Comment by SudhamsuAtCleo** [comment]
The Reports API section in https://developer-docs.amazon.com/sp-api/docs/tokens-api-use-case-guide#restricted-operations has been updated (`getReport `and `getReports` were removed from documentation).

Thanks
