### ISSUE TITLE
Facing issue in catalog items api

### ISSUE THREAD

**Issue by ahmadali419** [amzn/selling-partner-api-docs#3692]
https://sellingpartnerapi-na.amazon.com/catalog/2022-04-01/items?keywords=chair&marketplaceIds=ATVPDKIKX0DER

this error is coming pasing correct token but still error
{
    "errors": [
        {
            "code": "Unauthorized",
            "message": "Access to requested resource is denied.",
            "details": ""
        }
    ]
}

**Comment by chrisskhoury** [comment]
Hello @ahmadali419

Unauthorized errors are primarily caused by insufficient permissions. There can be various reasons behind this issue.

- Ensure that you have the appropriate role added to your application, such as the [Product Listing Role](https://developer-docs.amazon.com/sp-api/docs/product-listing-role) in this instance.
- Verify that you are accessing the correct region and marketplace. Since the URL indicates 'NA', ensure that the access token is authorized to access the North America (NA) region.

Unfortunately, I am unable to provide extensive debugging assistance here. It would be advisable to open a case with developer support for further investigation. You can open a case [here](https://developer.amazonservices.com/support).

Best,

Chris
Solution Architect, SP API
