### ISSUE TITLE
[BUG] [SP-API] [Issue]

### ISSUE THREAD

**Issue by promisepk** [amzn/selling-partner-api-docs#3705]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type
/inbound/fba/2024-03-20/inboundPlans
getShipment
## Expected Behavior

We need the Shippment.destination.address information.
Or has any other api to get the Shipment's destionation address?

## Current Behavior

The Shippment.ddestination.address was not return

## Context/Screenshots

class Shipment {
    amazonReferenceId: 1111
    contactInformation: null
    dates: class Dates {
        deliveryWindow: class Window {
            editableUntil: 2024-05-19T16:00Z
            end: 2024-06-01T16:00Z
            start: 2024-05-19T16:00Z
        }
        readyToShipWindow: null
    }
    destination: class ShipmentDestination {
        **address: null**
        destinationType: AMAZON_WAREHOUSE
        warehouseId: YYZ4
    }
    inboundPlanId: 
}
## Your Environment

linux

**Comment by chrisskhoury** [comment]
Hello @promisepk,

Based on the [reference page](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#getshipment), the [address](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#shipmentdestination) attribute can be optional. It is returned empty if the destination type is `AMAZON_OPTIMIZED`. In this case destinationType: `AMAZON_WAREHOUSE`. Unfortunately I cannot further debug this without a full request and response. 

Please make sure to open a [developer support case](https://developer.amazonservices.com/support) sharing the full request and response so that the backend team can have a look to why this happened.

Best,
Chris
Solution Architect, Amazon SP API
