### ISSUE TITLE
What is needed for GET_FBA_SNS_FORECAST_DATA ?

### ISSUE THREAD

**Issue by johnkw** [amzn/selling-partner-api-docs#371]
GET_FBA_SNS_FORECAST_DATA isn't even documented at all on https://github.com/amzn/selling-partner-api-docs/blob/main/guides/roles/Roles-in-the-Selling-Partner-API.md

Documenting it in general would be good.  In fact there seem to be quite a few missing, although GET_FBA_SNS_FORECAST_DATA is currently the one I'm trying to fix.

Right now it fails with `"code": "Unauthorized", "message": "Access to the resource is forbidden",`.  This is the same failure message some other reports gave when a Role was not attached to the App in the Seller Central app page.  Right now though all of the available roles are enabled and this one is still failing.

In general the API really needs to say *exactly* what is not authorized.  Saying "the resource" is useless.  It should say something like:

`"code": "Unauthorized", "message": "Access to 'GET_FBA_SNS_FORECAST_DATA' is forbidden. App needs XXXXX permission/role.",`

**Comment by johnkw** [comment]
Seller Support finally responded that the answer is `GET_FBA_SNS_FORECAST_DATA` Report Type is not currently supported by the SP-API. That's rather surprising. So if you don't currently have MWS access (we do, thankfully), then it's impossible to track SNS data in an automated way.

**Comment by johnkw** [comment]
Update: `GET_FBA_SNS_FORECAST_DATA` is now supported by SP-API. I'm not sure what the permission situation is. That still needs to be documented on https://github.com/amzn/selling-partner-api-docs/blob/main/guides/roles/Roles-in-the-Selling-Partner-API.md along with many other reports.

**Comment by johnkw** [comment]
This bug is just for documenting the API access/roles (and hopefully for actually fixing the API so it gives a more descriptive error message).  See also bug #421 for documenting the contents of the reports.

**Comment by Waqas770** [comment]
Any one found the solution ?

**Comment by johnkw** [comment]
No but some documentation was added in https://developer-docs.amazon.com/sp-api/docs/roles-in-the-selling-partner-api which fixed bug #375.

**Comment by avvarga** [comment]
Hello @johnkw,

As you have mentioned on your most recent post, our documentation has shifted to a [new site](https://developer-docs.amazon.com/sp-api/), where you will also be able to find different announcements, release notes, a blog and other sections.

More specifically related to this issue, the roles section that you mentioned has been improved to include all available Reports, Feeds and Notifications in a section below the operations for **each role**. For example, regarding the GET_FBA_SNS_FORECAST_DATA Report, you will see that it is available under the [Amazon Fulfillment Role](https://developer-docs.amazon.com/sp-api/docs/amazon-fulfillment-role#feeds-reports-and-notifications).

In regards to the other part of this issue, we are working with our teams in order to include more specific error messages when possible, although, we do not have an expected time when this will be completed. Once done, however, there will be an announcement under the corresponding section of our new documentation site.

Thanks,
Alejandro C
Selling Partner API Developer Support
