### ISSUE TITLE
[Commercial Access for Amazon Seller SP-API] Documentation 

### ISSUE THREAD

**Issue by bishwjeet-singh** [amzn/selling-partner-api-docs#3746]
I have created a Shopify app using the Amazon Seller SP-APIs. In order to get access to APIs, I registered my app on the Amazon developer console. However, now that I want to go public, I am not able to find any steps that would help me get commercial access for the APIs. What are the next steps? 

**Additional context**
I tried connecting with support, but they usually reply that developer team is not available. Additionally I tried searching for documentation but couldn't find one which would help me get commercial access for my app.

**Comment by harguph** [comment]
Hello @bishwjeet-singh , 


In order to making a public application:

[STEP-1] one has to register as a public developer. Please refer to the official documentation [here](https://developer-docs.amazon.com/sp-api/docs/register-as-a-public-developer) and follow the section "**Complete the Developer Profile**".

[STEP-2] List your app on the Selling Partner Appstore by following the documentation [here](https://developer-docs.amazon.com/sp-api/docs/list-your-app-on-the-selling-partner-appstore)

Additionally, refer [here](https://developer-docs.amazon.com/sp-api/docs/registering-your-application) for more information on how to register your application.

Regards.
