### ISSUE TITLE
[BUG] [SP-API] [Issue] No 404s for price updates

### ISSUE THREAD

**Issue by Faithfinder** [amzn/selling-partner-api-docs#3748]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type
[Patch Listing Item](https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-reference#patch-listings2021-08-01itemsselleridsku) and POST_PRODUCT_PRICING_DATA Feed,

## Expected Behavior
When I send an incorrect SKU to either, if there's an error in SKU, I get an error in the `issues` array

## Current Behavior
Instead everything is reported as good - price change is accepted, feed result returns successful processing

**Comment by chapmanjw** [comment]
@Faithfinder This is expected behavior. A "listing" represents three things: (1) what are you selling (the item), (2) how are you offering it (the pricing, etc.), and (3) how are you fulfilling it (FBA, MFN quantity, etc.). In this scenario, you are successfully sending us #2, but that doesn't mean you have a complete buyable listing. If you were to then add "item" details and "fulfillment" details, your listing would be complete. 

Using the Listings Items API `getListingItem` operation as part of your workflow will help paint the complete picture as to the status of your listings. The feed processing reports typically only include issues related to whether or not we could accept or process the data you submitted. See https://developer-docs.amazon.com/sp-api/docs/building-listings-management-workflows-guide.

Last note, this feed type  (POST_PRODUCT_PRICING_DATA) is being deprecated. See https://developer-docs.amazon.com/sp-api/changelog/deprecation-of-feeds-api-support-for-xml-and-flat-file-listings-feeds. I would recommend reviewing the migration guide on how to migrate your pricing update workflows: https://developer-docs.amazon.com/sp-api/docs/migrating-listings-management-workflows

**Comment by Faithfinder** [comment]
Thank you for explaining the model, however, please consider returning an issue of INFO severity. We've had bugs with incorrect SKU encoding in the past, and debugging was all guesswork.
