### ISSUE TITLE
Authorization of access to PII information to get shipping address information.

### ISSUE THREAD

**Issue by 9z** [amzn/selling-partner-api-docs#394]
Hello,

For getting shipping address via getOrderAddress api, I updated developer profile.

But I got the following answer,

"You have indicated that you require Restricted roles to build an application that will be publicly available for sellers. At this time, we are not approving the use of Restricted data for new public applications, or updates for added functionality on existing public applications. We apologize for any inconvenience this causes.

No changes have been made to your SP-API access at this time."

Has anyone solved this problem?

**Comment by Trocellen** [comment]
we are also experiencing a issue consuming a API-SP for buyer information.

The API involved is: getOrderBuyerInfo.

In few word we are able only to retrieve the mail information without other useful value for our business.
We need information about:

BuyerName The name of the buyer. string
BuyerCounty The county of the buyer. string
BuyerTaxInfo Tax information about the buyer

This information are requested only in case of Business Invoices

**Comment by karan4364** [comment]
Hi,
I am also experiencing the same problem. I have created a private app and access to all the roles. But still not getting buyer information in SP-API. 

I have raised a ticket to amazon agent but they said, Using this API I can not get the buyer information.

**Comment by unterweltler** [comment]
Having the same problem - I even applied to the "Direct Shipping" Role, which should give access to PII Informations.
But even though the role was granted - I still can't access any useful Buyer- / Shipping-Informations ...

What's the benefit of this API if we can't rebuild the functions that we have on a MWS App?
Especially because MWS Support is going do get deprecated.

**Comment by unterweltler** [comment]
Found a solution ... after getting the PII Role granted and adding it the the APP - you need to generate a new RefreshToken and use it in your APP.

After that - you will get the Shipping- / Buyer-Informations

**Comment by Trocellen** [comment]
Thanks a lot!
Sorry for the probably too easy question but I'm quite new in this field.
how can I get the PII role?

thanks a lot!
Nicola

**Comment by unterweltler** [comment]
For anyone asking - you need to apply for the PII-Role.
You can do the Application here - https://sellercentral-europe.amazon.com/developer/register (for European SellerAccounts).
Check the "Restricted" Roles that you need - to get access to the PII, you need "Direct-to-Customer Shipping".

**Comment by NoraYan** [comment]
@unterweltler I got approval of PII , selected new role and generated new refresh token, but still can't get full buyerinfo and shipping address.

**Comment by unterweltler** [comment]
@NoraYan 
hmm ... that's weird - for me using the new RefreshToken did the trick ...
You might need to wait a little bit until Amazon has updated your permissions on their API (but that's a very vague guess)

**Comment by 9z** [comment]
@NoraYan 
Hello 
How did you get PII approval?
I made a request for PII approval through the developer registration page, but it was rejected.
Have you also requested PII approval from the developer registration page?

**Comment by webinsect-rishabh** [comment]
@unterweltler @karan4364 @9z @NoraYan  Hi Guys, Does any one of you tried Reports API. I am able to get GET_MERCHANT_LISTINGS_DATA and FLAT_FILE_LISTING_DATA but i cant get REFERRAL_FEE_PREVIEW_REPORT.

and @NoraYan do you get the buyer_details now after the PII approval.

**Comment by jchavest13** [comment]
Hi everyone,

@9z - Could you please provide your most recent Developer Registration case? In this way I'll be able to take a look and address your concern accordingly.

@karan4364 @NoraYan @webinsect-rishabh - If you still need assistance on this topic and you have been already approved for required Restricted SP-API roles, please submit a request for SP-API technical support here: 
NA - https://sellercentral.amazon.com/gp/mws/contactus.html 
EU - https://sellercentral.amazon.co.uk/gp/mws/contactus.html  
AU - https://sellercentral.amazon.com.au/gp/mws/contactus.html    
JP - https://sellercentral.amazon.co.jp/gp/mws/contactus.html 

Regards,
Julian
Developer Registration Specialist

**Comment by anildropy** [comment]
Hello @jchavest13 ,

I got my MWS Developer Id on September 2020. At this time, I thought I do not need Restricted accesses so I did not apply for them. But when I build my APIs, I have seen that I cannot see buyer information of order because I do not have PII Access.

I applied to get PII Access (Direct-to-Consumer Shipping) several times to get Buyer Info, but it rejected.

Even I have developer Id and I call mws apis for my both Singapore and United Arab Emirates but I cannot see my app under Manage Your Apps section on seller central.

Can you please help me?

**Comment by jchavest13** [comment]
Hi @anildropy ,

Can you please provide your most recent Developer Registration case ID, so I can further review it and determine its outcome accordingly?

Regards,
Julian
Developer Registration Specialist, SP-API

**Comment by anildropy** [comment]
Hi @jchavest13 ,
Thank you for reaching me.

I am having same problem in my both registration for Amazon SG and Amazon UAE. most recent Developer Registration case IDS are as following:

Amazon SG: 2189375983
Amazon UAE: 6301302272

Need your help to reach that access to build my app.
Regards.

**Comment by anildropy** [comment]
> @NoraYan
> Hello
> How did you get PII approval?
> I made a request for PII approval through the developer registration page, but it was rejected.
> Have you also requested PII approval from the developer registration page?

Hello @9z ,

Any update for your access registration? Did you get PII access for your orders?

**Comment by jchavest13** [comment]
Hi @anildropy ,

Your case is currently pending review. Please ensure you monitor your Seller Central account for any pending case updates where your response may be needed to fully meet the requirements of our Data Protection and Acceptable Use policies.

Regards,
Julian
Developer Registration Specialist, SP-API

**Comment by jchavest13** [comment]
Hi @9z , 

Can you please provide your most recent Developer Registration case ID, so I can further review it and determine its outcome accordingly?

Regards,
Julian
Developer Registration Specialist, SP-API

**Comment by valigara** [comment]
Hi @jchavest13

Maybe you will be able to give some approximation on how quick we can have an answer? Our application is waiting for the PII approval for almost a month, and we are in production.

Thank you and Great day, 
Igor 
Product, Jewelry eCommerce specialist, Valigara Online

PS thank you for answering here! It's giving a feeling of "there is a chance". It's not easy waiting after applying, w/o any reply and idea on what's happening...

**Comment by jchavest13** [comment]
Hi @valigara ,

Can you please provide your most recent Developer Registration case ID, so I can further review it and determine its outcome accordingly?

Regards,
Julian
Developer Registration Specialist, SP-API

**Comment by valigara** [comment]
@jchavest13 Hi, Julian

Sure, 
We have 3 cases open on US, UK and JP marketplaces. 
I was able now to locate the open case on JP -> ID 2201471003
Having some issues viewing the cases on the UK and US hubs today (hmmm), but our US Seller ID where we've got already approved for SP-API is: AA8WH0OQF80OS , approval case 8079774141

I am available for all q's
igor@valigara.com / +972547575475

Thank you! 
Igor Nusinovich
Product, Jewelry eCommerce specialist, CEO, Valigara Online

**Comment by anildropy** [comment]
Hi @jchavest13 ,

Answered case # is 6301302272.
It says "We have reviewed the information you provided and determined that you are not eligible for access to the Amazon SP-API you requested." which means I am not allowed to access PII, but there is no reason for it. 

I need you to help me.

**Comment by valigara** [comment]
Hi @jchavest13 ,

Were you able to check the case? 
We are in production, can't provide decent answers to our clients for more than a month... Unfortunately the 1st-line support aren't able to provide any answers. :-/

Thank you!
Igor Nusinovich
Product, Jewelry eCommerce specialist, CEO, Valigara Online

**Comment by hemadevi** [comment]
Hi,
I have requested for PII in amazon sp-API. I have submitted a data protection policy, AUP, and Incident response plan. I got a response from Amazon: 
"We have reviewed the information you provided and determined that it is virtually identical to the information that has been submitted in the past by you or another account. Therefore, you are not eligible for access to the Amazon SP-API PII roles you have requested."
But this is the first time I'm opening an account in sp-API

Your SP-API access will remain the same based on this assessment. CASE LOG: 8293479061
Please let me know what to do?

**Comment by jchavest13** [comment]
Hello everyone,

@anildropy - I'll study your case further to see if the outcome is correct. Once I have any updates, guidance or further details about denial you received, I'll update this issue.

@valigara - Your case 2201471003 has been resolved as duplicate, since we found that you have submitted multiple Developer Profiles for your organization. 

Please note, we only require one Developer Profile submission from your organization. Therefore, please continue using case 8186080291 for your Developer Registration process, which is pending for you to provide additional information requested last week.

Once your case is approved, your organization will have global Marketplace access to SP-API based on the roles you requested.

@hemadevi - As the emailed you received said, the information you provided in your Developer Profile is virtually identical to the information we have received from other accounts. This could be either another account that belongs to your organization or to another one, and usually happens when we identified identical wording in responses from different accounts up to the point that sometimes is almost like a copy/paste.

What I can suggest you to do, is to update your Developer Profile and make sure you elaborate your own description of the security controls your organization has in place, according to our policies. Once submitted, our team will evaluate your request to determine its proper outcome.

@9z - Can you please provide your most recent Developer Registration case ID, so I can further review it and determine its outcome accordingly?

Regards,
Julian
Developer Registration Specialist, SP-API

**Comment by valigara** [comment]
Hi @jchavest13 !

Thank you very much for your answer. It was quite confusing to submit the registration in all marketplaces. So it makes complete sense that we have to submit it only once.

**Comment by hemadevi** [comment]
Hi,
I have updated our Developer Profile and make sure we elaborated our own description of the security controls of our organization has in place, according to Amazon policies.  yet I got the Restricted Access Request.  Response from amazon is as follows:
"We have identified the following areas that do not meet the requirements set forth in the Acceptable Use Policy and Data Protection Policies:
1.[Question - Describe why you require Personally Identifiable Information to build your application or feature.]
Acceptable Use Policy - Unsupported functionality for restricted data use: Restricted roles are provided exclusively for Tax Remittance, Tax invoicing or Direct-to-Consumer Shipping purposes. Based on the information you have provided, we determined that your application is using Restricted Roles for "we need customer’s name, street address, and billing address details for each of the Amazon orders we must fulfill", which is not a supported functionality for use of Restricted data obtained through Selling Partner API (SP-API).
a) Tax Remittance
b) Tax Invoicing
• The use case provided does not justify why the Seller Central Tax Settings configurations do not suffice your need for Tax Remittance and Tax Invoicing.
No changes have been made to your SP-API access at this time." 

I have also developed the incident response plan. I can provide you URL of it if you want.
 CASE LOG: 8338530181

**Comment by valigara** [comment]
> 8186080291

Dear @jchavest13, 
Did you find out the reason why I can't open case 8186080291 by direct link and can't see my US account in sellercentral?

**Comment by jchavest13** [comment]
Hi everyone,

@valigara - If you still have no access to your case, please contact Developer Support for further assistance: https://sellercentral.amazon.com/gp/mws/contactus.html
In addition, please check out the case once you can access it, as I can confirm there's an update on it.

@syedj-dev - Looks like your case was resolved a few days ago. Please go ahead and check it out to get more details about its outcome.

@hemadevi - Upon review, I could confirm there's an update in your Developer Registration case 8353354041, please make sure to check it out and take actions accordingly.

@baijianguo - I checked the case you provided and looks like it was already resolved. Please check it out for more information about its outcome.

@9z - I'm resolving this issue, since no response has been received from your end after multiple follow ups.

Regards,
Julian
Developer Registration Specialist, SP-API

**Comment by hemadevi** [comment]
I got the following response from amazon:
"please reply to this case and provide the Case ID and Merchant IDs for any other Developer Profile and/or MWS Developer Registration cases you may have submitted for your organization, including those in other regions." case ID: 8353354041"
I have amazon mws account and developer ID. I have forget to mentioned in the developer profile form adding mws developer id. But I have mentioned this in the case to reply to amazon about my present mws developer ID, merchant ID, region and organization name. I have provided all the known and available details I have. Please let me know. what should I do?

**Comment by hemadevi** [comment]
Hello,
I want PII access for the USA region;  I  have changed the developer profile details and IRP after encountering this issue. but I keep on getting the following response from amazon:
"We have reviewed the information you provided and determined that it is virtually identical to information that has been submitted in the past by you or another account. Therefore, you are not eligible for access to the Amazon SP-API roles you have requested."
case Log:8353354041
Can you please help me clarify what information they find virtually identical? 
Is it about the Incident response plan or developer profile details?
what I have to do to solve this issue?

**Comment by valigara** [comment]
> @valigara - If you still have no access to your case, please contact Developer Support for further assistance: https://sellercentral.amazon.com/gp/mws/contactus.html

Dear @jchavest13, 
Thank you so much! We really appreciate it.

We've opened several cases for Developer Support to solve the issue. We kindly want to continue the correspondence in these cases, But we have no access to them too.
CASE 8387331771
CASE 8403229511
Can you provide us with any information to solve the issue?

In addition, because of the issue we cannot proceed to work with case 8186080291, we've opened case "SP-API Developer Profile Update: Restricted Access Request" ID7054906262. Is it enough from our side to get restricted SP-API access for US/EU/JP as well?

**Comment by 40gb** [comment]
@jchavest13 
SP-API Developer Profile Created: Restricted Access Request
ID 6696277012

What would be the reason that reply says "you currently do not qualify for this access". It also says "it is required to be listed in the Marketplace Appstore". Can you please have a look at the case and tell me how to fix this?
Thanks

**Comment by cheryong** [comment]
Hi,

I need PII access for Singapore and a few other regions.
I have requested it 2 weeks ago and there is no response so far. My client is waiting for us to perform integration to their amazon seller account. Can you please help ? Here's my case number with Amazon Support 2219675723. Please let me know if you need any additional information.

Thank you in advance,
hia

**Comment by deo79** [comment]
@jchavest13 
Perhaps you could help me out as well?  Our developer ID just got denied a second time, and I have no idea why (this last review took months to complete)...  Case # 8090414061
We need PII for direct shipping to customers, and we've been without this access for months and months with severe ramifications.  The email response about the denial was very non-specific about issues with our application.

**Comment by shashank-depasser** [comment]
Hi @jchavest13 

We are experiencing the same problems with regards to getting access to the "**Direct-to-Consumer-Shipping**" API.
We have applied for the access a multiple times and have been denied with the reason being "**We have completed our assessment and have determined that you do not meet the requirements for Restricted SP-API**".

I want to understand what needs to be done in order to get the access. Our case id is **7163823762**.

Any help here would be really appreciated.

**Comment by jpatlolla** [comment]
Hi @jchavest13 

We also experiencing the same problem with regards to getting access to the 
Direct-to-Consumer Delivery(Restricted) API.  Any help to get approved and access to the SP-API

Thank you for updating your Amazon Selling Partner API (SP-API) Developer Profile. We have completed our assessment and have determined that you are not eligible for an update to your access to the SP-API Restricted roles. Please read this message carefully and review the Case Appeals section below if you would like to appeal this decision.

We have identified the following areas that do not meet the requirements set forth in the Acceptable Use Policy and Data Protection Policies, please refer to the links provided below and look for the information for each corresponding Policy link:

AUP - Acceptable Use Policy
https://sellercentral.amazon.com/mws/static/policy?documentType=AUP&locale=uk_UK

Data usage 4.1.

RDA - Restricted Data Access
https://sellercentral.amazon.com/mws/static/policy?documentType=DPP&locale=us_US

Access Management 1.2
Encryption at Rest 2.4
Data Retention 2.1
Logging and Monitoring 2.6
Incident Response Plan 1.6

Case Id: 7221343242

 Thank you

**Comment by MojoManager** [comment]
Hi @jchavest13

SP-API Developer Profile Update : Restricted Access Request
ID7287202882

We also experiencing the same problem with regards to getting access to the
Direct-to-Consumer Delivery(Restricted) API. Any help to get approved and access to the SP-API


Thank you for your response.

We have completed our assessment and have determined at this point in time that you are not eligible for Restricted SP-API access to build a publicly available application. While we appreciate your submission, we reserve Restricted SP-API access for developers that represent the greatest benefit to Amazon Customers and Selling Partners. As our Marketplace Appstore and your application evolve, you may reapply for this access in the future.

No changes have been made to your SP-API access at this time.

Please advise

Many thanks

**Comment by MojoManager** [comment]
Hi jchavest13 ,

Our github account was flagged and all tickets were spammed. Now it's active.  Please check following. 

SP-API Developer Profile Update : Restricted Access Request
ID7287202882

We also experiencing the same problem with regards to getting access to the
Direct-to-Consumer Delivery(Restricted) API. Any help to get approved and access to the SP-API

Thank you for your response.

We have completed our assessment and have determined at this point in time that you are not eligible for Restricted SP-API access to build a publicly available application. While we appreciate your submission, we reserve Restricted SP-API access for developers that represent the greatest benefit to Amazon Customers and Selling Partners. As our Marketplace Appstore and your application evolve, you may reapply for this access in the future.

No changes have been made to your SP-API access at this time.

Please advise

Many thanks

**Comment by paly76** [comment]
Hi @jchavest13 :
My developer information has been submitted for a long time, but it has not yet been reviewed. Please review it as soon as possible, thank you!
Caseid:8789514971

**Comment by amy432** [comment]
Hi @jchavest13 
Having the same problem - I even applied to the "Direct Shipping" Role, which should give access to PII Informations.

Case ：8939994301
Case :  8933789211

**Comment by margaret0303** [comment]
Dear @jchavest13
We are having same problem with rejection for Restricted Access.
"We have completed our assessment and have determined that you do not meet the requirements for Restricted SP-API. To protect Amazon Customers, we only consider sharing Customer data (“Restricted access”) with third party Developers that offer features that are materially different from existing applications. The Developers that meet these criteria must then go through rigorous security reviews with Amazon."

We asked for details of rejection as our application is actually unique solution and beneficial for Sellers but we have not  received any respond yet.
I would be grateful if you could you please supports how to proceed further as our clients are now on stand-by.
Thank you.
Case ID: 7334070982

**Comment by fernlop** [comment]
Hello,

same Problem here (Case 6900535322)
I tried multiple times but always get the same response. There is no explanation why my request is refused beside the standard response block everyone else is getting from Amazon too. 

If you check my activity in this repo you can see that I'm even helping other sellers use the new API but still I'm not "worthy" accessing it?

I used the same data protection policies I created for other sellers that have successfully requested PII access for themselves. But if I try to get access to it as an app developer it gets refused? 

I even think about reporting this to the Federal Cartel Office because it's hurting my business very much. It's the basis of my e-commerce software I'm building. 

Best regards,

Marvin

**Comment by tom-it** [comment]
we are stuck with building our intergration in our shopify app to allow our merchants to import order data from their amazon account. 

our app is live with over 200 merchants using it, and aside from the bol.com intergration which is working, we get a lot of requests for amazon. 

after 4 weeks of development time we come to find out we get rejected for PII data, which makes it impossible for us to offer merchants what they need. :( very dissappointing

**Comment by sarabjeetsaini** [comment]
Hi, I need an account that has access to PII. If someone willing to sell let me know. 

Telegraph @sunnysaini09
