### ISSUE TITLE
For each seller, are refresh tokens global or different for each marketplace? 

### ISSUE THREAD

**Issue by github-admin-cosmers** [amzn/selling-partner-api-docs#407]

**Comment by ravikas** [comment]
if you create application for US, you can access data for CA, BR, MX marketplaces (tested this with orders)., but you cannot get data for other marketplaces, switching to Europe endpoint returns error, therefore i think in order to access data for eu marketplaces you need to create Europe country application with different authorization/tokens.

**Comment by nodisk8800** [comment]
One Refreshtoken for one Area.

**Comment by github-admin-cosmers** [comment]
Thanks for your response guys
