### ISSUE TITLE
Receive 403 on SPAPI

### ISSUE THREAD

**Issue by Raf2061** [amzn/selling-partner-api-docs#410]
I tried to connect to SPAPI since from november 2020, contacting Amazon support but none was able to resolve, so I stop trying to use API and I use a different solution. But I would like to understand why, after following ALL the documentation issues (creating AWS profile, create application, setting up the authentication like the documentation said) I wasn't able to use, and receiving simply 403 on calling API for purchaseOrders  (non other details, or json-formatted errors).
Amazon help desk simply ask to me to send details on my error, but I haven't any!

**Comment by avvarga** [comment]
Hello @Raf2061,

I apologize that we have not been able to pinpoint the source of the error. 

Because of the nature of the error presented, we do need to follow up via a support case. 

The additional details requested are usually a time stamp and Request ID, which depending on the program used to submit the request (via your own software or a third party program like Postman) this can be found in a different location.

Please open a support case so we can pursue the investigation and provide additional, more case-specific details.

Thanks,
Alejandro Chavarria
Selling Partner API Developer Support
