### ISSUE TITLE
Error code MD9999 when a seller from the US uses our OAuth link, but it works fine for EU sellers.

### ISSUE THREAD

**Issue by intellifox-hq** [amzn/selling-partner-api-docs#464]
Hi!

We have an hybrid MWS+SP-API app.

Sellers from the EU are using our app without any issue. SP-API and MWS works flawlessly.
We tried to enroll a user from the US using the proper OAuth link, but it resulted in the error "MD9999".

![image](https://user-images.githubusercontent.com/74097842/109796011-f0bde180-7c17-11eb-9e72-759ff8b15ddd.png)

We opened a case (case id is 6751004542 ) with details but it hasn't bee resolved.
Do any other app using the OAuth process have encountered this error?
Is this because we only have MWS id for the EU region?

**Most importantly: how do we solve this?**

Thank you @parvathm for your help with this. Sorry for the inconvenience.

**Comment by estebanangel** [comment]
Same issue here but in our case the US marketplaces are working but when the User logs in with Amazon to the EU ones, we get this MD9999 error. Any solutions for this case?

**Comment by intellifox-hq** [comment]
> Same issue here but in our case the US marketplaces are working but when the User logs in with Amazon to the EU ones, we get this MD9999 error. Any solutions for this case?

It seems to me the solution is quite obvious. **Let's switch our tokens!!!**

I'm kidding of course...
Up until now I did not have any resolution from the Amazon team, unfortunately.

Do you have a hybrid app (MWS+SP) or just an SP access?
My guess is that this error is triggered with half-filled hybrid app (those that don't have MWS tokens for each marketplace, it's the only reason I can see).

**Comment by parvathm** [comment]
> 
> 
> > Same issue here but in our case the US marketplaces are working but when the User logs in with Amazon to the EU ones, we get this MD9999 error. Any solutions for this case?
> 
> It seems to me the solution is quite obvious. **Let's switch our tokens!!!**
> 
> I'm kidding of course...
> Up until now I did not have any resolution from the Amazon team, unfortunately.
> 
> Do you have a hybrid app (MWS+SP) or just an SP access?
> My guess is that this error is triggered with half-filled hybrid app (those that don't have MWS tokens for each marketplace, it's the only reason I can see).

Hi @intellifox-hq,

I looked at the case , sorry for the delay in response. NA MWS AccountId is not configured in the app.  Yes. You are right that only EU MWS developer id is added and hence NA is returning error.

Thanks,
Parvathm
Selling Partner API Developer Support.

**Comment by parvathm** [comment]
> 
> 
> Same issue here but in our case the US marketplaces are working but when the User logs in with Amazon to the EU ones, we get this MD9999 error. Any solutions for this case?

Hi @estebanangel,

If you have created a case id with app details please let us know . We will check and get back to you.

Thanks,
Parvathm
Selling Partner API Developer Support.

**Comment by estebanangel** [comment]
I will create the case and let you know, thank you very much. In our case, the app is only a Selling Partner API, not MWS.

Thanks

Esteban Angel

**Comment by estebanangel** [comment]
> > Same issue here but in our case the US marketplaces are working but when the User logs in with Amazon to the EU ones, we get this MD9999 error. Any solutions for this case?
> 
> Hi @estebanangel,
> 
> If you have created a case id with app details please let us know . We will check and get back to you.
> 
> Thanks,
> Parvathm
> Selling Partner API Developer Support.

Hi @parvathm ! Here's the case id ID8190891061. Thank you very much for your help!

**Comment by intellifox-hq** [comment]
> Hi @intellifox-hq,
> 
> I looked at the case , sorry for the delay in response. NA MWS AccountId is not configured in the app. Yes. You are right that only EU MWS developer id is added and hence NA is returning error.
> 
> Thanks,
> Parvathm
> Selling Partner API Developer Support.

Thank you very much for you answer @parvathm , that clears things up.
Since it's not possible for us to get a brand new MWS token for the NA marketplaces and we didn't have one beforehand, we'll have to fully migrate to SP-API.

The not self-explanatory part of the process was that MWS has a region by region token system, while SP-API works for any account upon any region (which is great).

Then of course an hybrid app (MWS + SP-API) would only let us work with the smallest subset of users.
Thank you again for your work @parvathm and have a good day.

**Comment by estebanangel** [comment]
Hi @parvathm ! Can you open this issue again? this is not closed because there might be other cases for the MD9999 error. In our case we don't have a hybrid app, we have a full SP API app. can you check please the case ID I sent yesterday?

**Comment by nirmay** [comment]
We are facing the same issue. we have a hybrid app working well for NA region, we are now extending it to EU region, but see this error.

The case is already raised with support, 8383884761
@parvathm @rugved1991 Could you please check and let us know if there is anything that needs to change on our app config. you will find additional details on the ticket.

thanks in advance,
Mayuresh

**Comment by rugved1991** [comment]
Hi @nirmay,

I noticed that you have only added NA developer ID on your hybrid app. That is why you are able to authorize NA sellers. If you wish to authorize EU sellers through the hybrid application, you would need to add EU developer ID to your application. 
Try adding the EU dev ID in regional developer IDs in app settings and then test again.

Thanks,
Rugved
Solutions Architect, SP API

**Comment by Sgroove** [comment]
We are having the same issue @rugved1991, our case ID is 7995216561.

Do you mind checking it and letting me know how we can overcome this issue? We are not able to authorize European sellers at the moment because of it. 

We did try to update the application using the same US Developer ID for Europe but it won't work of course.

Thanks in advance!

**Comment by AmazonSellerNeedingHelp** [comment]
Hi, 

Please can anyone help me. I am an Amazon Seller, not a Developer. (So much of this is confusing).

About 2 months ago my A2X account did some updates, and it required me to re-sync my market-places. The UK/EU was fine, but the NA account would come up with this MD9999 error. Normally, the hand shake is done, and it leaves Amazon and goes back to the app (e.e.g A2X). but it just gives this error code. Weirdly if I then check my apps in Amazon, it shows as connected but hasn't. Its now been about 10 weeks and no progression. I had A2X running fine for 2/3 years before this with no problems.

Following that, my Helium 10 account needed to be re-connected, and has the same issues - its now been 2 months and they have just refunded me. They were never any help anyway. I had Helium 10 running for 3/4 years before this with no problems. 

I have tried other Apps, Seller Toolkit, Link My Books, and they are all having this issue. I cant connect any apps to my NA account.

I literally cant run my business properly as the accounting ones are not working, and no-one knows how to fix it. 

One person said the the API was reporting Null.


Amazon are adamant its not my account, and has nothing to do with them. They have been no help at all.

They say its the apps fault:


This is Gabrielle from the Selling Partner API Developer Support team.
I reviewed your account and I understand you are concerned about the MD errors you are experience with the third party application.
While I know you're disappointed with our stance on this matter, I want to assure you the information you received from me on 4/6/2023  is correct.
As mentioned, we have check your account and on your side everything is good.
Please note that currently our developers are migrating their application from MWS to SP API and some of them and experiencing errors due to information missing in their applications.
For this reason we Advised the seller to have the Developer contact us directly, since the seller can not update the application and does not have the information we need to troubleshoot this type of error.
I'm sorry for any disappointment caused and appreciate your understanding. While we won’t be able to comment further on this matter, we're always happy to help if you have any other questions.

Please if anyone has any ideas on how to help me, I would be extremely grateful.

I run the business on my own, and I don't know whom to turn to. 

Thank you
Martin




<img width="1417" alt="Screenshot 2023-03-23 at 17 27 08" src="https://user-images.githubusercontent.com/132383480/235731802-43bed7ba-18d9-45e4-8d8a-067a7ee3781d.png">
<img width="1405" alt="Screenshot 2023-03-23 at 17 26 56" src="https://user-images.githubusercontent.com/132383480/235731793-ddfc9d8d-63d9-4f55-9d25-fbce26924199.png">

**Comment by hinavinayak** [comment]
> 

Hello, 

I just checked authorizing a few of the apps you mentioned from a NA seller account and was able to do so without error. I started by clicking authorize now from this Helium10 App listings [link](https://sellercentral.amazon.com/selling-partner-appstore/dp/amzn1.sellerapps.app.d1c63fac-31eb-42f2-9b2a-6efaeb60d262) and was able to generate the token end to end. 

Can you ensure your NA ( US marketplace per the screenshot) account has no outstanding seller central blocks or pending issues? 
Also, can you share the case-id you submitted with seller/developer support?

**Comment by AmazonSellerNeedingHelp** [comment]
Yes, this is the ridiculous thing - Amazon API say it the apps fault and its a new issue, yet no one from the apps has ever seen it before, and this thread here (same issue) is from over 2 years ago !


Two of my Case ID's:

12216980551
12415326411

Thank you for your help.

Also, here is my response on another thread:


Hi Federico,

Hi @AmazonSellerNeedingHelp,

I apologize for this issue, and understand how this is currently affecting your business.

As Gabrielle from Developer Support mentioned, there is no issue with your selling account. The error is likely related to the applications you are trying to connect (A2X and Helium 10). Therefore, we need their owners to contact Developer Support so we can debug and troubleshoot. Have you already contacted these service providers reporting your issue? After receiving your request, they should contact us and the issue should be eventually solved. If you haven't, I kindly ask you to do it, and we will be glad to support them on the resolution of this problem.

Thank you, Federico Selling Partner Developer Services

This makes no sense at all.

These Apps (not just A2X and Helium 10, I have tried with 8 different apps now - ALL have the same result.

*** I cant connect a SINGLE app to my NA account - not one I have tried will work - they ALL fail ***

None of the APPs developers have encountered this error before - no one knows what it is or how to fix it.

A2X and Helium 10 I previously had for 4/5 years with no issues.

There is something wrong with my account, when the handshake happens - it doesn't happen.

I have been advised that my account may be suppressed. Can you see this??

It may be an account being suppressed isn't completely visible internally so it may have just been missed.

It was recommended that I follow up with the Seller Central Support and let them know the account is in a Suppressed state and find out how it can be removed.

However I have called Seller Support, and they said my account is not suppressed, and they cant see anything wrong.

I know 100% this to do with my account. Some setting is out, something is not right here !

Thank you

Hi @AmazonSellerNeedingHelp,

I apologize for this issue, and understand how this is currently affecting your business.

As Gabrielle from Developer Support mentioned, there is no issue with your selling account. The error is likely related to the applications you are trying to connect (A2X and Helium 10). Therefore, we need their owners to contact Developer Support so we can debug and troubleshoot. Have you already contacted these service providers reporting your issue? After receiving your request, they should contact us and the issue should be eventually solved. If you haven't, I kindly ask you to do it, and we will be glad to support them on the resolution of this problem.

Thank you, Federico Selling Partner Developer Services

This makes no sense at all.

These Apps (not just A2X and Helium 10, I have tried with 8 different apps now - ALL have the same result.

*** I cant connect a SINGLE app to my NA account - not one I have tried will work - they ALL fail ***

None of the APPs developers have encountered this error before - no one knows what it is or how to fix it.

A2X and Helium 10 I previously had for 4/5 years with no issues.

There is something wrong with my account, when the handshake happens - it doesn't happen.

I have been advised that my account may be suppressed. Can you see this??

It may be an account being suppressed isn't completely visible internally so it may have just been missed.

It was recommended that I follow up with the Seller Central Support and let them know the account is in a Suppressed state and find out how it can be removed.

However I have called Seller Support, and they said my account is not suppressed, and they cant see anything wrong.

I know 100% this to do with my account. Some setting is out, something is not right here !

Thank you

ps - Federico - please do not close this - it is not solved...
