### ISSUE TITLE
[FEATURE] Inbound Shipment API Use Case Guide

### ISSUE THREAD

**Issue by amanz360** [amzn/selling-partner-api-docs#518]
**Describe the improvement**
Add a detailed guide describing the expected workflow for using the Inbound Shipment API. This API encompasses a full workflow with fairly complicated requirements, it would be extremely useful to have general tips and guidelines about each step of the process.

**Additional context**
I've recently set up an inbound shipment workflow and it was only possible to get all the way through via information found in various forum posts online, outdated MWS documentation, random stack overflow posts, and other issues on this repo. There are still many things I'm unsure about even though I've set up a fully working inbound shipment workflow because it's difficult to understand the full set of considerations based on the current documentation.

**Comment by charliecode** [comment]
@amanz360 I would like to see this as well, Amazon has been detailed like this with some things for the SP-API but not all. Interestingly they did what you're asking for with the MWS API, [here's an example](https://docs.developer.amazonservices.com/en_US/fba_guide/FBAGuide_CommonTasks.html). Also, because there's a lot of overlap between the new and old APIs you can sometimes refer to the old guides for guidance. Good examples is the one you're currently working on, [you can check that out here](https://docs.developer.amazonservices.com/en_US/fba_guide/FBAGuide_ShipInventoryToAFN.html).

**Comment by vuesets** [comment]
@charliecode  

How do I create in-bound shopment in the form of a new workflow. 
Example, I would create boxes package, then create shipment on use sp-api.
I noticed that the MWS API doesn't say anything about this.
