### ISSUE TITLE
[FEATURE] Documentation - Best practice to receive Fees, Sales Prices and Product Data for many listings

### ISSUE THREAD

**Issue by stefnats** [amzn/selling-partner-api-docs#519]
Hello,

our use case is that we sometimes need to retrieve all fees, sales prices and product data of all of a seller's listings.
With the old MWS API, this was possible with getting multiple listings at once, however we had always encountered rate throttling which we accepted. With the new API it's only possible to retrieve only one SKU/ASIN at a time. This means much more API Calls and much more time to retrieve. I believe this is not the best interest for Amazon.
I noticed that these fees are in no reports and the sales prices are also in no reports.

So what would be the best practice to receive Fees, Product Data and Sales Prices for all listings?
To be more exact

Fees = All available fees like Referral Fee, Promotions, FBA Fees, etc. based on a price input
Product Data = ASIN, Title, Images, Attributes, Sales Ranks, Variations, etc.
Sales Prices = Current online price and - if it exists - a strikethrough price
What are the best practices for retrieving data for lots of listings (>100k)?

Thanks in advance!

**Comment by stefnats** [comment]
For Fees i think i found it out myself:
Reports `GET_REFERRAL_FEE_PREVIEW_REPORT` and `GET_FBA_ESTIMATED_FBA_FEES_TXT_DATA` contain these data.
You may only request `GET_REFERRAL_FEE_PREVIEW_REPORT` once every 24 hours, so you might want to check for finished reports of that type in the last 24 hours.

However, product data & sales prices are still unknown to be received. Can anybody help?

**Comment by ellis** [comment]
Your use case seems like it should be the most basic one to support (other than that fact that you're talking about 100k listings), but it's still not well supported at all.  Here are a few of the many pitfalls:

- The report `GET_FBA_ESTIMATED_FBA_FEES_TXT_DATA` is practically useless in Europe because it returns the fees for all EU countries at once but doesn't have a column to let you know which country a particular column belongs to. (#694)
- The Product Fees and Product Pricing APIs don't work with all SKUs (#467)
- The report `GET_MERCHANT_LISTINGS_ALL_DATA` won't suffice in FR, because it's missing the `asin1` column for no fathomable reason. (#580)  Otherwise, it will provide you with the title and prices of SKUs.

For product data, check out the newer [Catalog Items](https://github.com/amzn/selling-partner-api-docs/blob/main/references/catalog-items-api/catalogItems_2020-12-01.md) API.  It has lots good data, but isn't intended for bulk; you'll need to query each ASIN individually.  You'll need to use a different API for ranking, and you'll also need to iterate through all the ASINs individually.
