### ISSUE TITLE
PII - approval time

### ISSUE THREAD

**Issue by SebastianOzdoba** [amzn/selling-partner-api-docs#525]
Hi
We are waiting for application approval (PII) for 4 weeks. Is there anyone who make it happen?
Case ID: 6810562052
Thanks, best regards

**Comment by SebastianOzdoba** [comment]
@krithic15 can you help for it?

**Comment by krithic15** [comment]
Hello @SebastianOzdoba,
Apologies for the delay here. I got an update that you should be hearing back on the case by end of tomorrow. 
Thank you for your patience.

Best,
Krithi,
Solutions Architect, SP API

**Comment by GuillermoZAfiroCode** [comment]
Did you get PII access?
I had tried it for several months but I didn't get it... 

Amazon told me that nobody is getting that access for now...

**Comment by SebastianOzdoba** [comment]
@GuillermoZAfiroCode no i don't have it.
Still is "pending review". I need that access because my customers sending FBM orders  :)

**Comment by bobsys-mfleischer** [comment]
Nothing is happening here either.

Case ID: 6871048152
We opened the ticket on 18 March. Almost a month later we still have no feedback.

**Comment by rugved1991** [comment]
Hi @bobsys-mfleischer,

Thanks for providing the case ID. I have escalated the case from my side. The team will review the case and respond back to it. Please continue to monitor the case for updates.

@SebastianOzdoba you have requested for restricted roles and the case is currently pending review. Please continue to monitor the case for further updates.

Thanks,
Rugved
Solutions Architect, SP API

**Comment by jchavest13** [comment]
Hi everyone,

@SebastianOzdoba - Your case is still under review since you have requested access to Restricted SP-API roles. Please ensure you continue monitoring your case for any pending case updates where your response may be needed to fully meet the requirements of our Data Protection and Acceptable Use policies. 

@bobsys-mfleischer - Upon review, I can confirm there is an update in your Developer Registration case. Please carefully review the case and provide the requested additional information as instructed.

Regards,
Julian
Risk Specialist, SP-API
