### ISSUE TITLE
Purchase orders not being returned - BUG

### ISSUE THREAD

**Issue by GeorgeJalland** [amzn/selling-partner-api-docs#555]
I am having an issue where the "purchaseOrders" and "purchaseOrdersStatus" endpoints are returning blank lists of purchase orders despite the purchase orders existing within Vendor Central. I have been using the API for about a month and have not had this issue before. Please advise.

**Comment by GeorgeJalland** [comment]
More specifically, the endpoints I am talking about are: 
https://sellingpartnerapi-eu.amazon.com/vendor/orders/v1/purchaseOrders
https://sellingpartnerapi-eu.amazon.com/vendor/orders/v1/purchaseOrdersStatus

The respective responses are attached. 
![purchaseOrders](https://user-images.githubusercontent.com/67790077/113323572-048b5f00-930e-11eb-9370-3697a09c3c82.PNG)
![purchaseOrdersStatus](https://user-images.githubusercontent.com/67790077/113323640-1bca4c80-930e-11eb-9bb9-476b58570950.PNG)

**Comment by rugved1991** [comment]
Hi @GeorgeJalland,

Can you try adjusting the timestamp durations using CreatedAfter or CreatedBefore parameters?
If you are still seeing empty response, please open a support case and provide us the complete request and response along with headers to troubleshoot the issue further.

Best,
Rugved
Solutions Architect, SP API

**Comment by GeorgeJalland** [comment]
Hi Rugved, 

Thanks for the reply. I've tried with various different query parameters and the response is still the same. I can also query for a specific PO that exists within VC and I get a "ResourceNotFound" error. As I say, I've been using the SP-API for about a month and it has been working fine. It's worth noting that this happens for 2 separate Vendor Central accounts (and hence credentials), however, I am using the same AWS credentials to sign both. I have raised a support case in one of the Vendor Central accounts but I am awaiting a response from Amazon. When you say provide with the complete request, are you wanting the raw HTTP code? 

Many thanks,
George

**Comment by RoFuLo** [comment]
Same problem here. In my case we can't fetch PO information for orders created after 2021-03-31. The orders doesn't appear when we call purchaseOrders with purchaseOrderState=NEW, and we get an  'ResourceNotFound' Error when we call PurchaseOrder with an identifier of a order created after 2021-04-01.

**Comment by rugved1991** [comment]
Hi @GeorgeJalland and @RoFuLo ,

Thanks for reaching out. There was an issue with the Vendor Orders API. This impacted the orders created between 03/02 and 03/4. The issue is now resolved and you should be able to receive response from the API once again. If you are seeing any missing orders, please cut a ticket to vendor support with a list of purchaseOrders. The support team will be able to help resolve the issue.

Thanks,
Rugved
Solutions Architect, SP API

**Comment by sidrafarooq** [comment]
Hi, 

I am facing the same problem. by calling getPurchaseOrder and passing a specific purchase order i am able to get a single purchase order but when i am calling getPurchaseOrders the response is empty. I tried different from and to date and also tried other parameters but no success.

**Comment by inspiritek** [comment]
One of our Lambda functions which has used the SP API for making getOrderList calls for around a year has suddenly run into this issue as of about a week ago. Every aspect of the request is unchanged from before and the response.status_code is returning a 200, yet the 'payload' is returning e.g. {'Orders': [], 'CreatedBefore': '2023-06-12T18:40:04Z'}. I have been troubleshooting this for hours now and I am still not sure what the issue is.

Something to note though is that the LWA credentials for the application weren't rotated in time and we 'supposedly' lost access to the SP API, but using our new LWA credentials we are still able to get specific order information using an order ID as well as retrieve payout reports and listing reports. The only API call that stopped working was the order list call. Keep in mind that the LWA credentials at this point HAVE been rotated, and updated inside the application, and it changed nothing.

**Comment by robertlansing** [comment]
@inspiritek Did you ever resolve this issue? I am experiencing the same thing but just for one vendor, but right around the time of LWA creds expiring.

**Comment by inspiritek** [comment]
@robertlansing Unfortunately, I don't have a specific answer for you (but I didn't want to leave you hanging). It's been so long ago I don't fully recall the solution but, if my memory serves at all, we were looping through multiple marketplaces and I believe we had to restructure the way we were looping and change the order of some of the data in the request. 
Not much help, I know, but maybe it will spark something that helps you solve the issue you are having.
