### ISSUE TITLE
How to get all the product information of the seller ?

### ISSUE THREAD

**Issue by gopkg-dev** [amzn/selling-partner-api-docs#577]
I now need to get all the seller's product information, including the following information
`asin`,`sellersku`,`fnsku`,`title`,`image`,`price`,`discount price`,`stock`,`status` ......
Now I'm using `GET_MERCHANT_LISTINGS_ALL_DATA` report
But can't get `fnsku`, `discount price`, `stock`

**Comment by stefnats** [comment]
Hey @gopkg-dev 

i'd recommend `GET_MERCHANT_LISTINGS_DATA`

What do you mean with `status`? For deactivated / defective data you need to retrieve the `GET_MERCHANT_LISTINGS_DEFECT_DATA` report.

For Discount Pricing, there is no report to my knowledge (please correct me if i'm wrong!), so you have to use the Product Pricing API: 
https://github.com/amzn/selling-partner-api-docs/blob/main/references/product-pricing-api/productPricingV0.md#getpricing

**Comment by gopkg-dev** [comment]
@Stefnats 
`GET_MERCHANT_LISTINGS_DATA`  does not work, it has no ASIN

**Comment by zhumo1998** [comment]
> 我现在需要把所有卖家的产品信息，包括以下信息
> `asin`，`sellersku`，`fnsku`，`title`，`image`，`price`，`discount price`，`stock`，`status`......
> 现在，我使用的`GET_MERCHANT_LISTINGS_ALL_DATA`报告
> ，但不能得到`fnsku`，`discount price`，`stock`

Hello,How can I get all the product information that I am selling in Amazon mall? I can't get listing through the report. Can you help me solve this problem? Thank you very much.

**Comment by stefnats** [comment]
> @stefnats `GET_MERCHANT_LISTINGS_DATA` does not work, it has no ASIN ![image](https://user-images.githubusercontent.com/58848833/114048688-6115ed80-98bd-11eb-82b9-f61ac78f462a.png)

Hey there!
I have experienced this very problem with the `_GET_MERCHANT_LISTINGS_DATA_` report type in MWS as well since 2012 or so. 
My solution would be to call another endpoint, for example [`getPricing`](https://github.com/amzn/selling-partner-api-docs/blob/main/references/product-pricing-api/productPricingV0.md#getpricing) by the SKU which also returns the ASIN.

This is very inconvenient and i have addressed this issue a few times with dev support, but they didn't fix it (yet).

It seems that mostly Amazon.fr listings are affected that have been listed with EAN in inventory loader / listing loader feed.

**Comment by stefnats** [comment]
Hey there, just a thought again. You can try other reports (afn inventory, fee preview, etc.) that contain ASIN data as an additional source instead of querying all Skus from the listings report.

Did you manage to retrieve the ASINs?
