### ISSUE TITLE
[BUG] The same report type returns different data, this problem is very serious. 

### ISSUE THREAD

**Issue by gopkg-dev** [amzn/selling-partner-api-docs#580]
##  **In the European test, France return 13 fields, while in other countries 30 fields were return.**

ReportType :  `GET_MERCHANT_LISTINGS_ALL_DATA`

## **I hope they return the same.**

@rugved1991  @krithic15

```json
     {
         "reportType": "GET_MERCHANT_LISTINGS_ALL_DATA",
         "processingEndTime": "2021-04-08T11:07:06+00:00",
         "processingStatus": "DONE",
         "marketplaceIds": [
            "A13V1IB3VIYZZH"
         ],
         "reportDocumentId": "amzn1.spdoc.1.3.e313a2e7-4076-4519-99be-c202af538527.T20WWMK2AT0YQL.47700",
         "reportId": "181296018725",
         "dataEndTime": "2021-04-08T11:06:55+00:00",
         "createdTime": "2021-04-08T11:06:55+00:00",
         "processingStartTime": "2021-04-08T11:07:00+00:00",
         "dataStartTime": "2021-04-08T11:06:55+00:00"
      }
```
![image](https://user-images.githubusercontent.com/58848833/114017915-37e66480-989f-11eb-8204-e4a81b18d7f3.png)

**Comment by rugved1991** [comment]
Hi @gopkg-dev,

This is expected behavior. The Listings report data changes according to the marketplace. Some marketplaces have require additional information on a listing. But, there are some fields in the report which are common across all marketplaces. You can find a list of fields in an Active Listing Report here: https://sellercentral.amazon.com/gp/help/200385890?language=en_US&ref=ag_200385890_cont_561

The order of the report columns might change depending on the information added in each marketplace.

Thanks,
Rugved
Solutions Architect, SP API

**Comment by gopkg-dev** [comment]
Thanks for your reply, I get it

**Comment by ellis** [comment]
@rugved1991 The huge problem here is that the FR report is missing the `asin1` field, which lists the ASIN in every other marketplace I'm using.  (Or more accurately, the non-FR reports may sometimes leave `asin1` blank in rows where `product_id_type = 1`, but then `product_id` has the ASIN).

This unnecessarily makes the absolutely basic task of getting a merchant's list of SKUs and ASINs into a real chore.  Could you please just add in the `asin1` field like it is everywhere else?

**Comment by stefnats** [comment]
@ellis the missing asin1 results in when a listing in Fr is created via EAN. This is a bug that I know since 2011 I think, so it occurred in MWS as well. My solution for those ASINs is to retrieve the pricing by sku and this would also return the ASIN.

**Comment by ellis** [comment]
@stefnats Thanks for the "historical" background information.  I guess that dashes hopes of it ever being fixed. :(

And thanks for explaining your workaround, too.
