### ISSUE TITLE
Application is draft，Can I request an API?

### ISSUE THREAD

**Issue by 468092882** [amzn/selling-partner-api-docs#59]
title

**Comment by 468092882** [comment]
![image](https://user-images.githubusercontent.com/32814680/96848591-30fd9e00-1487-11eb-866f-79b7db1f107d.png)

**Comment by charliecode** [comment]
@468092882 I haven't read anything about anyone making API calls in draft state. I've only seen that draft state is used for testing authorization. It's definitely not going to work for production API calls, not sure about the sandboxed, I would guess not.

**Comment by rogersv** [comment]
You can use app in draft-state to connect to your own sellers account since you have the refresh token. You can not authenticate an external seller to get their refresh token when using draft state.

So you can do a production API call but only to your own seller account. You can also do an API call to the sandbox.

**Comment by charliecode** [comment]
@rogersv That's a great point, I forgot about the self authorization. Which I imagine would technically mean the app is still in draft-state for everyone except yourself, nice catch.

**Comment by charliecode** [comment]
@rogersv I am curious, in Developer Central what does the status of your app say? Mine also says "Current edit is saved as draft". The only thing the docs say about draft state is that by using the version=beta in the url during auth, you're in draft state.  And by not using it you're not is draft state but rather prod. They give zero direction beyond that. So I'm wondering if the issue with some of us is that our apps are in a permanent draft state, which needs fixed by Amazon via a case. I've already created a case where draft state was mentioned by the support team and am having an incredibly difficult time getting update responses from support. So I guess what I'm wondering is, does your app status in Developer Central also say "Current edit is saved as draft" and if not at what point did it say it is not in draft state? I understand the need for the aws4 signatures and all the additions to the headers but this seems out of the scope of all that.

**Comment by rogersv** [comment]
My app is in draft-state. I have not yet tried the auth step with version=beta. It is possible that I will get problem at that point.

**Comment by charliecode** [comment]
You can find a concise answer about application draft state in issue #66

**Comment by Jitendratri** [comment]
@charliecode My app is in ready to publish state can i request an api call?

**Comment by Jitendratri** [comment]
Application is Ready for publishing Can I request an API?
