### ISSUE TITLE
Publish new hybrid draft application - Waiting Amazon approval 

### ISSUE THREAD

**Issue by gregoks** [amzn/selling-partner-api-docs#631]
hi,

We have working MWS application and we want to start using SP API and migrate our existing seller tokens as well.
We first want to publish new hybrid application to see how it will work and how it will affect our seller point of view and then decide if to switch the existing MWS app to hybrid or start using new SP API application from scratch.

Can you please approve it? The case id is 8211772251, The app Id is amzn1.sp.solution.67eb191d-5881-4656-84c0-4efbd88cd9fa.
@rugved1991 can you please assist?

Thanks!

Greg

**Comment by rugved1991** [comment]
Hi @gregoks,

I would recommend you to not publish the application before testing out the SP APIs and implementing the OAuth flow on your client. If you publish your application on Appstore before making the changes on your client, any new users that click on "Authorize Now" button on Appstore for your application, will run into errors as you have not handled OAuth flow.
You can create new SP API application and test out the SP APIs. If you create a new hybrid app, you wont be able to use Authorization API to migrate existing users as there wont be any MWS authorizations configured with this new hybrid app.

The correct order of migrating to SP APIs is as follows:

1. Create HTTPS URLs for Login and Redirect.
2. Setup AWS Account with IAM User and Role.
3. Convert MWS app to hybrid application.
4. Receive authorization from your seller using the OAuth URL.
5. Test SP APIs
6. When satisfied with the tests, begin app publish process on Appstore.
7. Send app listing details for review.
8. Once the app is published, migrate all existing MWS sellers to SP APIs using Authorization API.

For more information on the migration process, please refer to our [Migration Guide](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/migration-guide/selling-partner-api-migration-guide.md).

Thanks,
Rugved
Solutions Architect, SP API

**Comment by gregoks** [comment]
Hi @rugved1991 ,

Thanks for your answers! I'm a little bit concerned about the following issues:

1. I have sellers that already use the MWS application, if I make this application hybrid, I will only be able to test migration of tokens in production environment for real existing sellers. If something wont work it can cause many issues.
If I have hybrid draft application, will I be able to connect seller to this new application with MWS token and then migrate it to OAuth token to see that it works correctly?

2. I wanted to see what the seller will feel with the hybrid application when he's trying to connect using "Authorize Now" button from my website and also from the amazon store application, to explain to all the sellers that they need to select the OAuth token instead of the MWS token. Your suggestion again will force me to test it in production and I want to see how the new hybrid application behaves before changing my existing MWS application.

Greg

**Comment by gregoks** [comment]
Another small question, you suggested first to convert my existing MWS app to hybrid application. Will this have any affect on the published MWS application? 
or will my app remain both published in amazon store as MWS and will also be in draft mode as hybrid?

Thanks!

Greg

**Comment by vikingcodes** [comment]
@gregoks When you will convert your MWS to the hybrid app (MWS + SP API). It will not affect existing MWS users. 

The main objective of a Hybrid app is that you can use both MWS API and SPAPI using the same app.

Yes, @rugved1991 suggests you right way to first convert the app to hybrid then SPAPI.

My suggestion to you first convert your existing app's authentication and authorization part to hybrid's SPAPI.

After that convert other MWS API to SPAPI one by one.

After successfully convert all MWS API to SPAPI. Then convert your hybrid app to the "SPAPI" App.

**Comment by vikingcodes** [comment]
@gregoks FYI: When you change anything on the app setting on seller central, you need to publish your app. It can take approx 15 days to publish your app. then you can make a call on behalf of the other seller on SP-API. 

Till you can test self authorization in-app draft mode.

And after September 2021, Amazon will close support for MWS API.

**Comment by rugved1991** [comment]
Hi @gregoks,
Please find the answers below:

1. I have sellers that already use the MWS application, if I make this application hybrid, I will only be able to test migration of tokens in production environment for real existing sellers. If something wont work it can cause many issues. If I have hybrid draft application, will I be able to connect seller to this new application with MWS token and then migrate it to OAuth token to see that it works correctly?
When you authorize a seller with hybrid application, you will receive MWS token and SP API OAuth code. You can use the MWS token to call MWS APIs. The SP API OAuth code will be used to receive tokens to call SP APIs. You cannot test migration of tokens but you will be able to test API calls on both MWS and SP APIs.

2. I wanted to see what the seller will feel with the hybrid application when he's trying to connect using "Authorize Now" button from my website and also from the amazon store application, to explain to all the sellers that they need to select the OAuth token instead of the MWS token. Your suggestion again will force me to test it in production and I want to see how the new hybrid application behaves before changing my existing MWS application.
You can test the OAuth flow while the app is in draft status by adding the "version=beta" parameter in the OAuth URL. When the app is published, you will remove this parameter.
 
3. Another small question, you suggested first to convert my existing MWS app to hybrid application. Will this have any affect on the published MWS application? or will my app remain both published in amazon store as MWS and will also be in draft mode as hybrid?
Converting the MWS app to hybrid will not affect your currently published MWS application. Your users will still be able to use the MWS app. You will have to publish the hybrid application to replace the MWS app on the Appstore.

Thanks,
Rugved
Solutions Architect, SP API

**Comment by rugved1991** [comment]
Hi @gregoks,

Let me know if you need any additional information. Feel free to close the issue if you dont have any additional questions.

Thanks,
Rugved
Solutions Architect, SP API
