### ISSUE TITLE
How to createReport with reportType GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2

### ISSUE THREAD

**Issue by wonpera** [amzn/selling-partner-api-docs#649]
hello~
    I am getting a successful response from createReport with reportType `GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL`, but when calling creatReport with reportType `GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2` got invalidInput error.
why would this be?
`{
    "errors":[
        {
            "code":"InvalidInput",
            "details":"",
            "message":"Request for report type 1118 is not allowed at this time"
        }
    ]
}`

**Comment by jatinthapar1910** [comment]
Having the same issue.

**Comment by jlevers** [comment]
I think it's because this report type can only be fetched, not created or scheduled, per the [reportType documentation](https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reportType_string_array_values.md#settlement-reports). I'm not sure why that is, but I've been able to successfully access it by calling `getReports` and then calling `getReport` with one of the report IDs I get back from the `getReports` call.
