### ISSUE TITLE
Signing up for Selling Partner API - Where to find IAM ARN?

### ISSUE THREAD

**Issue by LotusLine** [amzn/selling-partner-api-docs#69]
Hello,

We have a registered app already with old MWS API and are following the instructions to add new SP API for hybrid application.
https://prnt.sc/v6ykz6

Have gotten stuck at this point https://prnt.sc/v6ykpz.

What is IAM ARN and where can we get the value of this from?

**Comment by vdanyliv** [comment]
@LotusLine carefully read spec from this point [https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#step-2-create-an-iam-user](Create an IAM user)

**Comment by LotusLine** [comment]
Thanks for speedy response. Yep, have slowly followed each and one of those steps.
ARN Roles, user, permissions etc are all sorted out and created. Still stuck at what the value for IAM ARN is?

**Comment by vdanyliv** [comment]
@LotusLine ARN is an amazon resource name, you need to open a newly created role and find on the top of the page ARN identification.

**Comment by deepaktech94** [comment]
@LotusLine You need to create IAM user on amazon console. After create user amazon provide you user ARN like 

arn:aws:iam::711456690060:user/SPAPIUser

**Comment by vikingcodes** [comment]
@LotusLine You need to create IAM user on amazon console. After create user amazon provide you user ARN like 

arn:aws:iam::711456690060:user/SPAPIUser

**Comment by vdanyliv** [comment]
@vikingcodes really? please read docs carefully

Step 4. Create an IAM role
Save your **role ARN**. 
You will need it: When you register your applications

**Comment by vikingcodes** [comment]
@vdanyliv , We need User ARN or Role ARN ? I think on that screen we need User ARN.  Let me know if I am not correct.

I created following User and Role. 

User ARN
arn:aws:iam::711456690060:user/SPAPIUser 

Role ARN
arn:aws:iam::711456690060:role/SellingPartnerAPIRole 

On this screen https://prnt.sc/v6ykpz

For IAM ARN field we need to put full User ARN or Role ARN ?

 like "arn:aws:iam::711456690060:user/SPAPIUser " or Role ARN "arn:aws:iam::711456690060:role/SellingPartnerAPIRole "

Or 

Need to put just SPAPIUser  or SellingPartnerAPIRole  on IAM ARN field?

**Comment by vdanyliv** [comment]
@vikingcodes, you need to use role arn. I already integrated my app, and everything works as expected.
Also here is some extra info from docs.

Important. When registering your application, the IAM ARN that you provide must be for the IAM entity to which you attached the IAM policy from Step 3. Create an IAM policy. In this workflow, that IAM entity is the IAM role from Step 4. Create an IAM role. If you register your application using your IAM user, be sure that the IAM policy is attached to it. Otherwise your calls to the Selling Partner API will fail. We recommend registering your application using an IAM role, as shown in this workflow, to help you better control access to your AWS resources.

**Comment by vikingcodes** [comment]
Ok, I not implemented that steps. Thanks
