### ISSUE TITLE
[BUG] GET_FBA_ESTIMATED_FBA_FEES_TXT_DATA don't take marketplaceIds param into account

### ISSUE THREAD

**Issue by aaalekseev** [amzn/selling-partner-api-docs#694]
GET_FBA_ESTIMATED_FBA_FEES_TXT_DATA returns listings for all marketplaces regardless marketplaceIds param provided. 

In the returned listings there is not marketplaceId property - so it is not possible to match listings with corresponding marketplaces.

**Comment by yuql** [comment]
GET /reports/2020-09-04/reports，type：GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE
has same bug, marketplaceIds param invalid

**Comment by ellis** [comment]
Where I'm having a problem with this is in Europe, where we're getting the data for DE, ES, FR, IT, NL, SE, UK all mixed into a single report.  Either the report add a column for marketplace or it should respect the `marketplaceId` parameter.

There is a `currency` column, which that lets unambiguously assign rows to SE and UK, but for the Euro countries, we'd need to try to lookup the titles, but that would be super inconvenient and not completely reliable.

@yuql I vaguely remember struggling with this problem too, and not finding a complete solution.  I think the reason that the `marketplaceId` is ignored in the EU is because some rows are not specific to a country.  But they really should make sure that the country is specified on every row where possible (I think there are some where it's probably just missing because of sloppy programming).

**Comment by mott7** [comment]
This is still an issue rendering the report useless in the EU marketplace as there is no way to distinguish which marketplace the data relates to. Please fix

**Comment by AmandeepSingh179** [comment]
Facing the same issue. Can anyone from Amazon support team look into it?

**Comment by IBee21** [comment]
This has been such a problem for years. Please fix it!!

**Comment by mott7** [comment]
Ridiculous that this hasn't been fixed! Renders this report useless to anyone selling in multiple marketplaces with the same SKU.

**Comment by mott7** [comment]
The ludicrous thing is that it would take 10 seconds for a developer at @amvreddy-amazon to fix

**Comment by philsmy** [comment]
There used to be a sneaky way to figure out which EUR marketplace it was because of the way they broke up charges but that seems to be gone. So we’re actually going backwards

**Comment by nrueckmann** [comment]
Still broken
