### ISSUE TITLE
Shipping address is incomplete in /orders/v0/orders/{orderId}/address

### ISSUE THREAD

**Issue by rogersv** [amzn/selling-partner-api-docs#72]
I made a call to `/orders/v0/orders/{orderId}/address` to our own seller account to get a real order.
I got the order information but the shipping information was incomplete.

The response I got is below and the `xx...` contained correct data
```
{
    "payload": {
        "AmazonOrderId": "xxx-xxxxxxx-xxxxxxx",
        "ShippingAddress": {
            "PostalCode": "xxxxx",
            "City": "xxxxx",
            "CountryCode": "xx",
            "Name": ""
        }
    }
}
```
The "Name" should not be empty and a lot of other information is missing.

**EDIT**: Is this because of the app is in draft-state and the rest of the information is personal information?

Note:
The app is in draft-state and I have used self-auth to get the refresh-token.
(I used https://github.com/amzn/selling-partner-api-models/blob/main/models/orders-api-model/ordersV0.json as reference.)

**Comment by p-prins** [comment]
Yes, PII data is hidden by default. In some cases, you can get access to PII data, but only for the purpose of taxes or merchant fulfilment. From the new [Data Protection Policy (DPP)](https://s3.amazonaws.com/amazonservicesstatic.com/policies/Amazon-Selling-Partner-Acceptable-Use-Policy_2021.pdf)):

> Do not use Personally Identifiable Information about Amazon Customers for any purpose other than tax and
merchant fulfillment.

PII data includes (from the new [DPP](https://s3.amazonaws.com/amazonservicesstatic.com/policies/Amazon-Selling-Partner-Acceptable-Use-Policy_2021.pdf)):

> This includes, but is not limited to, a Customer or Selling Partner’s name, address, e-mail address, phone number, gift message content, survey responses, payment details, purchases, cookies, digital fingerprint (e.g., browser, user device), IP Address, geo-location, or Internet-connected device product identifier.

Also see the current [DPP](http://docs.developer.amazonservices.com/en_UK/dev_guide/DG_DataProtectionPolicy.html).

**Comment by rogersv** [comment]
Thanks for the response.
It will be quite difficult to ship the order to a customer without having access to the shipping address (when using FBM).
I assume that it should be possible to get that data from the API since it is documented.

I suspect that the personal data is hidden since the app is in draft-state and unapproved by Amazon.

**Comment by charliecode** [comment]
@rogersv - @p-prins is dead on... I do not believe the PII is removed because you're in draft state. I think you're actually making production calls if you're using the self authorization. As you know, the only time test calls is mentioned is in reference to using the version=beta being added during SP-API auth, not for making actual SP-API calls. But you have bypassed auth and therefore are making production calls. The previous application I built had all PII missing for all FBA orders. And believe me I saw many many many orders. Is it also missing for FBM? I thought the shipment related data was on those orders. I'm trying to find the screen where it mentioned how you can request access to PII under certain conditions. I know I saw it somewhere but can't currently find it. Regardless I'd imagine it's done through Seller Support so you may want to start there.

**Comment by rogersv** [comment]
@charliecode Thanks for you response. The shipping information was actually missing on an FBM order.

**Comment by p-prins** [comment]
It's been a long time since I registered, but I vaguely remember that they ask you what the purpose of your application is. Based on the answers you provided at the time they might not have granted you access to PII data. I think it's best if you open open a support ticket in Seller Central because I don't think this is an issue with the API itself.

**Comment by seanevan** [comment]
Hi @rogersv, can you please log your case with Developer Support here https://sellercentral.amazon.com/gp/mws/contactus.html and reply with your case ID so the team can confirm it routed correctly.

Thanks,
Sean Evans
Manager, Support Engineering

**Comment by rogersv** [comment]
@seanevan Thanks, I created a new case earlier today. The case id is `6462722682`

**Comment by charliecode** [comment]
For the benefit of others, I found a link to more information as well as instructions on exactly what data is restricted and not as well as how to access more permissions via "Roles". [You can find that information here.](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/roles/Roles-in-the-Selling-Partner-API.md)

**Comment by rogersv** [comment]
@charliecode answered my question. I had not applied for the correct role for this use case.

**Comment by aadedeji-dxt** [comment]
I have run into the same issue, and I have confirmed that Direct-to-Consumer Shipping and Tax Invoicing roles are enabled for the application that is making the authorized call to the getOrderAddress SP-API endpoint.

The fields returned in the GetOrderAddressResponse are below (similar to the response of the original post). PII such as address and name are being stripped from the response. Is there anything I can do from my end to fix this?

{
    "payload": {
        "AmazonOrderId": "xxx-xxxxxxx-xxxxxxx",
        "ShippingAddress": {
            "PostalCode": "xxxxx",
            "City": "xxxxx",
            "CountryCode": "xx",
            "Name": ""
        }
    }
}
