### ISSUE TITLE
Not found GetMatchingProductForId API on SPAPI docs

### ISSUE THREAD

**Issue by vikingcodes** [amzn/selling-partner-api-docs#74]
We still using GetMatchingProductForId API on SPAPI ?

**Comment by seanevan** [comment]
Hi @vikingcodes, I think you may be looking for the operations that can be found in our [Catalog Items API](https://github.com/amzn/selling-partner-api-models/blob/3a0872d1603a2cf2859335c271272c39f816bc47/models/catalog-items-api-model/catalogItemsV0.json). Please let me know if I've misunderstood your question.

Thanks,
Sean Evans
Manager, Support Engineering

**Comment by kairav646** [comment]
Hi @seanevan ,

based on your reference, we can retrieve data for products that are available in our catalog. But if we want details of products those are not available in our catalog. But want to check to get details, I am using GetMatchingProductForId.

In MWS, by using GetMatchingProductForId we can find products based on UPC and ASIN. I can't find it in the SP API. Can you please provide any other API call or update on it?

**Comment by Abdullah-Koroglu** [comment]
> Hi @seanevan ,
> 
> based on your reference, we can retrieve data for products that are available in our catalog. But if we want details of products those are not available in our catalog. But want to check to get details, I am using GetMatchingProductForId.
> 
> In MWS, by using GetMatchingProductForId we can find products based on UPC and ASIN. I can't find it in the SP API. Can you please provide any other API call or update on it?

Having the same issue. Please help ! :D

**Comment by webinsect-rishabh** [comment]
> Hi @vikingcodes, I think you may be looking for the operations that can be found in our [Catalog Items API](https://github.com/amzn/selling-partner-api-models/blob/main/models/catalog-items-api-model/catalogItemsV0.json). Please let me know if I've misunderstood your question.
> 
> Thanks,
> Sean Evans
> Manager, Support Engineering

Same issue for me also. Please anyone provide details about this

**Comment by rugved1991** [comment]
Hi @webinsect-rishabh, @Abdullah-Koroglu,

You can use the [ListCatalogItems](https://github.com/amzn/selling-partner-api-docs/blob/main/references/catalog-items-api/catalogItemsV0.md#listcatalogitems) operation to search for items using different query parameters like UPC, ASIN, ISBN, etc. 

Thanks,
Rugved
Solutions Architect

**Comment by ulandj** [comment]
Hi @rugved1991 ,
We can retrieve 5 products' details passing SellerSKU params in a single request using `GetMatchingProductForId` method of the MWS API. But in the `ListCatalogItems` of SP API we can get only one product's details using SellerSKU which means we will have to do 4 extra requests.
Do you know if there are any ways to fetch details of multiple products in a single request? Or is there a plan to improve `ListCatalogItems` endpoint of SP API so that we could request 5 or more products' details passing SellerSKU parameter with multiple SKUs? i.e. to do the same as `GetMatchingProductForId` of the MWS API ?
Thanks
