### ISSUE TITLE
reports-api: access to the resource is forbidden

### ISSUE THREAD

**Issue by YFBook** [amzn/selling-partner-api-docs#769]
I am using python and  I can successfully request and download GET_RESTOCK_INVENTORY_RECOMMENDATIONS_REPORT

however when I attempt to create GET_REMOTE_FULFILLMENT_ELIGIBILITY,the thing I really need is the reports api and it gives a 403 with:

{
“code”: “Unauthorized”,
“message”: “Access to the resource is forbidden”,
“details”: “”
}

Any ideas?

**Comment by pengxiaoyang123** [comment]
Settlement reports cannot be requested or scheduled. They are automatically scheduled by Amazon. You can search for these reports using the getReports operation.

**Comment by dobariyarakesh** [comment]
Can you post full request here so that can help to check issue

**Comment by rugved1991** [comment]
Hi @YFBook,

Please make sure your application has "Amazon Fulfillment" role enabled on it in order to make successful request to this report type. Please add this role to your app and get a new set of refresh and access token so that you can include the newly added role permissions to the request.
If you are still seeing an error, please open up a support case with the complete request and response details along with response headers. You can provide the case ID here so that we can track the issue on our side.

Thanks,
Rugved
Solutions Architect, SP API

**Comment by ansgarbecker** [comment]
I got the same 403 error with the report type `GET_ORDERS_DATA`. My SP API app client has all roles enabled, and I created a new refresh token plus new access key set in AWS. After googling around I found the `GET_ORDERS_DATA` is not available to the SP API, and it [has been replaced by `GET_ORDER_REPORT_DATA_INVOICING`](https://github.com/amzn/selling-partner-api-docs/issues/2397#issuecomment-1175071944). This is highly confusing, and non-intuitive. For what purpose are you renaming report types?
On top of that, the `GET_ORDER_REPORT_DATA_INVOICING` is one of the restricted reports, which require a Restricted Data Token (RDT) in the relevant report API operations. MWS API did not require such an RDT.
