### ISSUE TITLE
[FEATURE] Documentation Rate Limit / Burst explanation

### ISSUE THREAD

**Issue by xbaha** [amzn/selling-partner-api-docs#796]
The getOrderItems has a Rate (requests per second) 0.0055 and a Burst of 20
Does that mean I can send 20 calls, then 1 call every 181 seconds??? (1/0.0055)
I am unsure if I understood this, I figured this out based on the was docs: https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-request-throttling.html

**Comment by jhullparkseed** [comment]
I am also looking for a better explanation so I can code limits in before hitting limits.  What is frustrating with this new order model is  instead of getting all order data in "GetOrder" I now have  make 4 separate calls per order which seems less efficient.  I would rather a switch on GetOrder that allows to get all or just header data.

**Comment by xbaha** [comment]
it seems true, 1 call per 3 minutes... not sure what Amazon is trying to say here?

**Comment by iceleo-com** [comment]
Amazon is not active. Nearly a thousand tickets here, but everything is still pending
It is likely we cannot touch the giant
