### ISSUE TITLE
searchCatalogItems sorting?

### ISSUE THREAD

**Issue by amz-tools** [amzn/selling-partner-api-docs#829]
We noticed the new endpoint [searchCatologItems](https://github.com/amzn/selling-partner-api-docs/blob/main/references/catalog-items-api/catalogItems_2020-12-01.md#searchcatalogitems) is returning ASINs for a specific keyword or set of keywords. And in contrast to [listCatalogItems](https://github.com/amzn/selling-partner-api-docs/blob/main/references/catalog-items-api/catalogItemsV0.md#listcatalogitems) it is possible to retrieve up to 1000 ASINs instead of only 10.

We are wondering though about the sorting. The listCatalogItems endpoint is returning the ASINs by popularity quite similar as doing a manual search on Amazon. The searchCatalogItems is in a different order. Is there any logic behind the sorting? Or is it possible/planned to include an option that would i.e. enable to sort the ASINs returned by the searchCatalogItems quite similar to the sorting of the listCatalogItems? This would really improve the use of this new endpoint!

**Comment by chapmanjw** [comment]
Hi @amz-tools. The new Catalog Search API sorts results based on popularity/relevancy. If we were to add the ability to ask for different sorting on the request, what would be most useful to add (such as sorting on item name, or some other facet)?

**Comment by amz-tools** [comment]
Hi @chapmanjw, thanks for your reply. What we would really appreciate is a sorting that returns the items in a comparable sorting to the default sorting on the website when searching for a keyword or a set of keywords.

Right now this is already the case with the listCatalogItems operation. It essentially returns the Top 10 items for a specific query quite comparable to a manual search on the website with the same query. However, it is not possible to retrieve more than 10 items with the listCatalogItems operation (in contrast to the searchCatalogItems operation returning up to 1000 items).

In fact we would be very happy if you could enhance the API by one of these two possibilities:
- The possibility to change the searchCatalogItems operation sorting order to represent the one currently used for the listCatalogItems operation
- The possibility to retrieve more than 10 items when using the listCatalogItems operation

**Comment by chapmanjw** [comment]
Hi @amz-tools, the V0 (ListCatalogItems) operations is on a deprecation path. See https://github.com/amzn/selling-partner-api-docs/discussions/1041.

The new SearchCatalogItems API is focused on "sellable" products as opposed to "buyable" products (where search relevancy is based on seller popularity instead of buyer popularity). While we would not be able to replicate the search behavior of the retail websites exactly, we could look at options to sort on dimensions like sales ranks.

**Comment by amz-tools** [comment]
@chapmanjw Thanks for the info about the deprecation of listCatalogItems. This is quite an issue, I guess not just for us but for many developers. This will remove the opportunity of retrieving the top products of a search (top products in the sense of buyer popularity, as you call it).

What I am wondering though: You say its not possible to replicate the search behavior exactly, but for the soon to be deprecated listCatalogItems you are already doing just that. Sorry to say so, but that sounds strange to me. Is it possible that Amazon maybe doesn't want to return products based on buyer popularity in future API releases in order to prevent developers from having an easy way of retrieving a "real" search result via the API?

**Comment by chapmanjw** [comment]
@amz-tools The issue with focusing on mimicking the "retail website" search functionality is that it is entirely focused on the buyer experience and does not cover seller use-cases. For example, today, you cannot get ASINs in the `listCatalogItems` operation if they do not have any buyable offers or have other factors preventing them from being included in search results on the retail website. The prevailing feedback we have received from developers is that such ASINs can be found only when searching on Seller Central, but not in the APIs. The expectation from developers based on the feedback we have received so far is that the API search results should be comparable to the search results on Seller Central when listing products. The goal of these APIs is to provide similar or identical functionality to what sellers see on Seller Central, not the buyer-facing experiences. 

Our primary concern with the new API was ensuring we cover all "sellable" ASINs to enable discovery for selling items, even if they would have been omitted from retail website search results. We don't have a mechanism to accomplish both mirroring retail website search results behavior while also ensuring all sellable ASINs are provided. While we could consider adding more sorting options as a future iteration of this API, "sellable" ASINs will always be the focus of this API as those are most broadly applicable to the use-cases supported by Selling Partner APIs.

I've captured an action item for my team to investigate what additional sorting options we can provide within the scope of "sellable" ASINs. It may be possible to achieve similar ranking, albeit with all matching "sellable" ASINs as opposed to only "buyable" ASINs. 

Please submit a support case (if you haven't already) so that we can follow up on this directly with you. Thanks!

**Comment by ellis** [comment]
@chapmanjw I want to echo the concern of @amz-tool

The loss of `listCatalogItems` would be a major loss for our agency.  We use it to keep track of our clients' top ranking products and their top competitors, which the new `searchCatalogItems` method doesn't support.  Even sorting by BSR would not be helpful, because we need to stay on top of organic ranking per keyword.

**Comment by ellis** [comment]
@chapmanjw @amz-tools @teddy-codes I submitted Support Case 7344929922, and received a frustrating response:

> listCatalogItems ranks results based on buyability and is generally similar to the search results you'd see on Amazon.com.
> 
> searchCatalogItems is intended to be seller oriented and presents ASINs in the same order as you would see them on the Seller Central product search page. These results can include ASINs that might be very relevant to seller's but not at all relevant to a buyer.
> 
> If you are interested in results ranked the same way as they are on Amazon.com, you could explore calling the Product Advertising API SearchItems:
> https://webservices.amazon.com/paapi5/documentation/search-items.html
>
> Please note the issue related to Product Advertising API is handled by Amazon Associates Support team, so if you have any question regarding to the Product Advertising API, please refer to:
> https://webservices.amazon.com/paapi5/documentation/contact-us.html

Here's the two-part problem:

1\. We're asking/begging for `listCatalogItems` NOT to be retired because it covers a **very important** use case for us and our clients.  Its replacement, `searchCatalogItems`, can't cover the same use case, and it sounds like there is no interest in making it cover the same use case.

2\. Thanks for suggesting an alternative API.  Unfortunately, on the [registration page](https://webservices.amazon.com/paapi5/documentation/register-for-pa-api.html), we see that we don't qualify!:

> Product Advertising API sign up is available only to associates who have referred qualified sales and have been accepted into the program.

How about just not removing `listCatalogItems`???

**Comment by callumb123** [comment]
I wanted to add to the above that for MANY requests using the exact same query string can result in searchCatalogItems returning zero matches whereas listCatalogItems returns 10 matches. In what case is this useful to developers? I don't see how this is reflecting sellable items better than listCatalogItems?

In its current state searchCatalogItems is almost useless for my current use case and will completely destroy my application if it fully replaces listCatalogItems.

**Comment by chapmanjw** [comment]
@ellis Updated information on the deprecation timelines for the older APIs has been published: https://github.com/amzn/selling-partner-api-docs/discussions/1781. 

In our original deprecation announcement back in the summer, we indicated that we are taking all of the feedback received in 2021 so that we can ensure we are covering the right use-cases in the Catalog Item APIs before finally deprecating the other APIs. So, to that end, thank you for the detailed feedback thus far. 

I don't see that the support case ever made it to my team, so I will follow up on that next.

**Comment by ganeshkrishnan1** [comment]
Commenting to reopen this. We need a way to get list of catalog items that sellers know if their products are in the search results. The search catalog items returns random list that has no relation to the search results of the buyer. Hence this api should be available and not deprecated
