### ISSUE TITLE
Best way to acknowledge orders with Seller-API

### ISSUE THREAD

**Issue by Bowserlord** [amzn/selling-partner-api-docs#935]
Hello together,

what is in your opinion the best way with the new Seller-API to acknowledge orders (**without using a vendor-api**)?
I guess the Order-API is only for Order-Informations (like BuyerInfo and Address) so u cant acknowledge via a simple REST Call. On the Report-API section,  i also didnt find a way to acknowledge order-reports.
The only way i found was the 'POST_ORDER_ACKNOWLEDGEMENT_DATA' - Feedtype, where u upload a .xml-feed to acknowledge an OrderID. Due the processing, u also have to wait and check, if the processing was successful.

Is there a "better" or smarter way to do this?

Beste Regards and thanks for help.

**Comment by marconline** [comment]
Good question. Acknowledging orders and reports are two different operations with two distinct meanings.
Acknowledging an order means that you are telling Amazon "Hey, I'm ok with this order" and basically you link your Order ID to the Amazon Order Id. You do that by streaming a POST_ORDER_ACKNOWLEDGMENT_DATA feed. 

Acknowledging a report means that you are telling Amazon "Hey, I'm ok with this report". This operation, that previously on MWS was available, it seems that it's not available with SP-API. This is miss is a problem since there is no way for us to download generated reports that have not been fully processed (i.e. not acknoweldged).
