### ISSUE TITLE
Fulfillment Inbound method getLabels, get InvalidInput error 

### ISSUE THREAD

**Issue by FexusZ** [amzn/selling-partner-api-docs#94]
Hello, I am trying to use the 'getLabels' method :
 https://sellingpartnerapi-eu.amazon.com/fba/inbound/v0/shipments/{shipmentId}/labels?PageType=PackageLabel_Thermal&LabelType=DEFAULT, but I get the error :
errors": [
    {
      "code": "InvalidInput",
      "message": "pageSize must be provided for Non-Partnered and LTL Shipments. Cannot print labels [shipmentId=shipmentId]",
      "details": ""
    }
  ]
}
But i don't see any pageSize in the documentation.

**Comment by charliecode** [comment]
@FexusZ I'm having the exact same issue. I created a support case for it (7542535591) on Oct 27th and have not yet received a response from Amazon. Soon as I do I'll put what they say here. I've researched it for countless hours and tried so many things to fix it but cannot figure it out, it appears to be an issue with the API. I would recommend you also create a support case and hopefully you'll get contacted soon.

**Comment by FexusZ** [comment]
@charliecode I did not find where the problem came from for the "LabelType = DEFAULT", but I was able to retrieve a label with "LabelType = UNIQUE", and passing "PackageLabelsToPrint = id of package"

**Comment by charliecode** [comment]
@FexusZ I finally received a response from Amazon about this issue. Here is their response:

**"Our findings so far indicate that the DEFAULT "labelType" parameter is selected for these kind of shipments as this option is no longer supported, however, the code itself does allow the option which in turn generates this errors.

We are working with our back-end teams to resolve this matter and, as soon as additional details are available I will be sure to reach back when an update is pushed to GitHub.

In the meanwhile, we have been instructed that the best way around this issue is to use the UNIQUE labelType option and pass the cartonIds in the PackageLabelsToPrint parameter for this kind of shipments."**

Of course, with support saying they will no longer support the DEFAULT labelType and subsequent encouragement to use the UNIQUE labelType and pass the cartonIds in the PackageLabelsToPrint means you need to send carton content info via the feeds api, this immediately brings up the question "What about using 2d barcodes for supplying carton contents?" Are 2d barcodes going to continue to be supported for carton contents? Would be really nice to get some official direction on this. @seanevan @edaik

**Comment by charliecode** [comment]
@FexusZ This issue can now be closed. It was fixed with [this commit](https://github.com/amzn/selling-partner-api-docs/commit/81fe79a31ef37446c6c321d16015278a0ef5f026). The InvalidInput error arising because the request would not accept the pageSize param for Non-Partnered and LTL Shipments is no longer an issue. 

Some request params have been added and some changed, so in order to make a successful request your client side API request code will need to be updated. [You can find the changes to params here.](https://github.com/amzn/selling-partner-api-docs/blob/main/references/fulfillment-inbound-api/fulfillmentInboundV0.md#getlabels)

A big thanks to @edaik for getting this fixed and especially @parvathm who IMO is the most prompt, professional and highly qualified Support Engineer I've ever dealt with at Amazon or any company for that matter.

**Comment by parvathm** [comment]
Hi,

I am closing this issue as part of this  [commit](https://github.com/amzn/selling-partner-api-docs/commit/81fe79a31ef37446c6c321d16015278a0ef5f026). If you still have any questions please let us know.

Thanks,
Parvathm,
Selling Partner API Developer Support.
