### ISSUE TITLE
FbaInboundApi createInboundShipmentPlan doesn't accept address

### ISSUE THREAD

**Issue by castorachel** [amzn/selling-partner-api-docs#941]
I'm trying to create an inbound shipment plan, but it doesn't seem to be accepting my address no matter what I do. I'm having trouble with the Address class all over sp api. None of my objects have a problem with it until I call createInboundShipmentPlan. Is there some format I'm not following?

How I make an Address:
Address warehouse = new Address();
warehouse.setName("XXXXXXXX");
warehouse.setAddressLine1("XXX BXXXXX Ln  #3");
warehouse.setCity("XXXXX");
warehouse.setStateOrRegion("OH");
warehouse.setPostalCode("XXXXX");
warehouse.setCountryCode("US");

Error response body I get:
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": " Reason: Country field is missing, Name field is missing, AddressLine1 field is missing.",
      "details": ""
    }
  ]
}

**Comment by pengjun132** [comment]
In FbaInboundApi, createInboundShipmentPlanRequest doesn't use body when forms request.

$httpBody = ''; should be $httpBody = $body;

https://github.com/clousale/amazon-sp-api-php/issues/87

**Comment by rockchiu** [comment]
I have the same problem too.
Whatever I change any address for createInboundShipmentPlan. The AP has always returned  the "InvalidInput message: Reason: Country field is missing, Name field is missing, AddressLine1 field is missing." error.
But I very sure my address have Country, Name & AddressLine1 data filled.
PS: I used java client.

**Comment by rockchiu** [comment]
Hi, guys:
I have found the where the problem is, that because Address parameter name is wrong for the request.
Here is our use swagger jar to generate the Java API client code:
<img width="1190" alt="Address_java__4671___4681__—_SP_API_JavaCL" src="https://user-images.githubusercontent.com/7351485/129131311-a8dd2d7a-a632-4c02-9f9d-cfd7170902fa.png">
I change the parameter name from source code, and then the request is succeeded.
Thanks for your kind reminder to check the request parameter.
Rock
