### ISSUE TITLE
Basic Questions about Amazon APIs

### ISSUE THREAD

**Issue by Avisa13** [amzn/selling-partner-api-docs#962]
Hello,

First of all, we have tried to contact via "api-services-support@amazon.com" but the mailbox is full.

So, we have some basic questions that we could not figure out. If someone can explain them it would be greatly appreciated.

**1)** On MWS, with **GetMatchingProductForId** service, does it return information for any available product on Amazon website? I mean, the products that are not sold by us. For example; for the following **ASIN: B08VN3Q6KM** (We do not have any relation with the product and sellers). The question is also same for the **SP-API** for **GetCatalogItem** service.

**2)** On MWS, **GetMatchingProductForId** service returns only the main image of the product. On the forums, some of the users say, to get the all images which can be seen on Amazon publicly, can be fetched by Product Advertising API not by MWS, is it correct?

**3)** We also see that, **SP-API -> GetCatalogItem** has an attribute which returns all images from random product that we searched by ASIN on Amazon. But it says "**All image variants are provided to brand owners**.". Is there any restriction that can prevent us to access all images shown on Amazon for a random product?

![image](https://user-images.githubusercontent.com/86690840/123872399-b520f300-d93d-11eb-9bbd-bc56c4ed6389.png)

Thanks in advance.
Best regards.

**Comment by stefnats** [comment]
The official of contacting dev support is eithere here or on https://developer.amazonservices.com

Please note that the MWS API (as you asked in 1&2) is deprecated and this is only about SP API

1) Yes

2) Product Advertising API is only for Advertisers, i.e. people that have sites/blogs/etc. and recommend Amazon Items. If you have no such site, your appeal to use this API will get denied or later blocked. I don't know of any way to retrieve the other images, but maybe anybody on here does. Also, try to contact official Dev Support and keep us updated here, please.

3) I hope i understand this right. As you have stated in 1) that you have no relation to the ASIN, you will only be provided the Main Image. If this is your item / brand you will receive the other images as well.

**Comment by Avisa13** [comment]
@stefnats, thank you for your response.

Right now, we do not have a seller account which is needed to access to the support. 
We are in analysis phase, so because of that, we are collecting the information as far as we can get.

I have one last question, I have looked at everywhere but could not figure out how to check if an ASIN has a stock and available to be sold.

We are going check the products' prices  regularly and also would like to check if it is in stock. (Currently available for sale).
We are planning to use 'product-pricing-api' from SP-API for checking prices.

What is the method to check if a product is available for sale(In stock) by querying ASIN? 

We are really appreciated with your response. Thanks for it again.

We are also going to share the information that we found about these questions when we figured out.

Best regards.

**Comment by Avisa13** [comment]
@stefnats 

Did you have time to look for my comment above? We really appreciate your help.

> The official of contacting dev support is eithere here or on https://developer.amazonservices.com
> 
> Please note that the MWS API (as you asked in 1&2) is deprecated and this is only about SP API
> 
> 1. Yes
> 2. Product Advertising API is only for Advertisers, i.e. people that have sites/blogs/etc. and recommend Amazon Items. If you have no such site, your appeal to use this API will get denied or later blocked. I don't know of any way to retrieve the other images, but maybe anybody on here does. Also, try to contact official Dev Support and keep us updated here, please.
> 3. I hope i understand this right. As you have stated in 1) that you have no relation to the ASIN, you will only be provided the Main Image. If this is your item / brand you will receive the other images as well.

**Comment by stefnats** [comment]
Hey @Avisa13
Please note that I'm not an Amazon official, just a fellow dev :)
I think the product pricing Api getitemoffers call might be usable to check if an item is on stock (generally, by any seller). If it sends a list that is not empty, there are offers and those are on stock. If you need to check those prices regularly and you're selling that item yourself, you can use the notifications Api to receive ANY_OFFER_CHANGED notifications when the price for an asin/seller has changed.

**Comment by chapmanjw** [comment]
@Avisa13 As mentioned on this announcement: https://github.com/amzn/selling-partner-api-docs/discussions/1041, the MWS GetMatchingProduct and Catalog Item V0 operations will be deprecated in the coming year. The new [searchCatalogItems](https://github.com/amzn/selling-partner-api-docs/blob/main/references/catalog-items-api/catalogItems_2020-12-01.md#searchcatalogitems) and [getCatalogItem](https://github.com/amzn/selling-partner-api-docs/blob/main/references/catalog-items-api/catalogItems_2020-12-01.md#getcatalogitem) operations are their replacements. You can find more details on what they support in the [use case guide](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/catalog-items-api-use-case-guide/catalog-items-use-case-guide_2020-12-01.md). 

With these you can search and retrieve summary details about any ASIN in the Amazon catalog (regardless if the seller has a relationship with that ASIN or not). This includes a thumbnail of the main product image. In order to retrieve more detailed information about the item with these ASINs, such as all of the product images, the seller must be the brand owner of the ASIN.

**Comment by chapmanjw** [comment]
@Avisa13 We have updated the 2020-12-01 version of the Catalog Items Get API to no longer require brand affiliation with an ASIN in order to retrieve the raw `attributes` data set. Requesting the `attributes` data set will return all attributes for an ASIN that are defined by the Product Type Definitions API for the product type of the ASIN. As we are in-progress of migrating product types to the APIs, some ASINs will continue to rollup to the `PRODUCT` product type for the available attributes and only include the attributes that are defined on the root `PRODUCT` product type. 

While the `attributes` data will assist in inspecting the "raw" attributes for an ASIN, it is unmodeled data and is not ideal for some use-cases depending on modeled data (i.e., modeled in the Swagger model). With that in mind, we do still plan another release where additional details are added to the Swagger model of the `summaries` and `variations` sections. 

Thanks for the feedback thus far and helping us to refine this product!
