### ISSUE TITLE
Need a replacement for the Get_Date_Range_Financial_Transaction_Data Report in Reports-API

### ISSUE THREAD

**Issue by ezpinsky** [amzn/selling-partner-api-docs#967]
### Issue: 
I need a replacement for the GET_DATE_RANGE_FINANCIAL_TRANSACTION_DATA report that you can request in MWS. It has been deprecated in SP-API. For those that don’t know, this is the same report as the Date Range Report that can be downloaded in Seller Central. I use the information in this report to track my refunds to customers and find the average price I sell my units for (less the fees).

### Potential Solution: 
I found that if I normalize the data from the GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE report, it can be used to replace Date Range, however this settlement report is unfortunately limited to only the past 90 days worth of settlement data and the report can only be generated by Amazon. The thing is, I can literally go into seller central and download the same settlement data report going back to the beginning of my account so why is there a limit to 90 days for SP-API?
Please developers can you allow us to get more than 90 days for the settlement report or let us get the date range report again?
Any help would be appreciated thank you!

**Comment by stefnats** [comment]
My approach would be to query the finances API:
https://github.com/amzn/selling-partner-api-docs/blob/main/references/finances-api/financesV0.md#listfinancialevents

**Comment by ezpinsky** [comment]
Thank you @stefnats. I will give that a try. It looks promising.

**Comment by jayallu** [comment]
@ezpinsky any luck with the finance API to fetch date range report ?

**Comment by nilimarodrigues** [comment]
Hello @ezpinsky - were you able to figure out how to obtain "Date Range Report" using Finance APIs? We are in the same boat. The "Date Range Report" is very useful because it provides all transactional details including refunds as well as fees etc. We do not get these details from "Fulfillment Report". The "Settlement Report" as you called out in your other discussions, these reports are scheduled by Amazon and are generated only when settlement happens which does not help our purpose of receiving transactional data every day for the previous day.

Any help or direction that you can provide would be really appreciated! Thank you.
