### ISSUE TITLE
stop using github bugs to make announcements

### ISSUE THREAD

**Issue by johnkw** [amzn/selling-partner-api-docs#990]
Please stop using github bugs to make announcements. There is no way to subscribe to announcements, so these are mostly going to end up being lost/ignored.

See for example @jenilew in bug #945 - this should not have been created as a bug. Instead it should be a Github Announcement. Github supports this feature natively. Go to "Settings" on the /amzn/selling-partner-api-docs repository and scroll down to "Discussions" and click set up.

If you want, you can disable everything except for Announcements.

If you make announcements in the Announcements, then users can actually subscribe in github and get notifications of the announcements.

**Comment by ezpinsky** [comment]
THIS!!

**Comment by ShivikaK** [comment]
Hello @johnkw 

Thank you for your feedback! It has conveyed to our documentation team for further consideration.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by jenilew** [comment]
Hi @johnkw and @ezpinsky,

Thank you for the suggestion! I was not aware of this feature previously and we are investigating it. 

Look for an update later this week. :)

Keep the suggestions coming...

Best, 
Jen Lewis
Selling Partner API Content Team

**Comment by johnkw** [comment]
It's great that these were moved to the more helpful spot.

However it would be useful not to lock all of the announcements.

For example the first announcement I looked at has some serious problems, but I can't reply to point them out.

https://github.com/amzn/selling-partner-api-docs/discussions/1072 has a broken link, and the announcement itself is now out of date because the new API no longer requires the pointless extra layer of encryption on top of HTTPS. Reporting that in the announcement as a comment would be helpful to anyone looking at the original.  As it stands, the original is stuck in this unhelpful state and it's extremely difficult to report the problem.  I'm hoping some admin happens to see this comment and then makes note of the issue in the 1072 post.

**Comment by jenilew** [comment]
Hi JohnKW,

Thanks again for your feedback. 

The link has been updated in announcement #1072. The Guides folder structure has changed since that announcement was posted back in Sept 2020 and that change broke the link. 

I have not removed the announcement or pointer to the Documents Helper. While not relevant for those who integrate with the new version of Feeds and Reports; it is still relevant for those using the 2020-09-04 version. Those developers will still need it for encryption/decryption and there are developers who've integrated with that version who aren't planning to migrate immediately to the newer version.

More broadly, it's expected that announcements will go out of date sometimes because they are point-in-time information. We do not typically update past announcements for minor changes because it degrades the historical view. We will update current announcements with release date changes or critical changes to what's been announced to reduce any confusion. 

**Note**: Some of the older announcements moved to the Discussions tab have the date in the title line. This is due to limitations with GitHub functionality. We wanted to ensure the full announcement history is available when we migrated them to the new location. Some of them could not be migrated but had to be reposted and this changed the posting date on the announcement. In those instances, we've included the date in the title to make it clear these are older announcements.

You're welcome to post feedback about Announcements, or any documentation, here in the Issues tab. We've chosen not to enable commenting on the Announcements itself because it is Amazon's communication out to our developer community. Enabling comments introduces the possibility that Search functionality becomes diluted (i.e. not as useful) because it will return the results on comments; as well as the announcements themselves. This can delay finding the announcement you're looking for when searching. 

As indicated by this thread, we do pay attention to feedback. We will address or respond to feedback as we receive it and update any Announcements accordingly. 

Hope this helps explain some of our thinking around this area. Please continue to let us know how we can do better!

Sincerely, 

Jen
The Selling Partner API Team

**Comment by johnkw** [comment]
Thanks. I do think it's good to maintain the older Announcements. But they should be annotated when they're out of date, and it's hard to maintain that if no one can reply to them.

Also, if you're worried about difficulty searching, then it's far worse to be filing github doc bugs to point out that an Announcement has a problem.  Being able to reply directly to the Announcement would be far simpler.

This github currentlly has 599 open bugs.  It's completely out of control.  When I get an update from Seller Central about a bug fix, it's hard to find the open github bug it corresponds to, due to the sheer enormous number of open bugs.
