### ISSUE TITLE
Best way to get all seller's listings

### ISSUE THREAD

**Issue by yuri-lonesomelabs** [amzn/selling-partner-api-docs#992]
Hi, 
what would be the best way to get all the listings of the seller vie the SPAPI? I saw someone suggests using `_GET_MERCHANT_LISTINGS_DATA_ ` report. Is this the "right" way, or is there a dedicated API endpoint for that?

**Comment by johnkw** [comment]
It's been renamed to `GET_MERCHANT_LISTINGS_ALL_DATA` now, but fairly sure that's true, and it would be good to add documentation to the top of the https://github.com/amzn/selling-partner-api-docs/blob/main/references/listings-items-api/listingsItems_2020-09-01.md page to say something like "in order to retrieve listings, see the reports endpoint, specifically `GET_MERCHANT_LISTINGS_ALL_DATA`."

See also #421 for documenting the reports.

**Comment by yuri-lonesomelabs** [comment]
It's a great point regarding the docs.

**Comment by johnkw** [comment]
Hold on, this bug should remain open until the above documentation blurb is added.
